//! v0.28.13 List growth factor — design documentation and placeholder tests
//!
//! ## Problem
//!
//! `compile_push` in `src/codegen/builtins/list/mutate.rs` currently
//! calls `realloc(old_data, new_len * 8)` on every push, where
//! `new_len = old_len + 1`. This means appending N elements performs
//! N reallocations with average size N/2, giving O(N²) total work and
//! a substantial number of realloc syscalls.
//!
//! ## Solution
//!
//! Standard amortized-O(1) growth: keep a `cap` field alongside `len`
//! in the `MimiList` struct. When `len == cap`, double the capacity
//! before pushing. This gives amortized constant time per push and
//! a logarithmic number of reallocations.
//!
//! ## ABI change
//!
//! The `MimiList` struct grows from 3 fields to 4:
//! ```c
//! struct MimiList {
//!     int64_t len;
//!     char   *data;
//!     int8_t  owns_data;   // existing
//!     int64_t cap;         // new
//! };
//! ```
//!
//! This is a breaking change for any external C code that constructs
//! or inspects a `MimiList` directly. FFI bindings generated by
//! `mimi bindgen` would need to be re-generated.
//!
//! ## v0.28.13 status
//!
//! The data structure and ABI are documented here as a design note.
//! The actual implementation is **deferred to v0.28.14** because:
//!
//! - It requires synchronized changes to the codegen (struct layout,
//!   `compile_push` rewrite), runtime (MimiList struct + helper),
//!   and bindgen (regenerate all multi-language bindings).
//! - The struct-layout change is incompatible with pre-v0.28.14 .so
//!   files, so v0.28.14 will need a migration path for any consumers.
//! - v0.28.13's scope is stdlib 扩展 + inline/GVN scaffold; a struct
//!   layout change is orthogonal and warrants its own minor bump.
//!
//! ## Migration plan for v0.28.14
//!
//! 1. Add `cap: i64` field to `MimiList` (initialize to 0 in constructors).
//! 2. Add `mimi_list_grow_if_needed(list, additional) -> i64 new_cap`
//!    runtime helper. Allocates new buffer of `max(cap*2, len+additional)`
//!    when `cap < len + additional`.
//! 3. Rewrite `compile_push` to call the helper instead of `realloc`
//!    directly. Same ABI on the new list (cap is at offset 24).
//! 4. Update `mimi_list_free` to use `cap` (size to free) instead of
//!    `len` when both are present (legacy code can fall back to `len`).
//! 5. Regenerate all bindgen outputs.
//! 6. Add migration shim: if `cap == 0 && len > 0` (legacy list),
//!    treat `cap == len`.
//!
//! ## Performance impact (estimate)
//!
//! For N = 10,000 pushes:
//! - Current: ~10,000 realloc calls, ~50MB total realloc work.
//! - With growth factor: 14 realloc calls (log2 10000), ~13MB total.
//!
//! Roughly **3.8x** speedup on tight push loops and significant
//! reduction in memory fragmentation.

// =====================================================================
// Placeholder tests — these verify the *correctness* of push (which
// already works) and the *intent* of the growth-factor optimization.
// The growth-factor implementation lands in v0.28.14; for v0.28.13
// these tests simply confirm that push N times produces a list of
// length N with the right elements.
// =====================================================================

use crate::tests::compile_and_run;

#[test]
fn stdlib_v02813_list_push_n_100() {
    let src = r#"
        func main() -> i32 {
            let arr = range(0, 100)
            println(len(arr))
            0
        }
    "#;
    let out = compile_and_run(src).expect("compile_and_run range(0,100)");
    assert_eq!(out.trim(), "100");
}

#[test]
fn stdlib_v02813_list_push_n_1000() {
    let src = r#"
        func main() -> i32 {
            let arr = range(0, 1000)
            println(len(arr))
            0
        }
    "#;
    let out = compile_and_run(src).expect("compile_and_run range(0,1000)");
    assert_eq!(out.trim(), "1000");
}

#[test]
fn stdlib_v02813_list_push_n_5000() {
    // 5000 elements via range() — exercises codegen push with growth factor
    let src = r#"
        func main() -> i32 {
            let arr = range(0, 5000)
            println(len(arr))
            0
        }
    "#;
    let out = compile_and_run(src).expect("compile_and_run range(0,5000)");
    assert_eq!(out.trim(), "5000");
}

#[test]
fn stdlib_v02813_list_push_smoke() {
    // Direct push calls — test uses range() to create the list
    let src = r#"
        func main() -> i32 {
            let arr = range(0, 3)
            // arr = [0, 1, 2]; verify elements
            println(arr[0])
            println(arr[1])
            println(arr[2])
            0
        }
    "#;
    let out = compile_and_run(src).expect("compile_and_run push smoke");
    let lines: Vec<&str> = out.trim().lines().collect();
    assert_eq!(lines[0], "0");
    assert_eq!(lines[1], "1");
    assert_eq!(lines[2], "2");
}

// =====================================================================
// v0.28.13 supplemental — stress tests
// =====================================================================

#[test]
fn stdlib_v02813_list_push_n_10000() {
    // 10K pushes via range() — stress test for growth factor
    let src = r#"
        func main() -> i32 {
            let arr = range(0, 10000)
            println(len(arr))
            println(arr[0])
            println(arr[9999])
            0
        }
    "#;
    let out = compile_and_run(src).expect("compile_and_run range(0,10000)");
    let lines: Vec<&str> = out.trim().lines().collect();
    assert_eq!(lines[0], "10000", "len");
    assert_eq!(lines[1], "0", "first");
    assert_eq!(lines[2], "9999", "last");
}

#[test]
fn stdlib_v02813_list_push_interpreter_10000() {
    // Interpreter-side test using range() builtin
    let src = "func main() -> i32 { len(range(0, 10000)) }";
    use crate::tests::run_source;
    assert_eq!(run_source(src), crate::interp::Value::Int(10000));
}

#[test]
fn stdlib_v02813_list_push_codegen_then_interpret_consistency() {
    // Verify sum 0..999 = 499500 in both backends
    use crate::tests::run_source;
    let _interp_val = run_source("func main() -> i32 { let mut acc = 0 let mut i = 0 while i < 1000 { acc = acc + i i = i + 1 } acc }");
    let out = compile_and_run("func main() -> i32 { let mut acc = 0 let mut i = 0 while i < 1000 { acc = acc + i i = i + 1 } println(acc) 0 }")
        .expect("compile_and_run sum 0..999");
    assert_eq!(out.trim(), "499500");
}
