// ===========================================================================
// v0.28.19 — Actor Codegen Real Concurrency (extracted from runtime/mod.rs)
//
// The runtime owns a mailbox + dedicated worker thread per actor, mirroring
// the interpreter's `ActorHandle::new` pattern.  Actor method bodies are
// LLVM-compiled functions; the runtime invokes them indirectly through a
// per-actor-type *dispatch function* generated by codegen.
//
// This module owns the live-actor registry (`LIVE_ACTORS`) and all
// `mimi_actor_*` / `mimi_broadcast*` extern "C" entry points.
// ===========================================================================

use std::collections::HashMap;
use std::sync::Mutex;

// --- live-actor registry ---

static LIVE_ACTORS: std::sync::OnceLock<Mutex<HashMap<usize, std::sync::Arc<MimiActorRepr>>>> =
    std::sync::OnceLock::new();

fn live_actors() -> &'static Mutex<HashMap<usize, std::sync::Arc<MimiActorRepr>>> {
    LIVE_ACTORS.get_or_init(|| Mutex::new(HashMap::new()))
}

fn actor_take_live(handle: usize) -> Option<std::sync::Arc<MimiActorRepr>> {
    if handle == 0 {
        return None;
    }
    let mut g = live_actors().lock().unwrap_or_else(|e| e.into_inner());
    g.remove(&handle)
}
fn actor_pin_live(handle: usize) -> Option<std::sync::Arc<MimiActorRepr>> {
    if handle == 0 {
        return None;
    }
    let g = live_actors().lock().unwrap_or_else(|e| e.into_inner());
    g.get(&handle).cloned()
}

/// Maximum size of the args blob and result blob.
/// Struct/string arguments that exceed this are passed by pointer.
const MIMI_ACTOR_BLOB_SIZE: usize = 256;

/// Actor message enqueued into the mailbox.
struct ActorMailboxMsg {
    /// Which method to invoke (index into the actor's method list).
    method_id: i32,
    /// Packed argument blob (method params laid out sequentially).
    args: Vec<u8>,
    /// Channel to send the packed result back to the caller.
    response: std::sync::mpsc::Sender<ActorMsgResult>,
}

/// Result returned from a mailbox message execution.
struct ActorMsgResult {
    /// Packed result blob.
    data: Vec<u8>,
    /// Number of bytes written.
    size: u64,
}

/// Runtime representation of a live actor instance.
/// Stored on the heap; the opaque pointer returned to codegen is `*mut MimiActorRepr`.
struct MimiActorRepr {
    /// Unique actor ID for self-call deadlock avoidance.
    id: u64,
    /// Parent actor captured from the spawning worker. Top-level and detached
    /// actors have no parent.
    parent_id: Option<u64>,
    /// Detached actors are excluded from parent SystemKill cascades.
    detached: bool,
    /// Reserved for future use: a heap-allocated field blob accessible from
    /// the handle side. Currently the worker thread owns the live field storage;
    /// all field access goes through the mailbox dispatch path.
    #[allow(dead_code)]
    fields: Box<[u8]>,
    /// Mailbox sender — clone retained by the handle; worker holds the receiver.
    mailbox_tx: std::sync::Mutex<Option<std::sync::mpsc::Sender<ActorMailboxMsg>>>,
    /// Worker thread join handle (joined on drop).
    worker: std::sync::Mutex<Option<std::thread::JoinHandle<()>>>,
    /// v0.29.11: Fault absorption — when set, mailbox is short-circuited (O(1)).
    /// Shared with the worker so both call and drain paths see the same flag.
    faulted: std::sync::Arc<std::sync::atomic::AtomicBool>,
    /// v0.29.21: mailbox high-water depth limit.
    mailbox_depth_limit: std::sync::atomic::AtomicUsize,
    /// v0.29.21: approximate in-flight message count.
    mailbox_depth: std::sync::Arc<std::sync::atomic::AtomicUsize>,
    /// v0.29.21: muted under backpressure.
    muted: std::sync::Arc<std::sync::atomic::AtomicBool>,
    /// v0.29.25: method_id → method name for polymorphic broadcast name resolution.
    method_names: std::sync::Mutex<Vec<String>>,
}

impl Drop for MimiActorRepr {
    fn drop(&mut self) {
        // Closing the final sender lets the worker drain queued messages and exit.
        self.mailbox_tx
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .take();
        if let Some(worker) = self.worker.lock().unwrap_or_else(|e| e.into_inner()).take() {
            // SystemKill may be initiated by the actor itself. Dropping the
            // JoinHandle detaches in that case; the closed mailbox lets the
            // worker return immediately after the current dispatch.
            if worker.thread().id() != std::thread::current().id() {
                let _ = worker.join();
            }
        }
    }
}

// SAFETY: `MimiActorRepr` is shared between the caller thread (which holds the
// opaque pointer) and the worker thread (which owns the receiver).  The fields
// blob is only accessed by the worker thread (messages carry all needed data);
// the mailbox channel is itself `Send`.  The dispatch function pointer is a
// plain C function pointer stored in the codegen module's text segment.
// We manually ensure no `&mut` aliasing occurs: the worker has exclusive
// access to `fields` between messages, and `mailbox_tx` is a `Send` channel.
unsafe impl Send for MimiActorRepr {}
unsafe impl Sync for MimiActorRepr {}

/// Global atomic counter for unique actor IDs.
static ACTOR_ID_COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);
/// v0.29.24: process-wide max children (0 = unlimited).
static ACTOR_SPAWN_MAX: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
/// v0.29.24: number of actors successfully spawned (not yet dropped).
static ACTOR_SPAWN_COUNT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

// Thread-local: the ID of the actor whose worker thread we are currently
// executing on, or 0 if not on an actor worker thread.  Used for self-call
// deadlock avoidance — if a method call targets the same actor, we execute
// it synchronously instead of sending to the mailbox (which would deadlock
// since the worker is busy waiting for the response to its own message).
thread_local! {
    static CURRENT_ACTOR_ID: std::cell::Cell<u64> = const { std::cell::Cell::new(0) };
}

/// Type of the per-actor-type dispatch function generated by codegen.
/// Called on the actor's worker thread to execute a method.
// SAFETY: This is a C ABI function pointer; calling it is unsafe.
type ActorDispatchFn = unsafe extern "C" fn(
    method_id: i32,
    self_fields_ptr: *mut std::ffi::c_void,
    args_blob: *const std::ffi::c_void,
    args_size: i64,
    result_blob: *mut std::ffi::c_void,
    result_size_out: *mut i64,
);

/// Spawn a new actor instance.
///
/// # Parameters
/// - `fields_ptr`: pointer to the initialised actor field blob (memcpy'd).
/// - `fields_size`: size of the field blob in bytes.
/// - `dispatch_fn`: the `{Name}__dispatch` function generated by codegen.
///
/// # Returns
/// Opaque `*mut MimiActorRepr` handle, or null on failure.
#[no_mangle]
pub extern "C" fn mimi_actor_spawn(
    fields_ptr: *const std::ffi::c_void,
    fields_size: i64,
    dispatch_fn: Option<ActorDispatchFn>,
) -> *mut std::ffi::c_void {
    mimi_actor_spawn_with_mode(fields_ptr, fields_size, dispatch_fn, false)
}

/// Spawn an actor that is not owned by the current actor's lifecycle.
#[no_mangle]
pub extern "C" fn mimi_actor_spawn_detached(
    fields_ptr: *const std::ffi::c_void,
    fields_size: i64,
    dispatch_fn: Option<ActorDispatchFn>,
) -> *mut std::ffi::c_void {
    mimi_actor_spawn_with_mode(fields_ptr, fields_size, dispatch_fn, true)
}

fn mimi_actor_spawn_with_mode(
    fields_ptr: *const std::ffi::c_void,
    fields_size: i64,
    dispatch_fn: Option<ActorDispatchFn>,
    detached: bool,
) -> *mut std::ffi::c_void {
    if fields_ptr.is_null() || dispatch_fn.is_none() {
        return std::ptr::null_mut();
    }

    // v0.29.24: spawn quota (0 max = unlimited).
    let max = ACTOR_SPAWN_MAX.load(std::sync::atomic::Ordering::Acquire);
    if max > 0 {
        let count = ACTOR_SPAWN_COUNT.load(std::sync::atomic::Ordering::Acquire);
        if count >= max {
            return std::ptr::null_mut(); // QuotaExceeded
        }
    }

    let id = ACTOR_ID_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let parent_id = if detached {
        None
    } else {
        CURRENT_ACTOR_ID.with(|current| match current.get() {
            0 => None,
            id => Some(id),
        })
    };
    let fields_size = fields_size as usize;

    // SAFETY: `fields_ptr` is checked non-null; caller guarantees it points to
    // a valid field blob of `fields_size` bytes.
    let fields_blob: Box<[u8]> = unsafe {
        let slice = std::slice::from_raw_parts(fields_ptr as *const u8, fields_size);
        slice.to_vec().into_boxed_slice()
    };

    let (tx, rx) = std::sync::mpsc::channel::<ActorMailboxMsg>();

    // Clone the fields blob for the worker — the worker owns the live copy;
    // the handle's copy is not used after spawn (all access goes via mailbox).
    // Actually, we move the fields into the worker; the handle just holds the
    // channel + id. But we need the fields blob to be `Send`. Box<[u8]> is Send.
    let worker_fields: Box<[u8]> = fields_blob;

    let Some(dispatch) = dispatch_fn else {
        return std::ptr::null_mut();
    };
    let worker_id = id;
    let faulted = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    let worker_faulted = faulted.clone();
    let mailbox_depth = std::sync::Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let worker_depth = mailbox_depth.clone();
    let muted = std::sync::Arc::new(std::sync::atomic::AtomicBool::new(false));
    let worker_muted = muted.clone();
    let mailbox_depth_limit: usize = 2048;
    let worker_limit = mailbox_depth_limit;

    let thread_result = std::thread::Builder::new()
        .name(format!("mimi-actor-{}", id))
        .spawn(move || {
            // Set the thread-local so self-call detection works.
            CURRENT_ACTOR_ID.with(|c| c.set(worker_id));

            // The worker owns the mutable field storage.
            let mut fields = worker_fields;

            // Result blob is allocated once and reused.
            let mut result_blob = vec![0u8; MIMI_ACTOR_BLOB_SIZE];

            while let Ok(msg) = rx.recv() {
                // v0.29.21: depth accounting.
                let _ = worker_depth.fetch_update(
                    std::sync::atomic::Ordering::AcqRel,
                    std::sync::atomic::Ordering::Acquire,
                    |v| Some(v.saturating_sub(1)),
                );
                // Hysteresis unmute at ≤ 50% depth.
                let d = worker_depth.load(std::sync::atomic::Ordering::Acquire);
                if d <= worker_limit / 2 {
                    worker_muted.store(false, std::sync::atomic::Ordering::Release);
                }
                // v0.29.11: Fault absorption — drain without dispatch (O(1) short-circuit).
                if worker_faulted.load(std::sync::atomic::Ordering::Acquire) {
                    // Zero-size result signals short-circuit to the caller.
                    let _ = msg.response.send(ActorMsgResult {
                        data: Vec::new(),
                        size: 0,
                    });
                    continue;
                }
                // Execute the method via the dispatch function.
                // SAFETY: `dispatch` is a valid C function pointer generated by
                // codegen. `fields` is a valid mutable buffer. `msg.args` is a
                // valid byte slice. `result_blob` is a valid mutable buffer.
                let mut result_size: i64 = 0;
                unsafe {
                    dispatch(
                        msg.method_id,
                        fields.as_mut_ptr() as *mut std::ffi::c_void,
                        msg.args.as_ptr() as *const std::ffi::c_void,
                        msg.args.len() as i64,
                        result_blob.as_mut_ptr() as *mut std::ffi::c_void,
                        &mut result_size as *mut i64,
                    );
                }

                let rs = result_size.max(0) as usize;
                let data = if rs <= result_blob.len() {
                    result_blob[..rs].to_vec()
                } else {
                    Vec::new()
                };

                // Send result back; ignore error (caller may have timed out / dropped).
                let _ = msg.response.send(ActorMsgResult {
                    data,
                    size: result_size as u64,
                });
            }
        });
    let handle = match thread_result {
        Ok(h) => h,
        Err(_) => {
            // Thread spawn failed (resource limit) — return null actor handle.
            return std::ptr::null_mut();
        }
    };

    let repr = std::sync::Arc::new(MimiActorRepr {
        id,
        parent_id,
        detached,
        fields: Box::new([]), // handle doesn't own live fields; worker does
        mailbox_tx: std::sync::Mutex::new(Some(tx)),
        worker: std::sync::Mutex::new(Some(handle)),
        faulted,
        mailbox_depth_limit: std::sync::atomic::AtomicUsize::new(mailbox_depth_limit),
        mailbox_depth,
        muted,
        method_names: std::sync::Mutex::new(Vec::new()),
    });

    let raw = std::sync::Arc::as_ptr(&repr) as *mut std::ffi::c_void;
    // The topology lock makes parent validation and child insertion atomic
    // relative to SystemKill. A child cannot appear after its parent was cut.
    {
        let mut actors = live_actors().lock().unwrap_or_else(|e| e.into_inner());
        if let Some(parent_id) = parent_id {
            if !actors.values().any(|actor| actor.id == parent_id) {
                return std::ptr::null_mut();
            }
        }
        actors.insert(raw as usize, repr);
    }
    ACTOR_SPAWN_COUNT.fetch_add(1, std::sync::atomic::Ordering::AcqRel);
    raw
}

/// Pin a live actor while holding the registry lock.
///
/// The returned Arc must be acquired before any actor state is accessed. Drop
/// first detaches the handle from this registry, so no new pin can race with
/// destruction while existing operations keep the control block alive.
fn actor_pin_handle(handle: *mut std::ffi::c_void) -> Option<std::sync::Arc<MimiActorRepr>> {
    if handle.is_null() {
        None
    } else {
        actor_pin_live(handle as usize)
    }
}

#[cfg(test)]
static ACTOR_CALL_PAUSE_AFTER_PIN: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);
#[cfg(test)]
static ACTOR_CALL_PIN_REACHED: std::sync::atomic::AtomicBool =
    std::sync::atomic::AtomicBool::new(false);

#[cfg(test)]
pub(crate) fn actor_test_pause_after_pin(pause: bool) {
    ACTOR_CALL_PIN_REACHED.store(false, std::sync::atomic::Ordering::Release);
    ACTOR_CALL_PAUSE_AFTER_PIN.store(pause, std::sync::atomic::Ordering::Release);
}

#[cfg(test)]
pub(crate) fn actor_test_pin_reached() -> bool {
    ACTOR_CALL_PIN_REACHED.load(std::sync::atomic::Ordering::Acquire)
}

/// Get the actor ID from a handle. Used by codegen for self-call detection.
#[no_mangle]
pub extern "C" fn mimi_actor_id(handle: *mut std::ffi::c_void) -> u64 {
    actor_pin_handle(handle).map_or(0, |actor| actor.id)
}

/// Get the current actor ID (thread-local). Returns 0 if not on an actor worker.
/// Used by codegen to detect self-calls and execute them synchronously.
#[no_mangle]
pub extern "C" fn mimi_actor_current_id() -> u64 {
    CURRENT_ACTOR_ID.with(|c| c.get())
}

/// Call an actor method (blocking).
///
/// Sends a message to the actor's mailbox and blocks waiting for the response.
/// If called from within the same actor's worker thread (self-call), this would
/// deadlock — the caller must check `mimi_actor_current_id() == mimi_actor_id(handle)`
/// and execute the method directly instead.
///
/// # Parameters
/// - `handle`: opaque actor handle from `mimi_actor_spawn`.
/// - `method_id`: method index (determined by codegen at compile time).
/// - `args_ptr`: packed argument blob.
/// - `args_size`: size of args blob in bytes.
/// - `result_ptr`: output buffer for the packed result (caller-allocated, ≥8 bytes).
///
/// # Returns
/// Number of bytes written to `result_ptr`, or 0 on error.
#[no_mangle]
pub extern "C" fn mimi_actor_call(
    handle: *mut std::ffi::c_void,
    method_id: i32,
    args_ptr: *const std::ffi::c_void,
    args_size: i64,
    result_ptr: *mut std::ffi::c_void,
) -> i64 {
    let Some(repr) = actor_pin_handle(handle) else {
        return 0;
    };

    #[cfg(test)]
    if ACTOR_CALL_PAUSE_AFTER_PIN.load(std::sync::atomic::Ordering::Acquire) {
        ACTOR_CALL_PIN_REACHED.store(true, std::sync::atomic::Ordering::Release);
        while ACTOR_CALL_PAUSE_AFTER_PIN.load(std::sync::atomic::Ordering::Acquire) {
            std::thread::yield_now();
        }
    }

    // v0.29.11: O(1) mailbox short-circuit after Fault absorption.
    if repr.faulted.load(std::sync::atomic::Ordering::Acquire) {
        return 0;
    }

    // v0.29.21: mailbox backpressure — wait while muted/over HWM, TTL break.
    let ttl = std::time::Duration::from_millis(50);
    let start = std::time::Instant::now();
    loop {
        let depth = repr
            .mailbox_depth
            .load(std::sync::atomic::Ordering::Acquire);
        let muted = repr.muted.load(std::sync::atomic::Ordering::Acquire);
        let over = depth
            >= repr
                .mailbox_depth_limit
                .load(std::sync::atomic::Ordering::Acquire);
        if !muted && !over {
            break;
        }
        if start.elapsed() >= ttl {
            // SendErrorNotWriteable — force-wake producer (return 0).
            return 0;
        }
        std::thread::sleep(std::time::Duration::from_millis(1));
    }

    // Pack args.
    let args: Vec<u8> = if args_ptr.is_null() || args_size <= 0 {
        Vec::new()
    } else {
        // SAFETY: caller guarantees `args_ptr` points to `args_size` valid bytes.
        unsafe {
            let slice = std::slice::from_raw_parts(args_ptr as *const u8, args_size as usize);
            slice.to_vec()
        }
    };

    let (resp_tx, resp_rx) = std::sync::mpsc::channel::<ActorMsgResult>();

    let msg = ActorMailboxMsg {
        method_id,
        args,
        response: resp_tx,
    };

    // v0.29.21: reserve depth slot; mute if over HWM.
    let d = repr
        .mailbox_depth
        .fetch_add(1, std::sync::atomic::Ordering::AcqRel)
        + 1;
    if d > repr
        .mailbox_depth_limit
        .load(std::sync::atomic::Ordering::Acquire)
    {
        repr.muted.store(true, std::sync::atomic::Ordering::Release);
    }
    // Send to mailbox. If the channel is closed (actor dropped), return 0.
    let mailbox_tx = repr
        .mailbox_tx
        .lock()
        .unwrap_or_else(|e| e.into_inner())
        .clone();
    if match mailbox_tx {
        Some(tx) => tx.send(msg).is_err(),
        None => true,
    } {
        let _ = repr.mailbox_depth.fetch_update(
            std::sync::atomic::Ordering::AcqRel,
            std::sync::atomic::Ordering::Acquire,
            |v| Some(v.saturating_sub(1)),
        );
        return 0;
    }

    // Block waiting for the result.
    match resp_rx.recv() {
        Ok(result) => {
            let write_size = (result.size as usize).min(MIMI_ACTOR_BLOB_SIZE);
            if !result_ptr.is_null() && write_size > 0 && write_size <= result.data.len() {
                // SAFETY: `result_ptr` is caller-allocated with sufficient space;
                // `result.data` contains at least `write_size` bytes.
                unsafe {
                    std::ptr::copy_nonoverlapping(
                        result.data.as_ptr(),
                        result_ptr as *mut u8,
                        write_size,
                    );
                }
            }
            result.size as i64
        }
        Err(_) => 0,
    }
}

/// Drop an actor handle. Signals the worker thread to exit (by dropping the
/// mailbox sender) and joins it.
#[no_mangle]
pub extern "C" fn mimi_actor_drop(handle: *mut std::ffi::c_void) {
    // Detach under the registry lock. Existing operations own Arc pins; new
    // operations cannot obtain one, and final destruction is delayed safely.
    let Some(actor) = actor_take_live(handle as usize) else {
        return;
    };
    // v0.29.24: free a spawn slot.
    let _ = ACTOR_SPAWN_COUNT.fetch_update(
        std::sync::atomic::Ordering::AcqRel,
        std::sync::atomic::Ordering::Acquire,
        |v| Some(v.saturating_sub(1)),
    );
    drop(actor);
}

/// Terminate an actor and every transitively owned, non-detached child.
/// Topology is removed under one lock; actor shutdown happens after unlock.
#[no_mangle]
pub extern "C" fn mimi_actor_system_kill(handle: *mut std::ffi::c_void) {
    if handle.is_null() {
        return;
    }
    let victims = {
        let mut actors = live_actors().lock().unwrap_or_else(|e| e.into_inner());
        let Some(root) = actors.get(&(handle as usize)).cloned() else {
            return;
        };
        let mut ids = vec![root.id];
        let mut cursor = 0;
        while cursor < ids.len() {
            let parent = ids[cursor];
            for actor in actors.values() {
                if actor.parent_id == Some(parent) && !actor.detached && !ids.contains(&actor.id) {
                    ids.push(actor.id);
                }
            }
            cursor += 1;
        }
        let keys: Vec<usize> = actors
            .iter()
            .filter_map(|(key, actor)| ids.contains(&actor.id).then_some(*key))
            .collect();
        keys.into_iter()
            .filter_map(|key| actors.remove(&key))
            .collect::<Vec<_>>()
    };
    for actor in &victims {
        actor
            .faulted
            .store(true, std::sync::atomic::Ordering::Release);
        actor
            .mailbox_tx
            .lock()
            .unwrap_or_else(|e| e.into_inner())
            .take();
    }
    let removed = victims.len() as u64;
    let _ = ACTOR_SPAWN_COUNT.fetch_update(
        std::sync::atomic::Ordering::AcqRel,
        std::sync::atomic::Ordering::Acquire,
        |count| Some(count.saturating_sub(removed)),
    );
    drop(victims);
}

/// v0.29.11: Mark an actor as Faulted and short-circuit its mailbox (O(1)).
/// Subsequent `mimi_actor_call` returns 0 without enqueueing; the worker drains
/// any already-queued messages without dispatch.
#[no_mangle]
pub extern "C" fn mimi_actor_fault(handle: *mut std::ffi::c_void) {
    mimi_actor_system_kill(handle);
}

/// v0.29.11: Query whether an actor's mailbox is short-circuited.
/// Returns 1 if faulted, 0 otherwise (or if handle is null).
#[no_mangle]
pub extern "C" fn mimi_actor_is_faulted(handle: *mut std::ffi::c_void) -> i32 {
    let Some(repr) = actor_pin_handle(handle) else {
        return 0;
    };
    if repr.faulted.load(std::sync::atomic::Ordering::Acquire) {
        1
    } else {
        0
    }
}

/// v0.29.21: set mailbox high-water depth limit for backpressure.
#[no_mangle]
pub extern "C" fn mimi_actor_set_mailbox_depth(handle: *mut std::ffi::c_void, depth: i64) {
    if depth <= 0 {
        return;
    }
    let Some(repr) = actor_pin_handle(handle) else {
        return;
    };
    repr.mailbox_depth_limit
        .store(depth as usize, std::sync::atomic::Ordering::Release);
}

/// v0.29.21: current approximate mailbox depth.
#[no_mangle]
pub extern "C" fn mimi_actor_mailbox_depth(handle: *mut std::ffi::c_void) -> i64 {
    let Some(repr) = actor_pin_handle(handle) else {
        return 0;
    };
    repr.mailbox_depth
        .load(std::sync::atomic::Ordering::Acquire) as i64
}

/// v0.29.21: 1 if actor is muted under backpressure, else 0.
#[no_mangle]
pub extern "C" fn mimi_actor_is_muted(handle: *mut std::ffi::c_void) -> i32 {
    let Some(repr) = actor_pin_handle(handle) else {
        return 0;
    };
    if repr.muted.load(std::sync::atomic::Ordering::Acquire) {
        1
    } else {
        0
    }
}

/// v0.29.24: set process-wide max children (0 = unlimited).
#[no_mangle]
pub extern "C" fn mimi_actor_set_max_children(max: i64) {
    let v = if max <= 0 { 0 } else { max as u64 };
    ACTOR_SPAWN_MAX.store(v, std::sync::atomic::Ordering::Release);
}

/// v0.29.24: current live actor spawn count.
#[no_mangle]
pub extern "C" fn mimi_actor_spawn_count() -> i64 {
    ACTOR_SPAWN_COUNT.load(std::sync::atomic::Ordering::Acquire) as i64
}

/// v0.29.24: configured max children (0 = unlimited).
#[no_mangle]
pub extern "C" fn mimi_actor_max_children() -> i64 {
    ACTOR_SPAWN_MAX.load(std::sync::atomic::Ordering::Acquire) as i64
}

/// v0.29.25: register method names for an actor handle (for broadcast by name).
/// `names` is an array of `count` C strings (method name in definition order).
#[no_mangle]
pub extern "C" fn mimi_actor_set_method_names(
    handle: *mut std::ffi::c_void,
    names: *const *const std::os::raw::c_char,
    count: i64,
) {
    if names.is_null() || count <= 0 {
        return;
    }
    let Some(repr) = actor_pin_handle(handle) else {
        return;
    };
    let slice = unsafe { std::slice::from_raw_parts(names, count as usize) };
    let mut v = Vec::with_capacity(count as usize);
    for &p in slice {
        if p.is_null() {
            v.push(String::new());
        } else {
            let s = unsafe { std::ffi::CStr::from_ptr(p) }
                .to_string_lossy()
                .into_owned();
            v.push(s);
        }
    }
    if let Ok(mut g) = repr.method_names.lock() {
        *g = v;
    };
}

/// Resolve method name to method_id for a handle; returns -1 if not found.
#[no_mangle]
pub extern "C" fn mimi_actor_method_id(
    handle: *mut std::ffi::c_void,
    name: *const std::os::raw::c_char,
) -> i32 {
    if name.is_null() {
        return -1;
    }
    let Some(repr) = actor_pin_handle(handle) else {
        return -1;
    };
    let needle = unsafe { std::ffi::CStr::from_ptr(name) }.to_string_lossy();
    if let Ok(g) = repr.method_names.lock() {
        for (i, n) in g.iter().enumerate() {
            if n == needle.as_ref() {
                return i as i32;
            }
        }
    }
    -1
}

/// v0.29.25: broadcast method_name to an array of actor handles.
///
/// For each non-null handle, resolve method name → id and call mimi_actor_call
/// with empty args. Results: heap-allocated i64 array of length `count`.
/// v0.29.35: PeerFault slots use sentinel -1 (distinguishable from 0 result).
/// Caller owns the returned pointer.
#[no_mangle]
pub extern "C" fn mimi_broadcast(
    handles: *const *mut std::ffi::c_void,
    count: i64,
    method_name: *const std::os::raw::c_char,
    out_len: *mut i64,
) -> *mut i64 {
    if handles.is_null() || count <= 0 || method_name.is_null() {
        if !out_len.is_null() {
            unsafe { *out_len = 0 };
        }
        return std::ptr::null_mut();
    }
    let n = count as usize;
    let slice = unsafe { std::slice::from_raw_parts(handles, n) };
    let mut results: Vec<i64> = Vec::with_capacity(n);
    for &h in slice {
        if h.is_null() {
            // v0.29.35: PeerFault sentinel = -1
            results.push(-1);
            continue;
        }
        let mid = mimi_actor_method_id(h, method_name);
        if mid < 0 {
            // v0.29.35: unknown method → PeerFault sentinel
            results.push(-1);
            continue;
        }
        let mut result_buf = [0u8; MIMI_ACTOR_BLOB_SIZE];
        let sz = mimi_actor_call(
            h,
            mid,
            std::ptr::null(),
            0,
            result_buf.as_mut_ptr() as *mut std::ffi::c_void,
        );
        if sz >= 8 {
            // L4: slice is exactly 8 bytes by construction; avoid silent zero.
            let v = i64::from_le_bytes(result_buf[0..8].try_into().unwrap_or([0u8; 8]));
            results.push(v);
        } else {
            // v0.29.35: call failed → PeerFault sentinel
            results.push(-1);
        }
    }
    if !out_len.is_null() {
        unsafe { *out_len = results.len() as i64 };
    }
    let boxed = results.into_boxed_slice();
    Box::into_raw(boxed) as *mut i64
}

/// Free a buffer returned by mimi_broadcast.
#[no_mangle]
pub extern "C" fn mimi_broadcast_free(ptr: *mut i64, len: i64) {
    if ptr.is_null() || len <= 0 {
        return;
    }
    unsafe {
        let _ = Box::from_raw(std::ptr::slice_from_raw_parts_mut(ptr, len as usize));
    }
}
