use crate::core::{
    CheckedConversionKind, CheckedProgram, NodeId, Origin, PrimitiveType, ResolvedBlock,
    ResolvedCallable, ResolvedCallee, ResolvedExpr, ResolvedExprKind, ResolvedPattern,
    ResolvedPatternKind, ResolvedPlace, ResolvedStmtKind, ResolvedType, ResolvedTypeId,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct UnsupportedResolvedNode {
    pub owner: NodeId,
    pub node: NodeId,
    pub reason: String,
}

impl UnsupportedResolvedNode {
    fn new(owner: &NodeId, node: &NodeId, reason: impl Into<String>) -> Self {
        Self {
            owner: owner.clone(),
            node: node.clone(),
            reason: reason.into(),
        }
    }
}

pub(super) fn require_resolved_native_program(
    program: &CheckedProgram,
) -> Result<(), UnsupportedResolvedNode> {
    let user_flow_count = program
        .flows()
        .values()
        .filter(|flow| matches!(flow.origin, crate::core::Origin::User(_)))
        .count();
    if user_flow_count != 0
        || !program.actors().is_empty()
        || !program.sessions().is_empty()
        || !program.protocols().is_empty()
        || !program.capabilities().is_empty()
        || !program.traits().is_empty()
        || !program.impls().is_empty()
        || !program.extern_blocks().is_empty()
    {
        let owner = program
            .functions()
            .values()
            .next()
            .map(|function| function.node_id.clone())
            .unwrap_or_else(|| NodeId("resolved-native:program".into()));
        return Err(UnsupportedResolvedNode::new(
            &owner,
            &owner,
            format!(
                "declaration kinds beyond plain functions are not in the resolved native slice \
                 (flows={}, actors={}, sessions={}, protocols={}, caps={}, constants={}, traits={}, \
                 impls={}, types={}, externs={})",
                user_flow_count,
                program.actors().len(),
                program.sessions().len(),
                program.protocols().len(),
                program.capabilities().len(),
                program.constants().len(),
                program.traits().len(),
                program.impls().len(),
                program.type_defs().len(),
                program.extern_blocks().len(),
            ),
        ));
    }
    // Constants are allowed, but only materializable (non-Complex) values.
    for constant in program.constants().values() {
        if matches!(constant.value, crate::core::ResolvedConstValue::Complex) {
            return Err(UnsupportedResolvedNode::new(
                &constant.node_id,
                &constant.node_id,
                "constant with non-materializable value is not in the resolved native slice",
            ));
        }
    }
    for function in program.functions().values() {
        if function.is_comptime {
            continue;
        }
        // P1-1 fix: non-User-origin functions (imported from stdlib or
        // generated by the runtime system) must reject the all-or-nothing
        // path. Their bodies may reference runtime symbols the resolved
        // emitter doesn't track, causing SIGSEGV. The per-function dispatch
        // path (eligible_function_ids) handles these correctly by excluding
        // them and falling back to the legacy emitter.
        if !matches!(function.origin, crate::core::Origin::User(_)) {
            return Err(UnsupportedResolvedNode::new(
                &function.node_id,
                &function.node_id,
                "non-user-origin function requires per-function dispatch (not all-or-nothing)",
            ));
        }
        if function.is_async || function.extern_abi.is_some() || !function.generics.is_empty() {
            return Err(UnsupportedResolvedNode::new(
                &function.node_id,
                &function.node_id,
                "async, export, and generic functions are not in the resolved native slice",
            ));
        }
        if function.qualified_name.contains("::") {
            return Err(UnsupportedResolvedNode::new(
                &function.node_id,
                &function.node_id,
                "qualified function symbols are not in the resolved native slice",
            ));
        }
        let callable = program.callable(&function.node_id).ok_or_else(|| {
            UnsupportedResolvedNode::new(
                &function.node_id,
                &function.node_id,
                "missing ResolvedCallable",
            )
        })?;
        require_resolved_native_callable(program, callable)?;
    }
    Ok(())
}

/// Per-function eligibility: returns the set of function NodeIds that can be
/// compiled through the resolved native emitter. Functions that fail the
/// per-function check are simply excluded (not an error).
///
/// Program-level blockers (flows, actors, sessions) still cause a full
/// rejection because they require special compilation infrastructure.
pub(super) fn eligible_function_ids(
    program: &CheckedProgram,
) -> Result<std::collections::BTreeSet<NodeId>, UnsupportedResolvedNode> {
    // 0.32.24: Actors/sessions/protocols/capabilities/externs unblocked at
    // program level. These programs contain regular helper functions (main,
    // utility functions) that don't involve actor/session/protocol compilation.
    // The per-function eligibility checks filter out:
    // - Actor methods (non-User origin, qualified names with "::")
    // - Session/protocol functions (non-User origin)
    // - Functions with actor/session/protocol types in signatures
    //   (require_scalar_type rejects non-scalar Nominal types)
    // The legacy emitter still compiles actor/session/protocol infrastructure
    // (forward declarations, type definitions, method bodies) via compile_actor(),
    // compile_session(), etc. The resolved emitter only compiles the regular
    // functions that pass per-function eligibility.
    //
    // History:
    // - 0.32.8: impls/externs removal caused 2 SIGSEGV (std_strings,
    //   multiple_std_modules) — resolved emitter compiled stdlib function
    //   BODIES. Fixed by per-function source_id filtering (0.32.13).
    // - 0.32.13: impls unblocked (checker auto-generates From/Into impls
    //   for every program). Per-function guards sufficient.
    // - 0.32.20: Flows unblocked. Per-function checks filter transition
    //   functions. Legacy emitter compiles Flow infrastructure.
    // - 0.32.24: Actors/sessions/protocols/caps/externs unblocked.
    //   Same pattern: per-function checks + legacy infrastructure.
    // ⛔ 2026-07-28: traits unblocked. Prelude always loads From/Into traits,
    // so this per-program check was catching EVERY program. The per-function
    // eligibility checks handle function-level filtering. The resolved type
    // lowering now matches legacy ABI for Result/Option. Tuple destructure in
    // the resolved emitter uses alloca+GEP+load instead of extract_value to
    // avoid struct field misordering on cross-function call results.
    // ✅ 0.32.13: impls unblocked. The checker auto-generates From/Into impls
    // for primitive types, making program.impls() non-empty for EVERY program
    // (even without `use std::xxx`). This was silently disabling per-function
    // dispatch for all real programs. The per-function guards (Origin::User,
    // qualified_name "::", non-User-origin callee rejection) are sufficient
    // to prevent stdlib functions from being compiled through resolved.
    // The 0.32.8 SIGSEGV was caused by stdlib module functions being
    // User-origin — the callee origin check (added in 0.32.8) now prevents
    // calls TO those functions from being eligible, which means the calling
    // function is rejected at the per-function level (not program level).
    // Constants must be materializable.
    for constant in program.constants().values() {
        if matches!(constant.value, crate::core::ResolvedConstValue::Complex) {
            return Err(UnsupportedResolvedNode::new(
                &constant.node_id,
                &constant.node_id,
                "constant with non-materializable value",
            ));
        }
    }
    // Per-function eligibility check.
    // 0.32.13: Determine the entry file's source_id so we can exclude
    // functions imported from module files (which are User-origin but
    // defined in a different source file).
    let entry_source = program.entry_span().map(|s| s.source_id);
    let verbose = std::env::var("MIMI_VERBOSE").is_ok();
    let mut eligible = std::collections::BTreeSet::new();
    for function in program.functions().values() {
        let name = &function.qualified_name;
        if function.is_comptime || function.is_async || function.extern_abi.is_some() {
            if verbose {
                eprintln!("info: resolved skip '{}': comptime/async/extern", name);
            }
            continue;
        }
        if !function.generics.is_empty() || function.qualified_name.contains("::") {
            if verbose {
                eprintln!("info: resolved skip '{}': generics/qualified", name);
            }
            continue;
        }
        // S13: exclude non-User-origin functions (imported from stdlib or
        // generated by the runtime system). Their bodies may reference runtime
        // symbols the resolved emitter doesn't track, causing SIGSEGV.
        if !matches!(function.origin, crate::core::Origin::User(_)) {
            if verbose {
                eprintln!("info: resolved skip '{}': non-user origin", name);
            }
            continue;
        }
        // 0.32.13: exclude functions from module files. Module functions
        // are User-origin (parsed from .mimi) but defined in a different
        // source file than the entry point. Their bodies reference runtime
        // symbols and cross-emitter patterns that cause SIGSEGV when
        // compiled through the resolved emitter.
        if let (Some(entry_src), Origin::User(span)) = (entry_source, &function.origin) {
            if span.source_id != entry_src {
                if verbose {
                    eprintln!(
                        "info: resolved skip '{}': module file (source_id mismatch)",
                        name
                    );
                }
                continue;
            }
        }
        let Some(callable) = program.callable(&function.node_id) else {
            if verbose {
                eprintln!("info: resolved skip '{}': no ResolvedCallable", name);
            }
            continue;
        };
        match require_resolved_native_callable_with_source(program, callable, entry_source) {
            Ok(()) => {
                eligible.insert(function.node_id.clone());
            }
            Err(reason) => {
                if verbose {
                    eprintln!("info: resolved skip '{}': {}", name, reason.reason);
                }
            }
        }
    }
    Ok(eligible)
}

pub(super) fn require_resolved_native_callable(
    program: &CheckedProgram,
    callable: &ResolvedCallable,
) -> Result<(), UnsupportedResolvedNode> {
    require_resolved_native_callable_with_source(program, callable, None)
}

fn require_resolved_native_callable_with_source(
    program: &CheckedProgram,
    callable: &ResolvedCallable,
    entry_source: Option<crate::span::SourceId>,
) -> Result<(), UnsupportedResolvedNode> {
    if !callable.contracts.is_empty() {
        return Err(UnsupportedResolvedNode::new(
            &callable.owner,
            &callable.owner,
            "contracts are not in the resolved native slice",
        ));
    }
    require_scalar_type(program, &callable.owner, &callable.signature.result)?;
    for parameter in &callable.signature.parameters {
        // 0.32.20: Reject view/mutate borrow parameters. These are passed
        // as pointers in the LLVM ABI, but the resolved emitter treats
        // parameters as values, causing ABI mismatches (SIGSEGV).
        // Exception: method receivers named "self" use value ABI even
        // with Mutate permission — the legacy forward declaration matches
        // the resolved emitter's lower_type output.
        if parameter.name != "self"
            && matches!(
                parameter.permission,
                Some(crate::core::ir::Permission::View) | Some(crate::core::ir::Permission::Mutate)
            )
        {
            return Err(UnsupportedResolvedNode::new(
                &callable.owner,
                &callable.owner,
                format!(
                    "parameter '{}' has view/mutate borrow (not in resolved native slice)",
                    parameter.name
                ),
            ));
        }
        require_scalar_type(program, &callable.owner, &parameter.ty)?;
    }
    require_block(program, &callable.owner, &callable.body.root, entry_source)
}

fn require_scalar_type(
    program: &CheckedProgram,
    owner: &NodeId,
    ty: &ResolvedTypeId,
) -> Result<(), UnsupportedResolvedNode> {
    match program.resolved_types().get(ty) {
        Some(ResolvedType::Primitive(_)) => Ok(()),
        Some(ResolvedType::Tuple(elements)) => {
            for element in elements {
                require_scalar_type(program, owner, element)?;
            }
            Ok(())
        }
        // 0.32.1: Option/Result are already lowerable in types.rs
        // ({i1, T} and {i1, T, E} structs). Accept them in the eligibility
        // gate so the resolved emitter can handle Option/Result-typed
        // parameters, return values, and local bindings.
        Some(ResolvedType::Option(payload)) => require_scalar_type(program, owner, payload),
        Some(ResolvedType::Result { ok, error }) => {
            require_scalar_type(program, owner, ok)?;
            require_scalar_type(program, owner, error)
        }
        // 0.32.14: Newtype is a transparent wrapper — same LLVM repr as inner.
        Some(ResolvedType::Newtype { inner, .. }) => require_scalar_type(program, owner, inner),
        // 0.32.16: Function types (closures) — LLVM repr is {ptr, ptr}.
        Some(ResolvedType::Function {
            parameters, result, ..
        }) => {
            for param in parameters {
                require_scalar_type(program, owner, param)?;
            }
            require_scalar_type(program, owner, result)
        }
        // 0.32.2: Builtin collection types (List/Map/Set) are lowerable
        // in types.rs. Accept them so the resolved emitter can handle
        // collection-typed parameters, return values, and local bindings.
        // 0.32.5: User-defined record types are also accepted.
        Some(ResolvedType::Nominal {
            item, arguments, ..
        }) => {
            match item.as_str() {
                "builtin:type:List" | "builtin:type:Map" | "builtin:type:Set" => {
                    for arg in arguments {
                        require_scalar_type(program, owner, arg)?;
                    }
                    Ok(())
                }
                _ => {
                    // User-defined nominal: accept Record and Enum kinds.
                    // Look up the type definition by matching the
                    // NominalTypeId string against type_defs entries.
                    let item_str = item.as_str();
                    // 0.32.20: Flow state types (state:FlowName::StateName)
                    // are record-like types registered by the legacy emitter
                    // as flow::FlowName::StateName. Accept them — lower_type
                    // handles the actual LLVM type lookup.
                    // v0.34.8: delegated to NominalTypeId single source of truth.
                    if item.nominal_is_flow_state() {
                        for arg in arguments {
                            require_scalar_type(program, owner, arg)?;
                        }
                        return Ok(());
                    }
                    let is_record_or_enum = program.type_defs().values().any(|td| {
                        // NominalTypeId is "type:Name"; qualified_name is "Name".
                        let matches_name = item_str
                            .strip_prefix("type:")
                            .is_some_and(|n| td.qualified_name == n)
                            || td.qualified_name == item_str;
                        matches_name
                            && matches!(
                                td.kind,
                                crate::core::resolved::ResolvedTypeKind::Record
                                    // 0.32.12: Enum types accepted. LLVM
                                    // representation is {i32 tag, i64 payload}.
                                    | crate::core::resolved::ResolvedTypeKind::Enum
                            )
                    });
                    if is_record_or_enum {
                        for arg in arguments {
                            require_scalar_type(program, owner, arg)?;
                        }
                        Ok(())
                    } else {
                        Err(UnsupportedResolvedNode::new(
                            owner,
                            owner,
                            format!(
                                "nominal type '{item_str}' is not a record or enum in the resolved native slice"
                            ),
                        ))
                    }
                }
            }
        }
        Some(other) => Err(UnsupportedResolvedNode::new(
            owner,
            owner,
            format!("type {other:?} is not in the resolved native slice"),
        )),
        None => Err(UnsupportedResolvedNode::new(
            owner,
            owner,
            format!("missing canonical type '{}'", ty.as_str()),
        )),
    }
}

fn require_block(
    program: &CheckedProgram,
    owner: &NodeId,
    block: &ResolvedBlock,
    entry_source: Option<crate::span::SourceId>,
) -> Result<(), UnsupportedResolvedNode> {
    for statement in &block.statements {
        if !statement.backend_requirements.is_empty() {
            return Err(UnsupportedResolvedNode::new(
                owner,
                &statement.node_id,
                "unmet body backend requirement",
            ));
        }
        match &statement.kind {
            ResolvedStmtKind::Bind {
                pattern,
                initializer: Some(initializer),
            } => {
                require_binding_pattern(owner, pattern)?;
                require_expr(program, owner, initializer, entry_source)?;
            }
            ResolvedStmtKind::Assign {
                target,
                value,
                conversion,
            } => {
                require_root_place(owner, &statement.node_id, target)?;
                require_conversion(owner, &statement.node_id, conversion.kind)?;
                require_expr(program, owner, value, entry_source)?;
            }
            ResolvedStmtKind::Return { value, conversion } => {
                if let Some(value) = value {
                    require_expr(program, owner, value, entry_source)?;
                }
                if let Some(conversion) = conversion {
                    require_conversion(owner, &statement.node_id, conversion.kind)?;
                }
            }
            ResolvedStmtKind::Expr(expression) => {
                require_expr(program, owner, expression, entry_source)?
            }
            ResolvedStmtKind::Bind {
                pattern,
                initializer: None,
            } => {
                require_binding_pattern(owner, pattern)?;
            }
            ResolvedStmtKind::While { condition, body } => {
                require_condition(program, owner, condition, entry_source)?;
                require_block(program, owner, body, entry_source)?;
            }
            ResolvedStmtKind::For {
                pattern,
                iterable,
                body,
            } => {
                require_binding_pattern(owner, pattern)?;
                match &iterable.kind {
                    ResolvedExprKind::Range { start, end } => {
                        require_integer_expr(program, owner, start, entry_source)?;
                        require_integer_expr(program, owner, end, entry_source)?;
                    }
                    // 0.32.14: `range(start, end)` builtin call — same
                    // semantics as Range { start, end }.
                    ResolvedExprKind::Call(call)
                        if matches!(call.callee, ResolvedCallee::Builtin(ref id) if id.as_str() == "range")
                            && call.arguments.len() == 2 =>
                    {
                        require_integer_expr(
                            program,
                            owner,
                            &call.arguments[0].value,
                            entry_source,
                        )?;
                        require_integer_expr(
                            program,
                            owner,
                            &call.arguments[1].value,
                            entry_source,
                        )?;
                    }
                    // 0.32.8–0.32.9: List iteration — `for x in expr` where
                    // expr: List<T>. Accept any expression (Load, Call,
                    // Project, etc.) whose canonical type is List<T> with
                    // scalar element type.
                    _ => {
                        require_expr(program, owner, iterable, entry_source)?;
                        require_list_iterable_type(program, owner, &iterable.ty)?;
                    }
                }
                require_block(program, owner, body, entry_source)?;
            }
            ResolvedStmtKind::Break(value) => {
                if value.is_some() {
                    return Err(UnsupportedResolvedNode::new(
                        owner,
                        &statement.node_id,
                        "break with a value is not in the resolved native slice",
                    ));
                }
            }
            ResolvedStmtKind::Continue => {}
            ResolvedStmtKind::Scope { kind, body } => {
                // Only plain lexical scopes are in the resolved native slice.
                if !matches!(kind, crate::core::ir::ResolvedScopeKind::Lexical) {
                    return Err(UnsupportedResolvedNode::new(
                        owner,
                        &statement.node_id,
                        format!("scope kind {kind:?} is not in the resolved native slice"),
                    ));
                }
                require_block(program, owner, body, entry_source)?;
            }
            ResolvedStmtKind::Loop(body) => {
                require_block(program, owner, body, entry_source)?;
            }
            // Specification-level statements: no codegen output, accept unconditionally.
            ResolvedStmtKind::Drop(_) => {}
            ResolvedStmtKind::Contract { condition, .. } => {
                require_expr(program, owner, condition, entry_source)?;
            }
            ResolvedStmtKind::Math(conditions) => {
                for condition in conditions {
                    require_expr(program, owner, condition, entry_source)?;
                }
            }
            // NestedCallable: declaration marker for nested functions. The nested
            // function is compiled separately (by the resolved emitter or legacy
            // emitter). This statement is a no-op in both backends.
            ResolvedStmtKind::NestedCallable(_) => {}
            other => {
                return Err(UnsupportedResolvedNode::new(
                    owner,
                    &statement.node_id,
                    format!("statement {other:?} is not in the resolved native slice"),
                ))
            }
        }
    }
    if let Some(result) = &block.result {
        require_expr(program, owner, result, entry_source)?;
    }
    Ok(())
}

fn require_binding_pattern(
    owner: &NodeId,
    pattern: &ResolvedPattern,
) -> Result<(), UnsupportedResolvedNode> {
    match &pattern.kind {
        ResolvedPatternKind::Binding {
            by_reference: None, ..
        }
        | ResolvedPatternKind::Wildcard => Ok(()),
        ResolvedPatternKind::Tuple(sub_patterns) => {
            for sub in sub_patterns {
                require_binding_pattern(owner, sub)?;
            }
            Ok(())
        }
        _ => Err(UnsupportedResolvedNode::new(
            owner,
            &pattern.node_id,
            "only value bindings, wildcards, and tuples are in the resolved native slice",
        )),
    }
}

fn require_root_place(
    owner: &NodeId,
    node: &NodeId,
    place: &ResolvedPlace,
) -> Result<(), UnsupportedResolvedNode> {
    for projection in &place.projections {
        match projection {
            crate::core::ir::ResolvedProjection::Tuple { .. } => {}
            // 0.32.2: Index projections for List/Map element access.
            crate::core::ir::ResolvedProjection::Index { .. } => {}
            // 0.32.5: Field projections for record field access.
            crate::core::ir::ResolvedProjection::Field { .. } => {}
            other => {
                return Err(UnsupportedResolvedNode::new(
                    owner,
                    node,
                    format!("projection {other:?} is not in the resolved native slice"),
                ))
            }
        }
    }
    Ok(())
}

fn require_conversion(
    owner: &NodeId,
    node: &NodeId,
    conversion: CheckedConversionKind,
) -> Result<(), UnsupportedResolvedNode> {
    if matches!(
        conversion,
        CheckedConversionKind::Identity
            | CheckedConversionKind::NumericWiden
            | CheckedConversionKind::NumericNarrowChecked
            // 0.32.11: Alias/Newtype conversions are identity at the LLVM
            // level (same representation, different type name). Accept them
            // so programs using type aliases and newtypes are eligible.
            | CheckedConversionKind::AliasWrap
            | CheckedConversionKind::AliasUnwrap
            | CheckedConversionKind::NewtypeWrap
            | CheckedConversionKind::NewtypeUnwrap
    ) {
        Ok(())
    } else {
        Err(UnsupportedResolvedNode::new(
            owner,
            node,
            format!("conversion {conversion:?} is not in the resolved native slice"),
        ))
    }
}

fn require_expr(
    program: &CheckedProgram,
    owner: &NodeId,
    expression: &ResolvedExpr,
    entry_source: Option<crate::span::SourceId>,
) -> Result<(), UnsupportedResolvedNode> {
    if !expression.backend_requirements.is_empty() {
        return Err(UnsupportedResolvedNode::new(
            owner,
            &expression.node_id,
            "unmet expression backend requirement",
        ));
    }
    require_scalar_type(program, &expression.node_id, &expression.ty)?;
    match &expression.kind {
        ResolvedExprKind::Literal(_) => Ok(()),
        ResolvedExprKind::Constant(_) => Ok(()),
        ResolvedExprKind::Load(place) => require_root_place(owner, &expression.node_id, place),
        ResolvedExprKind::Tuple(elements) => {
            for element in elements {
                require_expr(program, owner, element, entry_source)?;
            }
            Ok(())
        }
        // 0.32.2: List literals.
        ResolvedExprKind::List(elements) => {
            for element in elements {
                require_expr(program, owner, element, entry_source)?;
            }
            Ok(())
        }
        // 0.32.3: Map/Set literals.
        ResolvedExprKind::Map(entries) => {
            for (key, value) in entries {
                require_expr(program, owner, key, entry_source)?;
                require_expr(program, owner, value, entry_source)?;
            }
            Ok(())
        }
        ResolvedExprKind::Set(elements) => {
            for element in elements {
                require_expr(program, owner, element, entry_source)?;
            }
            Ok(())
        }
        // 0.32.5: Record construction.
        ResolvedExprKind::Record { fields, .. } => {
            for field in fields {
                require_expr(program, owner, &field.value, entry_source)?;
            }
            Ok(())
        }
        ResolvedExprKind::Project { value, projection } => {
            match projection {
                crate::core::ir::ResolvedValueProjection::Tuple(_) => {}
                // 0.32.2: Index value projections for List element access
                // on rvalues (e.g. get_list()[0]).
                crate::core::ir::ResolvedValueProjection::Index(index_expr) => {
                    require_expr(program, owner, index_expr, entry_source)?;
                }
                // 0.32.5: Field value projections for record rvalue access.
                crate::core::ir::ResolvedValueProjection::Field(_) => {}
                other => {
                    return Err(UnsupportedResolvedNode::new(
                        owner,
                        &expression.node_id,
                        format!("value projection {other:?} is not in the resolved native slice"),
                    ))
                }
            }
            require_expr(program, owner, value, entry_source)
        }
        ResolvedExprKind::Binary { left, right, .. } => {
            require_expr(program, owner, left, entry_source)?;
            require_expr(program, owner, right, entry_source)
        }
        ResolvedExprKind::Unary { op, operand }
            if matches!(
                op,
                crate::core::ir::ResolvedUnaryOp::Negate | crate::core::ir::ResolvedUnaryOp::Not
            ) =>
        {
            require_expr(program, owner, operand, entry_source)
        }
        ResolvedExprKind::Cast { value, conversion } => {
            require_conversion(owner, &expression.node_id, conversion.kind)?;
            require_expr(program, owner, value, entry_source)
        }
        // 0.32.16: LocalClosure calls — indirect call through closure struct.
        ResolvedExprKind::Call(call) if matches!(call.callee, ResolvedCallee::LocalClosure(_)) => {
            for argument in &call.arguments {
                require_conversion(owner, &argument.value.node_id, argument.conversion.kind)?;
                require_expr(program, owner, &argument.value, entry_source)?;
            }
            Ok(())
        }
        ResolvedExprKind::Call(call)
            if matches!(
                call.callee,
                ResolvedCallee::Function(_)
                    | ResolvedCallee::Builtin(_)
                    | ResolvedCallee::Transition(_)
                    | ResolvedCallee::ProtocolMethod { .. }
                    | ResolvedCallee::Extern(_)
            ) =>
        {
            // Reject calls to non-User-origin functions (imported from
            // stdlib or generated by the runtime system). Their LLVM
            // symbols may not be declared when the resolved emitter
            // compiles the caller, causing SIGSEGV. Also reject calls
            // to qualified functions (contains "::").
            if let ResolvedCallee::Function(ref callee_owner) = call.callee {
                if let Some(callee_fn) = program.functions().get(callee_owner) {
                    if callee_fn.qualified_name.contains("::") {
                        return Err(UnsupportedResolvedNode::new(
                            owner,
                            &expression.node_id,
                            format!(
                                "call to qualified function '{}' is not in the resolved native slice",
                                callee_fn.qualified_name
                            ),
                        ));
                    }
                    if !matches!(callee_fn.origin, crate::core::Origin::User(_)) {
                        return Err(UnsupportedResolvedNode::new(
                            owner,
                            &expression.node_id,
                            format!(
                                "call to non-user-origin function '{}' is not in the resolved native slice",
                                callee_fn.qualified_name
                            ),
                        ));
                    }
                    // 0.32.18: calls to module functions (different source_id)
                    // are now ALLOWED. The 0.32.13 restriction was overly
                    // conservative — the 0.32.8 SIGSEGV was caused by the
                    // resolved emitter compiling stdlib function BODIES
                    // (which reference runtime symbols it doesn't track),
                    // not by calling them. Module functions are forward-
                    // declared by the legacy emitter (compile.rs step 1)
                    // before the resolved subset is compiled (step 4), so
                    // the LLVM symbol is always available. The resolved
                    // emitter emits a plain `call` to the declared symbol;
                    // the legacy emitter compiles the callee body in step 5.
                    // Per-function source_id filtering (lines 218-222) still
                    // prevents module function BODIES from being compiled
                    // through the resolved emitter.
                }
            }
            for argument in &call.arguments {
                require_conversion(owner, &argument.value.node_id, argument.conversion.kind)?;
                require_expr(program, owner, &argument.value, entry_source)?;
            }
            Ok(())
        }
        ResolvedExprKind::If {
            condition,
            then_block,
            else_block,
        } => {
            require_condition(program, owner, condition, entry_source)?;
            require_block(program, owner, then_block, entry_source)?;
            require_block(program, owner, else_block, entry_source)
        }
        ResolvedExprKind::Block(block) => require_block(program, owner, block, entry_source),
        ResolvedExprKind::FString(parts) => {
            for part in parts {
                if let crate::core::ir::ResolvedFStringPart::Interpolation(expr) = part {
                    require_expr(program, owner, expr, entry_source)?;
                }
            }
            Ok(())
        }
        ResolvedExprKind::Match { scrutinee, arms } => {
            require_expr(program, owner, scrutinee, entry_source)?;
            for arm in arms {
                require_match_pattern(owner, &arm.pattern)?;
                if let Some(guard) = &arm.guard {
                    require_condition(program, owner, guard, entry_source)?;
                }
                require_expr(program, owner, &arm.body, entry_source)?;
            }
            Ok(())
        }
        ResolvedExprKind::Scope { kind, body } => {
            if !matches!(kind, crate::core::ir::ResolvedScopeKind::Lexical) {
                return Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    format!("scope kind {kind:?} is not in the resolved native slice"),
                ));
            }
            require_block(program, owner, body, entry_source)
        }
        // 0.32.10: Try expression (`?` operator). The inner value must be
        // Result<T, E> or Option<T>. The Try expression itself has type T
        // (the Ok/Some payload), already checked by require_scalar_type at
        // the top of require_expr.
        ResolvedExprKind::Try { value, .. } => {
            require_expr(program, owner, value, entry_source)?;
            // The inner expression's type must be Result or Option.
            match program.resolved_types().get(&value.ty) {
                Some(ResolvedType::Result { .. } | ResolvedType::Option(_)) => Ok(()),
                Some(other) => Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    format!("try inner type {other:?} is not Result or Option"),
                )),
                None => Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    "try inner expression has a missing canonical type",
                )),
            }
        }
        // 0.32.16: Lambda expressions — only non-capturing closures.
        ResolvedExprKind::Lambda(lambda) => {
            if !lambda.captures.is_empty() {
                return Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    "capturing lambda is not in the resolved native slice",
                ));
            }
            require_block(program, owner, &lambda.body, entry_source)
        }
        // 0.32.31: Slice expressions (xs[start:end]). Target must be a List.
        // Start/end are optional (default 0/len). Indices must be integers.
        ResolvedExprKind::Slice { target, start, end } => {
            require_expr(program, owner, target, entry_source)?;
            if let Some(start_expr) = start {
                require_integer_expr(program, owner, start_expr, entry_source)?;
            }
            if let Some(end_expr) = end {
                require_integer_expr(program, owner, end_expr, entry_source)?;
            }
            Ok(())
        }
        // 0.32.32: Old expression (contract `old(x)`). In codegen this is
        // identity — the runtime value IS the "old" value since contracts
        // are erased. Only the verifier gives old() distinct semantics.
        ResolvedExprKind::Old(inner) => require_expr(program, owner, inner, entry_source),
        // 0.32.33: Comprehension ([value for pattern in iterable if guard]).
        // Pattern must be a simple binding. Guard (if present) must be bool.
        ResolvedExprKind::Comprehension {
            pattern,
            value,
            iterable,
            guard,
        } => {
            // Only simple binding patterns supported (same as for-in).
            if !matches!(
                &pattern.kind,
                ResolvedPatternKind::Binding {
                    by_reference: None,
                    ..
                }
            ) {
                return Err(UnsupportedResolvedNode::new(
                    owner,
                    &pattern.node_id,
                    "comprehension pattern must be a simple binding",
                ));
            }
            require_expr(program, owner, iterable, entry_source)?;
            if let Some(guard_expr) = guard {
                require_condition(program, owner, guard_expr, entry_source)?;
            }
            require_expr(program, owner, value, entry_source)
        }
        // 0.32.34: OptionalChain (receiver?.field). Receiver must be Option/Result.
        // The field is projected from the payload record. Result is Option<FieldType>.
        ResolvedExprKind::OptionalChain { receiver, .. } => {
            require_expr(program, owner, receiver, entry_source)?;
            // Receiver must be Option or Result.
            match program.resolved_types().get(&receiver.ty) {
                Some(ResolvedType::Option(_) | ResolvedType::Result { .. }) => Ok(()),
                Some(other) => Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    format!("optional chain receiver type {other:?} is not Option/Result"),
                )),
                None => Err(UnsupportedResolvedNode::new(
                    owner,
                    &expression.node_id,
                    "optional chain receiver has no resolved type",
                )),
            }
        }
        // 0.32.35: Callable (first-class function value). Only Function callees
        // that are User-origin and non-qualified. The emitter returns a function
        // pointer to the declared LLVM symbol.
        ResolvedExprKind::Callable(callee) => match callee {
            ResolvedCallee::Function(callee_owner) => {
                if let Some(callee_fn) = program.functions().get(callee_owner) {
                    if callee_fn.qualified_name.contains("::") {
                        return Err(UnsupportedResolvedNode::new(
                            owner,
                            &expression.node_id,
                            "callable reference to qualified function not in resolved slice",
                        ));
                    }
                    if !matches!(callee_fn.origin, crate::core::Origin::User(_)) {
                        return Err(UnsupportedResolvedNode::new(
                            owner,
                            &expression.node_id,
                            "callable reference to non-user-origin function not in resolved slice",
                        ));
                    }
                }
                Ok(())
            }
            _ => Err(UnsupportedResolvedNode::new(
                owner,
                &expression.node_id,
                "only Function callees are supported as first-class values in resolved slice",
            )),
        },
        other => Err(UnsupportedResolvedNode::new(
            owner,
            &expression.node_id,
            format!("expression {other:?} is not in the resolved native slice"),
        )),
    }
}

/// Match arm patterns: only literals, wildcards, and simple bindings.
fn require_match_pattern(
    owner: &NodeId,
    pattern: &ResolvedPattern,
) -> Result<(), UnsupportedResolvedNode> {
    match &pattern.kind {
        ResolvedPatternKind::Wildcard
        | ResolvedPatternKind::Literal(_)
        | ResolvedPatternKind::Binding {
            by_reference: None, ..
        } => Ok(()),
        // 0.32.6: Constructor patterns for Option/Result match arms.
        // Field sub-patterns must also be in the slice.
        ResolvedPatternKind::Constructor { fields, .. } => {
            for (_, sub_pattern) in fields {
                require_match_pattern(owner, sub_pattern)?;
            }
            Ok(())
        }
        _ => Err(UnsupportedResolvedNode::new(
            owner,
            &pattern.node_id,
            "only literal, wildcard, binding, and constructor match patterns are in the resolved native slice",
        )),
    }
}

/// Condition expressions must be canonical `bool`.
fn require_condition(
    program: &CheckedProgram,
    owner: &NodeId,
    condition: &ResolvedExpr,
    entry_source: Option<crate::span::SourceId>,
) -> Result<(), UnsupportedResolvedNode> {
    require_expr(program, owner, condition, entry_source)?;
    match program.resolved_types().get(&condition.ty) {
        Some(ResolvedType::Primitive(PrimitiveType::Bool)) => Ok(()),
        Some(other) => Err(UnsupportedResolvedNode::new(
            owner,
            &condition.node_id,
            format!("condition type {other:?} is not bool"),
        )),
        None => Err(UnsupportedResolvedNode::new(
            owner,
            &condition.node_id,
            "condition has a missing canonical type",
        )),
    }
}

/// Range bounds must be signed or unsigned integers (not float/bool).
fn require_integer_expr(
    program: &CheckedProgram,
    owner: &NodeId,
    expression: &ResolvedExpr,
    entry_source: Option<crate::span::SourceId>,
) -> Result<(), UnsupportedResolvedNode> {
    require_expr(program, owner, expression, entry_source)?;
    match program.resolved_types().get(&expression.ty) {
        Some(ResolvedType::Primitive(
            PrimitiveType::I8
            | PrimitiveType::I16
            | PrimitiveType::I32
            | PrimitiveType::I64
            | PrimitiveType::I128
            | PrimitiveType::Isize
            | PrimitiveType::U8
            | PrimitiveType::U16
            | PrimitiveType::U32
            | PrimitiveType::U64
            | PrimitiveType::U128
            | PrimitiveType::Usize,
        )) => Ok(()),
        Some(other) => Err(UnsupportedResolvedNode::new(
            owner,
            &expression.node_id,
            format!("range bound type {other:?} is not an integer"),
        )),
        None => Err(UnsupportedResolvedNode::new(
            owner,
            &expression.node_id,
            "range bound has a missing canonical type",
        )),
    }
}

/// For-in-list iterable type must be `List<T>` where T is a scalar type
/// acceptable by the resolved native slice.
fn require_list_iterable_type(
    program: &CheckedProgram,
    owner: &NodeId,
    ty: &crate::core::ResolvedTypeId,
) -> Result<(), UnsupportedResolvedNode> {
    match program.resolved_types().get(ty) {
        Some(ResolvedType::Nominal {
            item, arguments, ..
        }) if item.as_str() == "builtin:type:List" => {
            // List<T>: element type must be scalar.
            for arg in arguments {
                require_scalar_type(program, owner, arg)?;
            }
            Ok(())
        }
        Some(other) => Err(UnsupportedResolvedNode::new(
            owner,
            owner,
            format!("for-in iterable type {other:?} is not List<T>"),
        )),
        None => Err(UnsupportedResolvedNode::new(
            owner,
            owner,
            "for-in iterable has a missing canonical type",
        )),
    }
}
