//! C++ binding generator from Mimi extern declarations.
//!
//! Generates a `.hpp` header with C++ wrapper classes that use RAII
//! for resource management and provide a natural C++ API over the C FFI.
//!
//! Usage:
//!   mimi emit-cpp-bindings path/to/pkg.mimi -o bindings.hpp

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// C++ binding generator — produces a `.hpp` header with RAII wrappers.
pub struct CppBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl CppBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete C++ header with RAII wrappers.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();
        let guard = format!("MIMI_{}_HPP", self.module_name.to_uppercase());

        writeln!(out, "// Auto-generated by Mimi FFI binding generator (C++)")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out, "// Do not edit manually.")?;
        writeln!(out)?;
        writeln!(out, "#ifndef {}", guard)?;
        writeln!(out, "#define {}", guard)?;
        writeln!(out)?;
        writeln!(out, "#include <cstdint>")?;
        writeln!(out, "#include <cstring>")?;
        writeln!(out, "#include <string>")?;
        writeln!(out, "#include <stdexcept>")?;
        writeln!(out, "#include <functional>")?;
        writeln!(out, "#include \"mimi_ffi.h\"")?;
        writeln!(out)?;

        // Namespace
        writeln!(out, "namespace mimi {{")?;
        writeln!(out, "namespace {} {{", sanitize_cpp_ns(&self.module_name))?;
        writeln!(out)?;

        // RAII string wrapper
        writeln!(out, "/// RAII wrapper for Mimi heap-allocated C strings.")?;
        writeln!(out, "class MimiString {{")?;
        writeln!(out, "public:")?;
        writeln!(out, "    explicit MimiString(char* raw) : data_(raw) {{}}")?;
        writeln!(out, "    ~MimiString() {{ if (data_) mimi_string_free(data_); }}")?;
        writeln!(out, "    MimiString(const MimiString&) = delete;")?;
        writeln!(out, "    MimiString& operator=(const MimiString&) = delete;")?;
        writeln!(out, "    MimiString(MimiString&& o) noexcept : data_(o.data_) {{ o.data_ = nullptr; }}")?;
        writeln!(out, "    MimiString& operator=(MimiString&& o) noexcept {{")?;
        writeln!(out, "        if (this != &o) {{ if (data_) mimi_string_free(data_); data_ = o.data_; o.data_ = nullptr; }}")?;
        writeln!(out, "        return *this;")?;
        writeln!(out, "    }}")?;
        writeln!(out, "    const char* c_str() const {{ return data_ ? data_ : \"\"; }}")?;
        writeln!(out, "    std::string str() const {{ return std::string(c_str()); }}")?;
        writeln!(out, "    explicit operator bool() const {{ return data_ != nullptr; }}")?;
        writeln!(out, "private:")?;
        writeln!(out, "    char* data_;")?;
        writeln!(out, "}};")?;
        writeln!(out)?;

        // Callback support: thread-local std::function slots and C trampolines
        self.write_callback_support(&mut out, extern_funcs)?;

        // C++ wrapper functions
        writeln!(out, "// C++ wrapper functions with RAII and type safety")?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_cpp_wrapper(&mut out, func, &contract)?;
        }

        writeln!(out, "}} // namespace {}", sanitize_cpp_ns(&self.module_name))?;
        writeln!(out, "}} // namespace mimi")?;
        writeln!(out)?;
        writeln!(out, "#endif // {}", guard)?;

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_callback_support(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback { param_types, ret_type } = &contract.args[i] {
                    let slot = format!("{}_{}_cb", func.name, p.name);
                    let tramp = format!("mimi_cb_{}_{}_trampoline", func.name, p.name);
                    let cpp_sig = self.callback_cpp_type(param_types, ret_type);
                    let c_sig = self.callback_c_signature(&tramp, param_types, ret_type);
                    writeln!(out, "// Callback slot for {}::{}", func.name, p.name)?;
                    writeln!(out, "thread_local static {} {};", cpp_sig, slot)?;
                    writeln!(out, "{}", c_sig)?;
                    writeln!(out, "    if (!{}) {{", slot)?;
                    writeln!(out, "        return {};", self.callback_default_ret(ret_type))?;
                    writeln!(out, "    }}")?;
                    let c_args: Vec<String> = param_types.iter().enumerate()
                        .map(|(j, _)| format!("arg{}", j))
                        .collect();
                    writeln!(out, "    return {}({});", slot, c_args.join(", "))?;
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }
            }
        }
        Ok(())
    }

    fn write_cpp_wrapper(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let cpp_params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| format!("{} {}", self.mimi_type_to_cpp(contract, i), p.name))
            .collect();
        let ret_cpp = self.ret_type_to_cpp(contract);

        // Build call arguments with conversions
        let mut conversions = String::new();
        let mut c_args = Vec::new();
        for (i, p) in func.params.iter().enumerate() {
            match contract.args[i] {
                FfiArgContract::StringBorrow => {
                    writeln!(conversions, "        auto {}_cstr = {}.c_str();", p.name, p.name)?;
                    c_args.push(format!("{}_cstr", p.name));
                }
                FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(conversions, "        auto {}_cstr = {}.c_str();", p.name, p.name)?;
                    c_args.push(format!("{}_cstr", p.name));
                }
                FfiArgContract::Callback { .. } => {
                    let slot = format!("{}_{}_cb", func.name, p.name);
                    let tramp = format!("{}_{}_trampoline", func.name, p.name);
                    writeln!(conversions, "        {} = {};", slot, p.name)?;
                    c_args.push(tramp);
                }
                _ => {
                    c_args.push(format!("static_cast<{}>({})", self.mimi_type_to_c(contract, i), p.name));
                }
            }
        }

        writeln!(out, "inline {} {}({}) {{", ret_cpp, func.name, cpp_params.join(", "))?;
        write!(out, "{}", conversions)?;

        // Use :: prefix to call C functions (avoids recursion with same-named wrappers)
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => {
                writeln!(out, "        MimiString mimi_ret(::{}({}));", func.name, c_args.join(", "))?;
            }
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "        ::{}({});", func.name, c_args.join(", "))?;
            }
            _ => {
                writeln!(out, "        {} mimi_ret = ::{}({});", ret_cpp, func.name, c_args.join(", "))?;
            }
        }

        // Clear callback slots so closures/captures are released after the call.
        for (i, p) in func.params.iter().enumerate() {
            if let FfiArgContract::Callback { .. } = &contract.args[i] {
                let slot = format!("{}_{}_cb", func.name, p.name);
                writeln!(out, "        {} = {{}};", slot)?;
            }
        }

        if !matches!(&contract.ret, crate::ffi::contract::FfiRetContract::Unit) {
            writeln!(out, "        return mimi_ret;")?;
        }
        writeln!(out, "}}")?;
        writeln!(out)
    }

    fn mimi_type_to_c(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "void*".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "const char*".to_string(),
            FfiArgContract::Cap(_) => "int64_t".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "void*".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "int64_t".to_string(),
            FfiArgContract::Json => "const char*".to_string(),
            FfiArgContract::StructByValue(name) => format!("struct {}", name),
            FfiArgContract::Callback { param_types, ret_type } => {
                self.callback_c_type(param_types, ret_type)
            }
            FfiArgContract::Unsupported(_) => "void*".to_string(),
        }
    }


    fn mimi_type_to_cpp(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "void*".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow => "const std::string&".to_string(),
            FfiArgContract::StringTransfer | FfiArgContract::Json => "const std::string&".to_string(),
            FfiArgContract::Cap(_) => "int64_t".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "void*".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "int64_t".to_string(),
            FfiArgContract::StructByValue(name) => format!("const struct {}&", name),
            FfiArgContract::Callback { param_types, ret_type } => {
                self.callback_cpp_type(param_types, ret_type)
            }
            FfiArgContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn ret_type_to_cpp(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "MimiString".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "void*".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "std::string".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("struct {}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn callback_cpp_type(&self, param_types: &[Type], ret_type: &Type) -> String {
        let args: Vec<String> = param_types
            .iter()
            .map(|ty| self.mimi_type_to_c_type(ty))
            .collect();
        format!(
            "std::function<{}({})>",
            self.mimi_type_to_c_type(ret_type),
            args.join(", ")
        )
    }

    fn callback_c_type(&self, param_types: &[Type], ret_type: &Type) -> String {
        let args: Vec<String> = param_types
            .iter()
            .map(|ty| self.mimi_type_to_c_type(ty))
            .collect();
        format!(
            "{} (*)({})",
            self.mimi_type_to_c_type(ret_type),
            args.join(", ")
        )
    }

    fn callback_c_signature(&self, name: &str, param_types: &[Type], ret_type: &Type) -> String {
        let ret = self.mimi_type_to_c_type(ret_type);
        let args: Vec<String> = param_types
            .iter()
            .enumerate()
            .map(|(i, ty)| format!("{} arg{}", self.mimi_type_to_c_type(ty), i))
            .collect();
        let args_str = if args.is_empty() { "void".to_string() } else { args.join(", ") };
        format!("extern \"C\" {} {}({}) {{", ret, name, args_str)
    }

    fn callback_default_ret(&self, ret_type: &Type) -> String {
        match ret_type {
            Type::Name(name, _) if name == "f64" => "0.0".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "0".to_string(),
        }
    }

    fn mimi_type_to_c_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" | "i64" | "bool" => "int64_t".to_string(),
                "f64" => "double".to_string(),
                _ => "int64_t".to_string(),
            },
            _ => "int64_t".to_string(),
        }
    }
}

fn sanitize_cpp_ns(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
