//! C++ binding generator from Mimi extern declarations.
//!
//! Generates a `.hpp` header with C++ wrapper classes that use RAII
//! for resource management and provide a natural C++ API over the C FFI.
//!
//! Usage:
//!   mimi emit-cpp-bindings path/to/pkg.mimi -o bindings.hpp

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, TypeDef};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// C++ binding generator — produces a `.hpp` header with RAII wrappers.
pub struct CppBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl CppBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete C++ header with RAII wrappers.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();
        let guard = format!("MIMI_{}_HPP", self.module_name.to_uppercase());

        writeln!(out, "// Auto-generated by Mimi FFI binding generator (C++)")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out, "// Do not edit manually.")?;
        writeln!(out)?;
        writeln!(out, "#ifndef {}", guard)?;
        writeln!(out, "#define {}", guard)?;
        writeln!(out)?;
        writeln!(out, "#include <cstdint>")?;
        writeln!(out, "#include <cstring>")?;
        writeln!(out, "#include <string>")?;
        writeln!(out, "#include <stdexcept>")?;
        writeln!(out, "#include <functional>")?;
        writeln!(out)?;
        writeln!(out, "// Mimi runtime C declarations")?;
        writeln!(out, "extern \"C\" {{")?;
        writeln!(out, "    void mimi_string_free(char* s);")?;
        writeln!(out, "}}")?;
        writeln!(out)?;

        // Namespace
        writeln!(out, "namespace mimi {{")?;
        writeln!(out, "namespace {} {{", sanitize_cpp_ns(&self.module_name))?;
        writeln!(out)?;

        // RAII string wrapper
        writeln!(out, "/// RAII wrapper for Mimi heap-allocated C strings.")?;
        writeln!(out, "class MimiString {{")?;
        writeln!(out, "public:")?;
        writeln!(out, "    explicit MimiString(char* raw) : data_(raw) {{}}")?;
        writeln!(out, "    ~MimiString() {{ if (data_) mimi_string_free(data_); }}")?;
        writeln!(out, "    MimiString(const MimiString&) = delete;")?;
        writeln!(out, "    MimiString& operator=(const MimiString&) = delete;")?;
        writeln!(out, "    MimiString(MimiString&& o) noexcept : data_(o.data_) {{ o.data_ = nullptr; }}")?;
        writeln!(out, "    MimiString& operator=(MimiString&& o) noexcept {{")?;
        writeln!(out, "        if (this != &o) {{ if (data_) mimi_string_free(data_); data_ = o.data_; o.data_ = nullptr; }}")?;
        writeln!(out, "        return *this;")?;
        writeln!(out, "    }}")?;
        writeln!(out, "    const char* c_str() const {{ return data_ ? data_ : \"\"; }}")?;
        writeln!(out, "    std::string str() const {{ return std::string(c_str()); }}")?;
        writeln!(out, "    explicit operator bool() const {{ return data_ != nullptr; }}")?;
        writeln!(out, "private:")?;
        writeln!(out, "    char* data_;")?;
        writeln!(out, "}};")?;
        writeln!(out)?;

        // Extern C declarations
        writeln!(out, "extern \"C\" {{")?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_c_decl(&mut out, func, &contract)?;
        }
        writeln!(out, "}} // extern \"C\"")?;
        writeln!(out)?;

        // C++ wrapper functions
        writeln!(out, "// C++ wrapper functions with RAII and type safety")?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_cpp_wrapper(&mut out, func, &contract)?;
        }

        writeln!(out, "}} // namespace {}", sanitize_cpp_ns(&self.module_name))?;
        writeln!(out, "}} // namespace mimi")?;
        writeln!(out)?;
        writeln!(out, "#endif // {}", guard)?;

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&crate::ast::TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_c_decl(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| format!("{} {}", self.mimi_type_to_c(&contract, i), p.name))
            .collect();
        let ret = self.ret_type_to_c(&contract);
        writeln!(out, "    {} {}({});", ret, func.name, params.join(", "))
    }

    fn write_cpp_wrapper(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let cpp_params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| format!("{} {}", self.mimi_type_to_cpp(&contract, i), p.name))
            .collect();
        let ret_cpp = self.ret_type_to_cpp(&contract);

        // Build call arguments with conversions
        let mut conversions = String::new();
        let mut c_args = Vec::new();
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow => {
                    writeln!(conversions, "        auto {}_cstr = {}.c_str();", p.name, p.name)?;
                    c_args.push(format!("{}_cstr", p.name));
                }
                FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(conversions, "        auto {}_cstr = {}.c_str();", p.name, p.name)?;
                    c_args.push(format!("{}_cstr", p.name));
                }
                _ => {
                    c_args.push(format!("static_cast<{}>({})", self.mimi_type_to_c(&contract, i), p.name));
                }
            }
        }

        writeln!(out, "inline {} {}({}) {{", ret_cpp, func.name, cpp_params.join(", "))?;
        write!(out, "{}", conversions)?;

        // Use :: prefix to call C functions (avoids recursion with same-named wrappers)
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => {
                writeln!(out, "        return MimiString(::{}({}));", func.name, c_args.join(", "))?;
            }
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "        ::{}({});", func.name, c_args.join(", "))?;
            }
            _ => {
                writeln!(out, "        return ::{}({});", func.name, c_args.join(", "))?;
            }
        }
        writeln!(out, "}}")?;
        writeln!(out)
    }

    fn mimi_type_to_c(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() { return "void*".to_string(); }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "const char*".to_string(),
            FfiArgContract::Cap(_) => "int64_t".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "void*".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "int64_t".to_string(),
            FfiArgContract::Json => "const char*".to_string(),
            FfiArgContract::StructByValue(_) => "void*".to_string(),
            FfiArgContract::Callback { .. } => "void*".to_string(),
            FfiArgContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn ret_type_to_c(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "char*".to_string(),
            _ => "int64_t".to_string(),
        }
    }

    fn mimi_type_to_cpp(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() { return "void*".to_string(); }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow => "const std::string&".to_string(),
            FfiArgContract::StringTransfer | FfiArgContract::Json => "const std::string&".to_string(),
            FfiArgContract::Cap(_) => "int64_t".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "void*".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "int64_t".to_string(),
            FfiArgContract::StructByValue(_) => "void*".to_string(),
            FfiArgContract::Callback { .. } => "void*".to_string(),
            FfiArgContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn ret_type_to_cpp(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "MimiString".to_string(),
            _ => "int64_t".to_string(),
        }
    }
}

fn sanitize_cpp_ns(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}
