//! Go FFI binding generator (CGO) from Mimi extern declarations.
//!
//! Generates a `.go` file with `import "C"` and CGO directives.
//!
//! Go callback ABI user-data root (closed 0.36.106 by design): the current
//! per-slot mutex snapshot is the accepted 0.1.6 mitigation; replacing global
//! callback slots with an ABI that carries user-data through the C function
//! pointer is a Wave-3 root solution and not a 0.1.6 blocker.
//!
//! Usage:
//!   mimi emit-go-bindings path/to/pkg.mimi -o bindings.go
//!
//! Contract (see `src/ffi/contract.rs`):
//!   * `FfiRetContract::String`  — borrowed from C; the binding must NOT free,
//!     and NULL must be checked before `C.GoString`.
//!   * `FfiRetContract::StringOwned` / `Json` — owned; freed with
//!     `mimi_string_free` after copying into a Go string.
//!   * `FfiArgContract::StringTransfer` — ownership of the buffer moves to C;
//!     the binding must NOT free it post-call.

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Go binding generator — produces a CGO-compatible `.go` file.
pub struct GoBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl GoBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete Go CGO bindings source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();
        let has_callbacks = self.has_callback_params(extern_funcs);

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out, "// Do not edit manually.")?;
        writeln!(out)?;
        writeln!(out, "package {}", sanitize_go_package(&self.module_name))?;
        writeln!(out)?;
        writeln!(out, "/*")?;
        writeln!(out, "#cgo LDFLAGS: -lmimi_runtime -lpthread -ldl -lm")?;
        writeln!(out, "#include <stdlib.h>")?;
        writeln!(out, "#include <stdbool.h>")?;
        writeln!(out, "#include <stdint.h>")?;
        writeln!(out, "extern void mimi_string_free(char* s);")?;

        // C struct definitions for #[repr(C)] records
        self.write_c_struct_decls(&mut out)?;

        // Extern function declarations
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_c_decl(&mut out, func, &contract)?;
        }
        writeln!(out, "*/")?;
        writeln!(out, "import \"C\"")?;
        // Audit fix (full-audit-2026-08-05 §12): callback slots need a mutex;
        // only import "sync" when callbacks exist (unused imports break Go).
        if has_callbacks {
            writeln!(out, "import \"sync\"")?;
        }
        writeln!(out, "import \"unsafe\"")?;
        writeln!(out)?;

        // Go struct types for #[repr(C)] records
        self.write_go_struct_defs(&mut out)?;

        // Audit fix (full-audit-2026-08-05 §12, fix 5): Mimi's codegen emits
        // repr(C) bool fields as LLVM i8 (one byte) — see
        // codegen::types::mimi_type_to_llvm_extern.  The old binding declared
        // them as C `int` (4 bytes), corrupting every struct that crossed the
        // boundary.  They now cross as uint8_t/uint8 (1 byte on both sides,
        // 0 = false, 1 = true), matching the layout byte-for-byte.

        // Go callback types, slots, and C-exported trampolines
        self.write_go_callback_support(&mut out, extern_funcs)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_go_func(&mut out, func, &contract)?;
        }

        Ok(out)
    }

    fn has_callback_params(&self, extern_funcs: &[ExternFunc]) -> bool {
        extern_funcs.iter().any(|func| {
            let contract = self.build_contract(func);
            contract
                .args
                .iter()
                .any(|arg| matches!(arg, FfiArgContract::Callback { .. }))
        })
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_c_struct_decls(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        for (name, td) in repr_c {
            if let TypeDefKind::Record(fields) = &td.kind {
                writeln!(out, "typedef struct {0} {{", name)?;
                for field in fields {
                    let c_type = self.mimi_type_to_c_field(&field.ty);
                    writeln!(out, "    {} {};", c_type, field.name)?;
                }
                writeln!(out, "}} {};", name)?;
            }
        }
        Ok(())
    }

    fn write_go_struct_defs(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        if !repr_c.is_empty() {
            writeln!(out, "// Go structs matching #[repr(C)] Mimi records")?;
            for (name, td) in repr_c {
                if let TypeDefKind::Record(fields) = &td.kind {
                    writeln!(out, "type {} struct {{", name)?;
                    for field in fields {
                        let go_type = self.mimi_type_to_go_field(&field.ty);
                        let go_name = capitalize(&field.name);
                        writeln!(out, "    {} {}", go_name, go_type)?;
                    }
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }
            }
        }
        Ok(())
    }

    fn write_go_callback_support(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        // Generate type aliases and slots for callback parameters
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback {
                    param_types,
                    ret_type,
                } = &contract.args[i]
                {
                    let go_type = self.callback_go_type(param_types, ret_type);
                    let slot = self.callback_slot_name(&func.name, &p.name);
                    writeln!(
                        out,
                        "type {} {}",
                        self.callback_type_name(&func.name, &p.name),
                        go_type
                    )?;
                    writeln!(
                        out,
                        "var {} {}",
                        slot,
                        self.callback_type_name(&func.name, &p.name)
                    )?;
                    // Audit fix (full-audit-2026-08-05 §12): the slot is shared
                    // package state read by cgo trampolines (which may run on C
                    // threads) and written by Go callers — guard every access
                    // with a per-slot mutex.
                    writeln!(out, "var {}_mu sync.Mutex", slot)?;
                }
            }
        }
        writeln!(out)?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback {
                    param_types,
                    ret_type,
                } = &contract.args[i]
                {
                    self.write_go_callback_trampoline(
                        out,
                        &func.name,
                        &p.name,
                        param_types,
                        ret_type,
                    )?;
                }
            }
        }
        Ok(())
    }

    fn write_go_callback_trampoline(
        &self,
        out: &mut String,
        func_name: &str,
        param_name: &str,
        param_types: &[Type],
        ret_type: &Type,
    ) -> Result<(), std::fmt::Error> {
        let tramp = self.callback_trampoline_name(func_name, param_name);
        writeln!(out, "//export {}", tramp)?;
        let c_args: Vec<String> = param_types
            .iter()
            .enumerate()
            .map(|(j, ty)| format!("arg{} {}", j, self.go_cgo_param_type(ty)))
            .collect();
        let c_ret = self.go_cgo_ret_type(ret_type);
        let slot = self.callback_slot_name(func_name, param_name);
        let go_args: Vec<String> = param_types
            .iter()
            .enumerate()
            .map(|(j, ty)| format!("{}(arg{})", self.go_cast_from_c(ty), j))
            .collect();
        let call = format!("cb({})", go_args.join(", "));
        // Audit fix §12: snapshot the slot under the mutex, then invoke the
        // copy outside the lock.  The caller must NOT hold the mutex across
        // the C call, otherwise a synchronous C→Go upcall would deadlock.
        writeln!(out, "func {}({}) {} {{", tramp, c_args.join(", "), c_ret)?;
        writeln!(out, "\t{}_mu.Lock()", slot)?;
        writeln!(out, "\tcb := {}", slot)?;
        writeln!(out, "\t{}_mu.Unlock()", slot)?;
        if c_ret.is_empty() {
            writeln!(out, "\tif cb == nil {{")?;
            writeln!(out, "\t\treturn")?;
            writeln!(out, "\t}}")?;
            writeln!(out, "\t{}", call)?;
        } else {
            writeln!(out, "\tif cb == nil {{")?;
            writeln!(out, "\t\treturn {}", self.go_callback_default_ret(ret_type))?;
            writeln!(out, "\t}}")?;
            writeln!(out, "\treturn {}({})", self.go_cast_to_c(ret_type), call)?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
        Ok(())
    }

    fn callback_type_name(&self, func_name: &str, param_name: &str) -> String {
        go_export_name(&format!("{}_{}_cb", func_name, param_name))
    }

    fn callback_slot_name(&self, func_name: &str, param_name: &str) -> String {
        format!("{}_{}_cb_slot", func_name, param_name)
    }

    fn callback_trampoline_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}", func_name, param_name)
    }

    fn callback_go_type(&self, param_types: &[Type], ret_type: &Type) -> String {
        let args: Vec<String> = param_types
            .iter()
            .map(|ty| self.go_callback_arg_type(ty))
            .collect();
        let ret = self.go_callback_ret_type(ret_type);
        if ret.is_empty() {
            format!("func({})", args.join(", "))
        } else {
            format!("func({}) {}", args.join(", "), ret)
        }
    }

    fn callback_c_type(&self, param_types: &[Type], ret_type: &Type) -> String {
        self.callback_c_param_decl("callback", param_types, ret_type)
    }

    fn callback_c_param_decl(&self, name: &str, param_types: &[Type], ret_type: &Type) -> String {
        let args: Vec<String> = param_types
            .iter()
            .map(|ty| self.c_callback_arg_type(ty))
            .collect();
        let ret = self.c_callback_ret_type(ret_type);
        let args_str = if args.is_empty() {
            "void".to_string()
        } else {
            args.join(", ")
        };
        format!("{} (*{})({})", ret, name, args_str)
    }

    fn c_callback_arg_type(&self, ty: &Type) -> String {
        // Match the original Mimi scalar widths in the C trampoline ABI.
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "int".to_string(),
            Type::Name(name, _) if name == "i64" => "long long".to_string(),
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            Type::Name(name, _) if name == "bool" => "_Bool".to_string(),
            _ => "long long".to_string(),
        }
    }

    fn c_callback_ret_type(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "int".to_string(),
            Type::Name(name, _) if name == "i64" => "long long".to_string(),
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            Type::Name(name, _) if name == "bool" => "_Bool".to_string(),
            Type::Name(name, _) if name == "unit" => "void".to_string(),
            _ => "long long".to_string(),
        }
    }

    fn go_callback_arg_type(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "int32".to_string(),
            Type::Name(name, _) if name == "i64" => "int64".to_string(),
            Type::Name(name, _) if name == "f64" => "float64".to_string(),
            Type::Name(name, _) if name == "bool" => "bool".to_string(),
            _ => "int64".to_string(),
        }
    }

    fn go_callback_ret_type(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "int32".to_string(),
            Type::Name(name, _) if name == "i64" => "int64".to_string(),
            Type::Name(name, _) if name == "f64" => "float64".to_string(),
            Type::Name(name, _) if name == "bool" => "bool".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "int64".to_string(),
        }
    }

    fn go_cgo_param_type(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "C.int".to_string(),
            Type::Name(name, _) if name == "i64" => "C.longlong".to_string(),
            Type::Name(name, _) if name == "f64" => "C.double".to_string(),
            Type::Name(name, _) if name == "bool" => "C._Bool".to_string(),
            _ => "C.longlong".to_string(),
        }
    }

    fn go_cgo_ret_type(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "C.int".to_string(),
            Type::Name(name, _) if name == "i64" => "C.longlong".to_string(),
            Type::Name(name, _) if name == "f64" => "C.double".to_string(),
            Type::Name(name, _) if name == "bool" => "C._Bool".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "C.longlong".to_string(),
        }
    }

    fn go_cast_from_c(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "int32".to_string(),
            Type::Name(name, _) if name == "i64" => "int64".to_string(),
            Type::Name(name, _) if name == "f64" => "float64".to_string(),
            Type::Name(name, _) if name == "bool" => "bool".to_string(),
            _ => "int64".to_string(),
        }
    }

    fn go_cast_to_c(&self, ty: &Type) -> String {
        // Audit fix §12 (sweep): i32 callbacks previously cast through
        // C.longlong, mismatching the `int` C ABI of the trampoline.
        match ty.unlocated() {
            Type::Name(name, _) if name == "i32" => "C.int".to_string(),
            Type::Name(name, _) if name == "i64" => "C.longlong".to_string(),
            Type::Name(name, _) if name == "f64" => "C.double".to_string(),
            Type::Name(name, _) if name == "bool" => "C._Bool".to_string(),
            _ => "C.longlong".to_string(),
        }
    }

    fn go_callback_default_ret(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) if name == "f64" => "0.0".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "0".to_string(),
        }
    }

    fn write_c_decl(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                if let FfiArgContract::Callback {
                    param_types,
                    ret_type,
                } = &contract.args[i]
                {
                    self.callback_c_param_decl(&p.name, param_types, ret_type)
                } else {
                    format!("{} {}", self.mimi_type_to_c(contract, i), p.name)
                }
            })
            .collect();
        let ret = self.ret_type_to_c(contract);
        writeln!(out, "extern {} {}({});", ret, func.name, params.join(", "))
    }

    fn write_go_func(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let go_params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                let ty = if let FfiArgContract::Callback { .. } = &contract.args[i] {
                    self.callback_type_name(&func.name, &p.name)
                } else {
                    self.mimi_type_to_go(contract, i)
                };
                format!("{} {}", p.name, ty)
            })
            .collect();
        let go_ret = self.ret_type_to_go(contract);

        // Build C call arguments with conversions
        let mut conversions = String::new();
        let mut c_args = Vec::new();
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                // Audit fix (full-audit-2026-08-05 §12, fix 7): StringTransfer
                // moves ownership of the CString buffer to C; freeing it after
                // the call was a double-free/UAF.  Borrow/Json buffers remain
                // Mimi-owned temporaries and are still freed.
                FfiArgContract::StringTransfer => {
                    writeln!(conversions, "\t{}_c := C.CString({})", p.name, p.name)?;
                    writeln!(
                        conversions,
                        "\t// StringTransfer: ownership of {}_c moves to C — do NOT free.",
                        p.name
                    )?;
                    c_args.push(format!("{}_c", p.name));
                }
                FfiArgContract::StringBorrow | FfiArgContract::Json => {
                    writeln!(conversions, "\t{}_c := C.CString({})", p.name, p.name)?;
                    writeln!(conversions, "\tdefer C.free(unsafe.Pointer({}_c))", p.name)?;
                    c_args.push(format!("{}_c", p.name));
                }
                FfiArgContract::StructByValue(name) => {
                    writeln!(conversions, "\t{}_c := C.{}{{}}", p.name, name)?;
                    if let Some(td) = self.type_defs.get(name) {
                        if let TypeDefKind::Record(fields) = &td.kind {
                            for field in fields {
                                let go_field = capitalize(&field.name);
                                let rhs = self.c_expr_from_go_value(
                                    &field.ty,
                                    &format!("{}.{}", p.name, go_field),
                                );
                                writeln!(conversions, "\t{}_c.{} = {}", p.name, field.name, rhs)?;
                            }
                        }
                    }
                    c_args.push(format!("{}_c", p.name));
                }
                FfiArgContract::Int(scalar) => {
                    let cast = match scalar {
                        crate::ffi::contract::FfiScalarType::I32 => "C.int",
                        crate::ffi::contract::FfiScalarType::I64 => "C.longlong",
                        crate::ffi::contract::FfiScalarType::Bool => "C._Bool",
                    };
                    c_args.push(format!("{}({})", cast, p.name));
                }
                FfiArgContract::Cap(_)
                | FfiArgContract::CShared(_)
                | FfiArgContract::CBorrow(_)
                | FfiArgContract::CBorrowMut(_) => {
                    c_args.push(format!("C.longlong({})", p.name));
                }
                FfiArgContract::Float => {
                    c_args.push(format!("C.double({})", p.name));
                }
                FfiArgContract::Callback { .. } => {
                    let slot = self.callback_slot_name(&func.name, &p.name);
                    let tramp = self.callback_trampoline_name(&func.name, &p.name);
                    let type_name = self.callback_type_name(&func.name, &p.name);
                    // Audit fix §12 (fix 6): every slot access is guarded by the
                    // per-slot mutex.  Defer LIFO at function exit: Lock() is
                    // registered last so it runs FIRST, then the slot is cleared
                    // under the mutex, then Unlock() (registered first) runs
                    // last.  The mutex is never held across the C call, so a
                    // synchronous C→Go upcall cannot deadlock on it.
                    writeln!(conversions, "\t{}_mu.Lock()", slot)?;
                    writeln!(conversions, "\t{} = ({})({})", slot, type_name, p.name)?;
                    writeln!(conversions, "\t{}_mu.Unlock()", slot)?;
                    writeln!(conversions, "\tdefer {}_mu.Unlock()", slot)?;
                    writeln!(conversions, "\tdefer func() {{ {} = nil }}()", slot)?;
                    writeln!(conversions, "\tdefer {}_mu.Lock()", slot)?;
                    c_args.push(format!("C.{}", tramp));
                }
                FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => {
                    // unsafe.Pointer maps directly onto C `void*` in cgo.
                    c_args.push(p.name.clone());
                }
                _ => {
                    c_args.push(p.name.clone());
                }
            }
        }

        let go_func_name = go_export_name(&func.name);
        writeln!(
            out,
            "func {}({}) {} {{",
            go_func_name,
            go_params.join(", "),
            go_ret
        )?;
        write!(out, "{}", conversions)?;
        match &contract.ret {
            // Audit fix (full-audit-2026-08-05 §12, fix 4): contract split.
            // `String` is borrowed from C: NULL-checked, copied via GoString,
            // and NEVER freed.
            crate::ffi::contract::FfiRetContract::String => {
                writeln!(out, "\tresult := C.{}({})", func.name, c_args.join(", "))?;
                writeln!(out, "\tif result == nil {{")?;
                writeln!(out, "\t\treturn \"\"")?;
                writeln!(out, "\t}}")?;
                writeln!(
                    out,
                    "\t// String returns are borrowed from C (FfiRetContract::String): do NOT free."
                )?;
                writeln!(out, "\treturn C.GoString(result)")?;
            }
            // `StringOwned` / `Json` transfer ownership to Mimi: copy then free.
            crate::ffi::contract::FfiRetContract::StringOwned
            | crate::ffi::contract::FfiRetContract::Json => {
                writeln!(out, "\tresult := C.{}({})", func.name, c_args.join(", "))?;
                writeln!(out, "\tif result == nil {{")?;
                writeln!(out, "\t\treturn \"\"")?;
                writeln!(out, "\t}}")?;
                writeln!(out, "\tdefer C.mimi_string_free(result)")?;
                writeln!(
                    out,
                    "\t// Owned (StringOwned/Json): free the C buffer after copying."
                )?;
                writeln!(out, "\treturn C.GoString(result)")?;
            }
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "\tC.{}({})", func.name, c_args.join(", "))?;
            }
            // Audit fix §12 (sweep): cgo's C numeric types are distinct from Go
            // types; the bare `return C.f(...)` previously emitted for scalar
            // returns did not compile.  Convert explicitly.
            crate::ffi::contract::FfiRetContract::Int(scalar) => {
                let cast = match scalar {
                    crate::ffi::contract::FfiScalarType::I32 => "int32",
                    crate::ffi::contract::FfiScalarType::I64 => "int64",
                    crate::ffi::contract::FfiScalarType::Bool => "bool",
                };
                writeln!(
                    out,
                    "\treturn {}(C.{}({}))",
                    cast,
                    func.name,
                    c_args.join(", ")
                )?;
            }
            crate::ffi::contract::FfiRetContract::Float => {
                writeln!(
                    out,
                    "\treturn float64(C.{}({}))",
                    func.name,
                    c_args.join(", ")
                )?;
            }
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => {
                writeln!(
                    out,
                    "\treturn int64(C.{}({}))",
                    func.name,
                    c_args.join(", ")
                )?;
            }
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => {
                writeln!(
                    out,
                    "\treturn unsafe.Pointer(C.{}({}))",
                    func.name,
                    c_args.join(", ")
                )?;
            }
            crate::ffi::contract::FfiRetContract::StructByValue(name) => {
                writeln!(out, "\tresult := C.{}({})", func.name, c_args.join(", "))?;
                if let Some(td) = self.type_defs.get(name) {
                    if let TypeDefKind::Record(fields) = &td.kind {
                        let field_inits: Vec<String> = fields
                            .iter()
                            .map(|field| {
                                let init = self.go_expr_from_c_value(
                                    &field.ty,
                                    &format!("result.{}", field.name),
                                );
                                format!("{}: {}", capitalize(&field.name), init)
                            })
                            .collect();
                        writeln!(out, "\treturn {}{{{}}}", name, field_inits.join(", "))?;
                    } else {
                        writeln!(out, "\treturn {}{{}}", name)?;
                    }
                } else {
                    writeln!(out, "\treturn {}{{}}", name)?;
                }
            }
            _ => {
                writeln!(out, "\treturn C.{}({})", func.name, c_args.join(", "))?;
            }
        }
        writeln!(out, "}}")?;
        writeln!(out)
    }

    /// Build the C-side expression for a Go struct field value (recursive for
    /// nested #[repr(C)] records).
    fn c_expr_from_go_value(&self, ty: &Type, go_expr: &str) -> String {
        match ty.unlocated() {
            Type::Name(name, _) => match name.as_str() {
                "i32" => format!("C.int({})", go_expr),
                "i64" => format!("C.longlong({})", go_expr),
                "f64" => format!("C.double({})", go_expr),
                // bool crosses as uint8 (see audit fix 5 note in generate()).
                "bool" => format!("C.uint8_t({})", go_expr),
                other => {
                    if self.is_repr_c_record(other) {
                        if let Some(TypeDefKind::Record(fields)) =
                            self.type_defs.get(other).map(|td| &td.kind)
                        {
                            let parts: Vec<String> = fields
                                .iter()
                                .map(|f| {
                                    format!(
                                        "{}: {}",
                                        f.name,
                                        self.c_expr_from_go_value(
                                            &f.ty,
                                            &format!("{}.{}", go_expr, capitalize(&f.name))
                                        )
                                    )
                                })
                                .collect();
                            format!("C.{}{{{}}}", other, parts.join(", "))
                        } else {
                            go_expr.to_string()
                        }
                    } else {
                        // unsafe.Pointer / opaque fields pass through to C void*.
                        go_expr.to_string()
                    }
                }
            },
            _ => go_expr.to_string(),
        }
    }

    /// Build the Go-side expression for a C struct field value (recursive for
    /// nested #[repr(C)] records).
    fn go_expr_from_c_value(&self, ty: &Type, c_expr: &str) -> String {
        match ty.unlocated() {
            Type::Name(name, _) => match name.as_str() {
                "i32" => format!("int32({})", c_expr),
                "i64" => format!("int64({})", c_expr),
                "f64" => format!("float64({})", c_expr),
                // uint8_t surfaces as uint8 in cgo; pass straight through.
                "bool" => format!("uint8({})", c_expr),
                other => {
                    if self.is_repr_c_record(other) {
                        if let Some(TypeDefKind::Record(fields)) =
                            self.type_defs.get(other).map(|td| &td.kind)
                        {
                            let parts: Vec<String> = fields
                                .iter()
                                .map(|f| {
                                    format!(
                                        "{}: {}",
                                        capitalize(&f.name),
                                        self.go_expr_from_c_value(
                                            &f.ty,
                                            &format!("{}.{}", c_expr, f.name)
                                        )
                                    )
                                })
                                .collect();
                            format!("{}{{{}}}", other, parts.join(", "))
                        } else {
                            c_expr.to_string()
                        }
                    } else {
                        // C void* surfaces as unsafe.Pointer in cgo already.
                        c_expr.to_string()
                    }
                }
            },
            _ => c_expr.to_string(),
        }
    }

    fn mimi_type_to_c(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "void*".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "int".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "long long".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "_Bool".to_string(),
            },
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "char*".to_string(),
            FfiArgContract::Cap(_) => "long long".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "void*".to_string(),
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "long long".to_string(),
            FfiArgContract::Json => "char*".to_string(),
            FfiArgContract::StructByValue(name) => format!("struct {}", name),
            FfiArgContract::Callback {
                param_types,
                ret_type,
            } => self.callback_c_type(param_types, ret_type),
            FfiArgContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn ret_type_to_c(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "int".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "long long".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "_Bool".to_string(),
            },
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "char*".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "void*".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "long long".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "char*".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("struct {}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "void*".to_string(),
        }
    }

    fn mimi_type_to_go(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "unsafe.Pointer".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "int32".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "int64".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            FfiArgContract::Float => "float64".to_string(),
            FfiArgContract::StringBorrow
            | FfiArgContract::StringTransfer
            | FfiArgContract::Json => "string".to_string(),
            FfiArgContract::Cap(_) => "int64".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => {
                "unsafe.Pointer".to_string()
            }
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "int64".to_string(),
            FfiArgContract::StructByValue(name) => name.clone(),
            FfiArgContract::Callback {
                param_types,
                ret_type,
            } => self.callback_go_type(param_types, ret_type),
            FfiArgContract::Unsupported(_) => "unsafe.Pointer".to_string(),
        }
    }

    fn ret_type_to_go(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "".to_string(),
            crate::ffi::contract::FfiRetContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "int32".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "int64".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            crate::ffi::contract::FfiRetContract::Float => "float64".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "string".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "unsafe.Pointer".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "int64".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "string".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => name.clone(),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "unsafe.Pointer".to_string(),
        }
    }

    fn mimi_type_to_c_field(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int".to_string(),
                "i64" => "long long".to_string(),
                "f64" => "double".to_string(),
                // Audit fix (full-audit-2026-08-05 §12, fix 5): the previous
                // "int" (4 bytes) corrupted #[repr(C)] struct layout.  Mimi's
                // codegen emits bool fields as a single byte (LLVM i8, see
                // codegen::types::mimi_type_to_llvm_extern); uint8_t matches
                // that layout exactly and is unambiguous in cgo.
                "bool" => "uint8_t".to_string(),
                other => {
                    if self.is_repr_c_record(other) {
                        format!("struct {}", other)
                    } else {
                        "void*".to_string()
                    }
                }
            },
            _ => "void*".to_string(),
        }
    }

    fn mimi_type_to_go_field(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int32".to_string(),
                "i64" => "int64".to_string(),
                "f64" => "float64".to_string(),
                // Go uint8 is 1 byte, matching the C uint8_t / LLVM i8 field.
                // Surfaces as bool to Go callers via mimiCBoolToGo conversion.
                "bool" => "uint8".to_string(),
                other => {
                    if self.is_repr_c_record(other) {
                        other.to_string()
                    } else {
                        "unsafe.Pointer".to_string()
                    }
                }
            },
            _ => "unsafe.Pointer".to_string(),
        }
    }

    fn is_repr_c_record(&self, name: &str) -> bool {
        self.type_defs
            .get(name)
            .map(|td| {
                matches!(td.kind, TypeDefKind::Record(_))
                    && td.attributes.contains(&TypeAttribute::ReprC)
            })
            .unwrap_or(false)
    }
}

fn sanitize_go_package(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.starts_with(|c: char| c.is_numeric()) {
        s = format!("_{}", s);
    }
    s.to_lowercase()
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn go_export_name(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}
