//! Java JNI binding generator from Mimi extern declarations.
//!
//! Generates a JNI C bridge file and a Java interface class.
//!
//! Usage:
//!   mimi emit-java-bindings path/to/pkg.mimi -o jni_bridge.c --java MimiModule.java

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Java JNI binding generator.
pub struct JniBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl JniBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the JNI C bridge source.
    pub fn generate_c(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator (JNI)")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out)?;
        writeln!(out, "#include <jni.h>")?;
        writeln!(out, "#include <stdlib.h>")?;
        writeln!(out, "#include <string.h>")?;
        writeln!(out, "#include <stdint.h>")?;
        writeln!(out)?;
        writeln!(out, "// Mimi runtime")?;
        writeln!(out, "extern void mimi_string_free(char* s);")?;
        writeln!(out)?;

        self.write_c_struct_decls(&mut out)?;
        self.write_c_callback_support(&mut out, extern_funcs)?;

        let java_class = sanitize_java_class(&self.module_name);

        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_jni_function(&mut out, func, &contract, &java_class)?;
        }

        Ok(out)
    }

    /// Generate the Java interface class.
    pub fn generate_java(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();
        let java_class = sanitize_java_class(&self.module_name);

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "public class {} {{", java_class)?;
        writeln!(out)?;
        writeln!(out, "    static {{")?;
        writeln!(out, "        System.loadLibrary(\"mimi_{}\");", self.module_name)?;
        writeln!(out, "    }}")?;
        writeln!(out)?;

        self.write_java_struct_defs(&mut out)?;

        // Functional interfaces for callback parameters
        self.write_java_callback_interfaces(&mut out, extern_funcs)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            let params: Vec<String> = func
                .params
                .iter()
                .enumerate()
                .map(|(i, p)| {
                    let ty = if let FfiArgContract::Callback { param_types, ret_type } = &contract.args[i] {
                        self.callback_interface_name(&func.name, &p.name, param_types, ret_type)
                    } else {
                        self.mimi_type_to_java(&contract, i)
                    };
                    format!("{} {}", ty, sanitize_java_name(&p.name))
                })
                .collect();
            let ret = self.ret_type_to_java(&contract);
            writeln!(out, "    public static native {} {}({});", ret, func.name, params.join(", "))?;
        }

        writeln!(out, "}}")?;
        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&crate::ast::TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_jni_function(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
        java_class: &str,
    ) -> Result<(), std::fmt::Error> {
        // JNI function name: Java_{package}_{class}_{method}
        writeln!(
            out,
            "JNIEXPORT {} JNICALL Java_{}_{}(JNIEnv *env, jclass cls",
            self.ret_type_to_jni(contract),
            java_class,
            func.name
        )?;
        for (i, p) in func.params.iter().enumerate() {
            write!(out, ", {} {}", self.mimi_type_to_jni(contract, i), sanitize_java_name(&p.name))?;
        }
        writeln!(out, ") {{")?;

        // Extract struct-by-value arguments first.
        for (i, p) in func.params.iter().enumerate() {
            if let FfiArgContract::StructByValue(name) = &contract.args[i] {
                let jname = sanitize_java_name(&p.name);
                self.write_struct_arg_extract(out, java_class, name, &jname)?;
            }
        }

        // Convert Java string arguments to C strings before the call.
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    let jname = sanitize_java_name(&p.name);
                    writeln!(out, "    const char* {}_str = (*env)->GetStringUTFChars(env, {}, NULL);", jname, jname)?;
                }
                _ => {}
            }
        }

        // Set up callback slots for function-pointer parameters.
        for (i, p) in func.params.iter().enumerate() {
            if let FfiArgContract::Callback { .. } = &contract.args[i] {
                let jname = sanitize_java_name(&p.name);
                let setup = self.callback_setup_name(&func.name, &p.name);
                writeln!(out, "    {}(env, {});", setup, jname)?;
            }
        }
        writeln!(out)?;

        // Build C call arguments
        let c_args: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                let jname = sanitize_java_name(&p.name);
                match &contract.args[i] {
                    FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                        format!("(char*){}_str", jname)
                    }
                    FfiArgContract::Int | FfiArgContract::Cap(_) | FfiArgContract::CShared(_)
                    | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => jname,
                    FfiArgContract::Float => jname,
                    FfiArgContract::StructByValue(_) => format!("{}_struct", jname),
                    FfiArgContract::Callback { .. } => self.callback_trampoline_name(&func.name, &p.name),
                    _ => format!("(intptr_t)NULL /* {} */", jname),
                }
            })
            .collect();

        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "    {}({});", func.name, c_args.join(", "))?;
            }
            crate::ffi::contract::FfiRetContract::Int => {
                writeln!(out, "    jlong mimi_ret = (jlong)({}({}));", func.name, c_args.join(", "))?;
            }
            crate::ffi::contract::FfiRetContract::Float => {
                writeln!(out, "    jdouble mimi_ret = (jdouble)({}({}));", func.name, c_args.join(", "))?;
            }
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => {
                writeln!(out, "    char* raw_ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    jstring mimi_ret = NULL;")?;
                writeln!(out, "    if (raw_ret) {{")?;
                writeln!(out, "        mimi_ret = (*env)->NewStringUTF(env, raw_ret);")?;
                writeln!(out, "        mimi_string_free(raw_ret);")?;
                writeln!(out, "    }}")?;
            }
            crate::ffi::contract::FfiRetContract::StructByValue(name) => {
                writeln!(out, "    struct {} mimi_struct_ret = {}({});", name, func.name, c_args.join(", "))?;
                writeln!(out, "    jobject mimi_ret = NULL;")?;
                self.write_struct_return_build(out, java_class, name, "mimi_ret")?;
            }
            _ => {
                writeln!(out, "    // Unsupported return type")?;
                writeln!(out, "    jlong mimi_ret = 0;")?;
            }
        }

        // Release string arguments and tear down callback slots
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    let jname = sanitize_java_name(&p.name);
                    writeln!(out, "    if ({}_str) (*env)->ReleaseStringUTFChars(env, {}, {}_str);", jname, jname, jname)?;
                }
                FfiArgContract::Callback { .. } => {
                    let teardown = self.callback_teardown_name(&func.name, &p.name);
                    writeln!(out, "    {}(env);", teardown)?;
                }
                _ => {}
            }
        }

        if !matches!(&contract.ret, crate::ffi::contract::FfiRetContract::Unit) {
            writeln!(out, "    return mimi_ret;")?;
        }

        writeln!(out, "}}")?;
        writeln!(out)
    }

    fn write_c_struct_decls(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        if !repr_c.is_empty() {
            writeln!(out, "// #[repr(C)] struct definitions")?;
            for (name, td) in repr_c {
                if let TypeDefKind::Record(fields) = &td.kind {
                    writeln!(out, "typedef struct {} {{", name)?;
                    for field in fields {
                        let c_type = self.mimi_type_to_c_field(&field.ty);
                        writeln!(out, "    {} {};", c_type, field.name)?;
                    }
                    writeln!(out, "}} {};", name)?;
                }
            }
            writeln!(out)?;
        }
        Ok(())
    }

    fn write_c_callback_support(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        let java_class = sanitize_java_class(&self.module_name);
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback { param_types, ret_type } = &contract.args[i] {
                    let slot = self.callback_slot_name(&func.name, &p.name);
                    let tramp = self.callback_trampoline_name(&func.name, &p.name);
                    let iface = self.callback_interface_name(&func.name, &p.name, param_types, ret_type);
                    let sig = self.callback_jni_signature(param_types, ret_type);
                    writeln!(out, "typedef struct {{")?;
                    writeln!(out, "    JNIEnv* env;")?;
                    writeln!(out, "    jobject global_ref;")?;
                    writeln!(out, "    jmethodID method;")?;
                    writeln!(out, "}} {0}_t;", slot)?;
                    writeln!(out, "static __thread {0}_t {0} = {{NULL, NULL, NULL}};", slot)?;
                    let ret_c = self.callback_c_type(ret_type);
                    let c_args: Vec<String> = param_types
                        .iter()
                        .enumerate()
                        .map(|(j, ty)| format!("{} arg{}", self.callback_c_type(ty), j))
                        .collect();
                    writeln!(
                        out,
                        "static {} {}({}) {{",
                        ret_c, tramp, c_args.join(", ")
                    )?;
                    writeln!(out, "    if (!{}.env || !{}.global_ref || !{}.method) {{", slot, slot, slot)?;
                    writeln!(out, "        return {};", self.callback_default_ret(ret_type))?;
                    writeln!(out, "    }}")?;
                    let jargs: Vec<String> = (0..param_types.len()).map(|j| format!("jarg{}", j)).collect();
                    for (j, ty) in param_types.iter().enumerate() {
                        let local_ty = self.callback_jni_arg_type(ty);
                        writeln!(out, "    {} jarg{} = ({})arg{};", local_ty, j, local_ty, j)?;
                    }
                    let call = self.callback_jni_call(ret_type);
                    if call == "Void" {
                        writeln!(
                            out,
                            "    (*{}.env)->CallVoidMethod({}.env, {}.global_ref, {}.method, {});",
                            slot, slot, slot, slot, jargs.join(", ")
                        )?;
                    } else {
                        let ret_local = self.callback_jni_ret_type(ret_type);
                        writeln!(
                            out,
                            "    {} jret = (*{}.env)->Call{}Method({}.env, {}.global_ref, {}.method, {});",
                            ret_local, slot, call, slot, slot, slot, jargs.join(", ")
                        )?;
                        writeln!(out, "    return ({})jret;", ret_c)?;
                    }
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                    let cb_setup = self.callback_setup_name(&func.name, &p.name);
                    writeln!(
                        out,
                        "static void {}(JNIEnv* env, jobject cb) {{",
                        cb_setup
                    )?;
                    writeln!(out, "    jclass cb_cls = (*env)->FindClass(env, \"{}${}\");", java_class, iface)?;
                    writeln!(out, "    {0}.method = (*env)->GetMethodID(env, cb_cls, \"apply\", \"{1}\");", slot, sig)?;
                    writeln!(out, "    {0}.global_ref = (*env)->NewGlobalRef(env, cb);", slot)?;
                    writeln!(out, "    {0}.env = env;", slot)?;
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                    let cb_teardown = self.callback_teardown_name(&func.name, &p.name);
                    writeln!(
                        out,
                        "static void {}(JNIEnv* env) {{",
                        cb_teardown
                    )?;
                    writeln!(out, "    if ({0}.global_ref) {{ (*env)->DeleteGlobalRef(env, {0}.global_ref); {0}.global_ref = NULL; {0}.env = NULL; {0}.method = NULL; }}", slot)?;
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }
            }
        }
        Ok(())
    }

    fn write_java_struct_defs(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        for (name, td) in repr_c {
            if let TypeDefKind::Record(fields) = &td.kind {
                writeln!(out, "    public static class {} {{", name)?;
                for field in fields {
                    writeln!(
                        out,
                        "        public {} {};",
                        self.java_field_type(&field.ty),
                        field.name
                    )?;
                }
                writeln!(out, "    }}")?;
                writeln!(out)?;
            }
        }
        Ok(())
    }

    fn write_java_callback_interfaces(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback { param_types, ret_type } = &contract.args[i] {
                    let iface = self.callback_interface_name(&func.name, &p.name, param_types, ret_type);
                    let ret_java = self.callback_java_ret_type(ret_type);
                    let params: Vec<String> = param_types
                        .iter()
                        .enumerate()
                        .map(|(j, ty)| format!("{} arg{}", self.callback_java_arg_type(ty), j))
                        .collect();
                    writeln!(out, "    @FunctionalInterface")?;
                    writeln!(out, "    public interface {} {{", iface)?;
                    writeln!(out, "        {} apply({});", ret_java, params.join(", "))?;
                    writeln!(out, "    }}")?;
                    writeln!(out)?;
                }
            }
        }
        Ok(())
    }

    fn write_struct_arg_extract(
        &self,
        out: &mut String,
        java_class: &str,
        type_name: &str,
        param_name: &str,
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "    struct {} {}_struct;", type_name, param_name)?;
        writeln!(out, "    jclass {0}_cls = (*env)->FindClass(env, \"{1}${0}\");", type_name, java_class)?;
        if let Some(td) = self.type_defs.get(type_name) {
            if let TypeDefKind::Record(fields) = &td.kind {
                for field in fields {
                    let sig = self.jni_field_signature(&field.ty);
                    writeln!(
                        out,
                        "    jfieldID {0}_{1}_fid = (*env)->GetFieldID(env, {0}_cls, \"{1}\", \"{2}\");",
                        param_name, field.name, sig
                    )?;
                    let (jtype, cast) = self.jni_field_access(&field.ty);
                    writeln!(
                        out,
                        "    {0}_struct.{1} = ({2})(*env)->Get{3}Field(env, {0}, {0}_{1}_fid);",
                        param_name, field.name, cast, jtype
                    )?;
                }
            }
        }
        Ok(())
    }

    fn write_struct_return_build(
        &self,
        out: &mut String,
        java_class: &str,
        type_name: &str,
        result_var: &str,
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "    jclass ret_cls = (*env)->FindClass(env, \"{}${}\");", java_class, type_name)?;
        writeln!(out, "    jmethodID ret_init = (*env)->GetMethodID(env, ret_cls, \"<init>\", \"()V\");")?;
        writeln!(out, "    jobject ret_obj = (*env)->NewObject(env, ret_cls, ret_init);")?;
        if let Some(td) = self.type_defs.get(type_name) {
            if let TypeDefKind::Record(fields) = &td.kind {
                for field in fields {
                    let sig = self.jni_field_signature(&field.ty);
                    writeln!(
                        out,
                        "    jfieldID ret_{}_fid = (*env)->GetFieldID(env, ret_cls, \"{}\", \"{}\");",
                        field.name, field.name, sig
                    )?;
                    let jtype = self.jni_field_access(&field.ty).0;
                    writeln!(
                        out,
                        "    (*env)->Set{}Field(env, ret_obj, ret_{}_fid, ret.{});",
                        jtype, field.name, field.name
                    )?;
                }
            }
        }
        writeln!(out, "    {} = ret_obj;", result_var)?;
        Ok(())
    }

    fn mimi_type_to_c_field(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int32_t".to_string(),
                "i64" => "int64_t".to_string(),
                "f64" => "double".to_string(),
                "bool" => "bool".to_string(),
                other => {
                    if self.is_repr_c_record(other) {
                        format!("struct {}", other)
                    } else {
                        "void*".to_string()
                    }
                }
            },
            _ => "void*".to_string(),
        }
    }

    fn java_field_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int".to_string(),
                "i64" => "long".to_string(),
                "f64" => "double".to_string(),
                "bool" => "boolean".to_string(),
                _ => "long".to_string(),
            },
            _ => "Object".to_string(),
        }
    }

    fn jni_field_signature(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "I".to_string(),
                "i64" => "J".to_string(),
                "f64" => "D".to_string(),
                "bool" => "Z".to_string(),
                _ => "J".to_string(),
            },
            _ => "Ljava/lang/Object;".to_string(),
        }
    }

    fn jni_field_access(&self, ty: &Type) -> (String, String) {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => ("Int".to_string(), "int32_t".to_string()),
                "i64" => ("Long".to_string(), "int64_t".to_string()),
                "f64" => ("Double".to_string(), "double".to_string()),
                "bool" => ("Boolean".to_string(), "bool".to_string()),
                _ => ("Long".to_string(), "int64_t".to_string()),
            },
            _ => ("Object".to_string(), "jobject".to_string()),
        }
    }

    fn is_repr_c_record(&self, name: &str) -> bool {
        self.type_defs
            .get(name)
            .map(|td| {
                matches!(td.kind, TypeDefKind::Record(_))
                    && td.attributes.contains(&TypeAttribute::ReprC)
            })
            .unwrap_or(false)
    }

    fn callback_interface_name(&self, func_name: &str, param_name: &str, _param_types: &[Type], _ret_type: &Type) -> String {
        format!("{}{}Callback", sanitize_java_class(func_name), sanitize_java_class(param_name))
    }

    fn callback_jni_signature(&self, param_types: &[Type], ret_type: &Type) -> String {
        let mut sig = String::from("(");
        for ty in param_types {
            sig.push_str(&self.jni_type_signature(ty));
        }
        sig.push(')');
        sig.push_str(&self.jni_type_signature(ret_type));
        sig
    }

    fn jni_type_signature(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "I".to_string(),
                "i64" => "J".to_string(),
                "f64" => "D".to_string(),
                "bool" => "Z".to_string(),
                "unit" => "V".to_string(),
                _ => "J".to_string(),
            },
            _ => "J".to_string(),
        }
    }

    fn callback_java_arg_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            _ => "long".to_string(),
        }
    }

    fn callback_java_ret_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            Type::Name(name, _) if name == "unit" => "void".to_string(),
            _ => "long".to_string(),
        }
    }

    fn callback_c_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            Type::Name(name, _) if name == "unit" => "void".to_string(),
            _ => "int64_t".to_string(),
        }
    }

    fn callback_default_ret(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "f64" => "0.0".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "0".to_string(),
        }
    }

    fn callback_jni_arg_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "i32" => "jint".to_string(),
            Type::Name(name, _) if name == "i64" => "jlong".to_string(),
            Type::Name(name, _) if name == "f64" => "jdouble".to_string(),
            Type::Name(name, _) if name == "bool" => "jboolean".to_string(),
            _ => "jlong".to_string(),
        }
    }

    fn callback_jni_ret_type(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "i32" => "jint".to_string(),
            Type::Name(name, _) if name == "i64" => "jlong".to_string(),
            Type::Name(name, _) if name == "f64" => "jdouble".to_string(),
            Type::Name(name, _) if name == "bool" => "jboolean".to_string(),
            Type::Name(name, _) if name == "unit" => "void".to_string(),
            _ => "jlong".to_string(),
        }
    }

    fn callback_jni_call(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "i32" => "Int".to_string(),
            Type::Name(name, _) if name == "i64" => "Long".to_string(),
            Type::Name(name, _) if name == "f64" => "Double".to_string(),
            Type::Name(name, _) if name == "bool" => "Boolean".to_string(),
            Type::Name(name, _) if name == "unit" => "Void".to_string(),
            _ => "Long".to_string(),
        }
    }

    fn callback_slot_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_slot", func_name, param_name)
    }

    fn callback_trampoline_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_trampoline", func_name, param_name)
    }

    fn callback_setup_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_setup", func_name, param_name)
    }

    fn callback_teardown_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_teardown", func_name, param_name)
    }

    fn mimi_type_to_jni(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "jlong".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "jlong".to_string(),
            FfiArgContract::Float => "jdouble".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "jstring".to_string(),
            FfiArgContract::Cap(_) => "jlong".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "jlong".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "jlong".to_string(),
            FfiArgContract::Json => "jstring".to_string(),
            FfiArgContract::StructByValue(_) => "jobject".to_string(),
            FfiArgContract::Callback { .. } => "jobject".to_string(),
            FfiArgContract::Unsupported(_) => "jlong".to_string(),
        }
    }

    fn ret_type_to_jni(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "jlong".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "jdouble".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "jstring".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(_) => "jobject".to_string(),
            _ => "jlong".to_string(),
        }
    }

    fn mimi_type_to_java(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "long".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "long".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "String".to_string(),
            FfiArgContract::Cap(_) => "long".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "long".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "long".to_string(),
            FfiArgContract::Json => "String".to_string(),
            FfiArgContract::StructByValue(name) => name.clone(),
            FfiArgContract::Callback { .. } => "long".to_string(),
            FfiArgContract::Unsupported(_) => "long".to_string(),
        }
    }

    fn ret_type_to_java(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "long".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "String".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => name.clone(),
            _ => "long".to_string(),
        }
    }
}

fn sanitize_java_class(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    if s.starts_with(|c: char| c.is_numeric()) {
        s = format!("_{}", s);
    }
    // PascalCase
    s.split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().to_string() + &chars.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect()
}

fn sanitize_java_name(name: &str) -> String {
    // Java reserved words
    match name {
        "abstract" | "assert" | "boolean" | "break" | "byte" | "case" | "catch" | "char"
        | "class" | "const" | "continue" | "default" | "do" | "double" | "else" | "enum"
        | "extends" | "final" | "finally" | "float" | "for" | "goto" | "if" | "implements"
        | "import" | "instanceof" | "int" | "interface" | "long" | "native" | "new"
        | "package" | "private" | "protected" | "public" | "return" | "short" | "static"
        | "strictfp" | "super" | "switch" | "synchronized" | "this" | "throw" | "throws"
        | "transient" | "try" | "void" | "volatile" | "while" => format!("{}_", name),
        _ => name.to_string(),
    }
}
