//! Node.js N-API binding generator from Mimi extern declarations.
//!
//! Generates a `.c` file that wraps Mimi's C API using N-API,
//! allowing Mimi functions to be called from Node.js.
//!
//! Also generates a `.d.ts` TypeScript type declaration file.
//!
//! Usage:
//!   mimi emit-node-bindings path/to/pkg.mimi -o bindings.c --ts types.d.ts

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, TypeDef};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Node.js N-API binding generator.
pub struct NodeBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl NodeBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete N-API C source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator (N-API)")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out)?;
        writeln!(out, "#include <node_api.h>")?;
        writeln!(out, "#include <stdlib.h>")?;
        writeln!(out, "#include <string.h>")?;
        writeln!(out)?;

        // Forward declarations for Mimi runtime
        writeln!(out, "// Mimi runtime function declarations")?;
        writeln!(out, "extern void mimi_string_free(char* s);")?;
        writeln!(out)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_napi_function(&mut out, func, &contract)?;
        }

        // Module initialization
        self.write_module_init(&mut out, extern_funcs)?;

        Ok(out)
    }

    /// Generate TypeScript type declarations.
    pub fn generate_dts(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "// TypeScript declarations for module: {}", self.module_name)?;
        writeln!(out)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            let params: Vec<String> = func
                .params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("{}: {}", p.name, self.mimi_type_to_ts(&contract, i)))
                .collect();
            let ret = self.ret_type_to_ts(&contract);
            writeln!(out, "export function {}({}): {};", func.name, params.join(", "), ret)?;
        }

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&crate::ast::TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_napi_function(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let wrapper_name = format!("napi_{}", func.name);

        writeln!(out, "static napi_value {}(napi_env env, napi_callback_info info) {{", wrapper_name)?;
        writeln!(out, "    size_t argc = {};", func.params.len())?;
        writeln!(out, "    napi_value args[{}];", func.params.len().max(1))?;
        writeln!(out, "    napi_get_cb_info(env, info, &argc, args, NULL, NULL);")?;
        writeln!(out)?;

        // Extract arguments
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::Int | FfiArgContract::Cap(_) | FfiArgContract::CShared(_)
                | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => {
                    writeln!(out, "    int64_t {}_val;", p.name)?;
                    writeln!(out, "    napi_get_value_int64(env, args[{}], &{}_val);", i, p.name)?;
                }
                FfiArgContract::Float => {
                    writeln!(out, "    double {}_val;", p.name)?;
                    writeln!(out, "    napi_get_value_double(env, args[{}], &{}_val);", i, p.name)?;
                }
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(out, "    size_t {}_len;", p.name)?;
                    writeln!(out, "    napi_get_value_string_utf8(env, args[{}], NULL, 0, &{}_len);", i, p.name)?;
                    writeln!(out, "    char* {}_buf = (char*)malloc({}_len + 1);", p.name, p.name)?;
                    writeln!(out, "    napi_get_value_string_utf8(env, args[{}], {}_buf, {}_len + 1, &{}_len);", i, p.name, p.name, p.name)?;
                }
                _ => {
                    writeln!(out, "    // Unsupported arg type for {}", p.name)?;
                }
            }
        }

        // Build C call
        let c_args: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| match &contract.args[i] {
                FfiArgContract::Int | FfiArgContract::Cap(_) | FfiArgContract::CShared(_)
                | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => format!("{}_val", p.name),
                FfiArgContract::Float => format!("{}_val", p.name),
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => format!("{}_buf", p.name),
                _ => format!("(intptr_t)NULL /* {} */", p.name),
            })
            .collect();

        writeln!(out)?;

        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "    {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_get_undefined(env, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::Int => {
                writeln!(out, "    long long ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_create_int64(env, ret, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::Float => {
                writeln!(out, "    double ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_create_double(env, ret, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => {
                writeln!(out, "    char* ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    if (ret) {{")?;
                writeln!(out, "        napi_create_string_utf8(env, ret, NAPI_AUTO_LENGTH, &result);")?;
                writeln!(out, "        mimi_string_free(ret);")?;
                writeln!(out, "    }} else {{")?;
                writeln!(out, "        napi_get_undefined(env, &result);")?;
                writeln!(out, "    }}")?;
            }
            _ => {
                writeln!(out, "    // Unsupported return type")?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_get_undefined(env, &result);")?;
            }
        }

        // Free string arguments
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(out, "    free({}_buf);", p.name)?;
                }
                _ => {}
            }
        }

        writeln!(out, "    return result;")?;
        writeln!(out, "}}")?;
        writeln!(out)
    }

    fn write_module_init(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "static napi_value Init(napi_env env, napi_value exports) {{")?;
        for func in extern_funcs {
            writeln!(out, "    {{")?;
            writeln!(out, "        napi_value fn;")?;
            writeln!(
                out,
                "        napi_create_function(env, \"{}\", NAPI_AUTO_LENGTH, napi_{}, NULL, &fn);",
                func.name, func.name
            )?;
            writeln!(out, "        napi_set_named_property(env, exports, \"{}\", fn);", func.name)?;
            writeln!(out, "    }}")?;
        }
        writeln!(out, "    return exports;")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
        writeln!(out, "NAPI_MODULE({}, Init)", self.module_name)?;
        Ok(())
    }

    fn mimi_type_to_ts(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "any".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "number".to_string(),
            FfiArgContract::Float => "number".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "string".to_string(),
            FfiArgContract::Cap(_) => "number".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "number".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "number".to_string(),
            FfiArgContract::Json => "string".to_string(),
            FfiArgContract::StructByValue(_) => "number".to_string(),
            FfiArgContract::Callback { .. } => "Function".to_string(),
            FfiArgContract::Unsupported(_) => "any".to_string(),
        }
    }

    fn ret_type_to_ts(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "number".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "number".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "string".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_) | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "number".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_) | crate::ffi::contract::FfiRetContract::CBorrow(_) | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "number".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "object".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(_) => "number".to_string(),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "any".to_string(),
        }
    }
}
