//! Node.js N-API binding generator from Mimi extern declarations.
//!
//! Generates a `.c` file that wraps Mimi's C API using N-API,
//! allowing Mimi functions to be called from Node.js.
//!
//! Also generates a `.d.ts` TypeScript type declaration file.
//!
//! Usage:
//!   mimi emit-node-bindings path/to/pkg.mimi -o bindings.c --ts types.d.ts

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Node.js N-API binding generator.
pub struct NodeBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl NodeBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete N-API C source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator (N-API)")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out)?;
        writeln!(out, "#include <node_api.h>")?;
        writeln!(out, "#include <stdlib.h>")?;
        writeln!(out, "#include <string.h>")?;
        writeln!(out, "#include <stdint.h>")?;
        writeln!(out)?;

        // Forward declarations for Mimi runtime
        writeln!(out, "// Mimi runtime function declarations")?;
        writeln!(out, "extern void mimi_string_free(char* s);")?;
        writeln!(out)?;

        // C struct definitions for #[repr(C)] records
        self.write_c_struct_decls(&mut out)?;

        // C callback trampolines for func(...) parameters
        self.write_callback_support(&mut out, extern_funcs)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_napi_function(&mut out, func, &contract)?;
        }

        // Module initialization
        self.write_module_init(&mut out, extern_funcs)?;

        Ok(out)
    }

    /// Generate TypeScript type declarations.
    pub fn generate_dts(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "// TypeScript declarations for module: {}", self.module_name)?;
        writeln!(out)?;

        // Interfaces for #[repr(C)] records
        self.write_ts_interfaces(&mut out)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            let params: Vec<String> = func
                .params
                .iter()
                .enumerate()
                .map(|(i, p)| format!("{}: {}", p.name, self.mimi_type_to_ts(&contract, i)))
                .collect();
            let ret = self.ret_type_to_ts(&contract);
            writeln!(out, "export function {}({}): {};", func.name, params.join(", "), ret)?;
        }

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_c_struct_decls(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        if !repr_c.is_empty() {
            writeln!(out, "// #[repr(C)] struct definitions")?;
            for (name, td) in repr_c {
                if let TypeDefKind::Record(fields) = &td.kind {
                    writeln!(out, "typedef struct {} {{", name)?;
                    for field in fields {
                        let c_type = self.mimi_type_to_c_field(&field.ty);
                        writeln!(out, "    {} {};", c_type, field.name)?;
                    }
                    writeln!(out, "}} {};", name)?;
                }
            }
            writeln!(out)?;
        }
        Ok(())
    }

    fn write_ts_interfaces(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);
        for (name, td) in repr_c {
            if let TypeDefKind::Record(fields) = &td.kind {
                writeln!(out, "export interface {} {{", name)?;
                for field in fields {
                    let ts_type = self.mimi_type_to_ts_field(&field.ty);
                    writeln!(out, "    {}: {};", field.name, ts_type)?;
                }
                writeln!(out, "}}")?;
                writeln!(out)?;
            }
        }
        Ok(())
    }

    fn write_callback_support(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        for func in extern_funcs {
            let contract = self.build_contract(func);
            for (i, p) in func.params.iter().enumerate() {
                if let FfiArgContract::Callback { param_types, ret_type } = &contract.args[i] {
                    let slot = self.callback_slot_name(&func.name, &p.name);
                    let tramp = self.callback_trampoline_name(&func.name, &p.name);
                    writeln!(out, "typedef struct {{ napi_env env; napi_ref ref; }} {}_t;", slot)?;
                    writeln!(out, "static __thread {}_t {} = {{NULL, NULL}};", slot, slot)?;
                    let ret_c = self.callback_c_type(ret_type);
                    let c_args: Vec<String> = param_types
                        .iter()
                        .enumerate()
                        .map(|(j, ty)| format!("{} arg{}", self.callback_c_type(ty), j))
                        .collect();
                    writeln!(
                        out,
                        "static {} {}({}) {{",
                        ret_c,
                        tramp,
                        c_args.join(", ")
                    )?;
                    writeln!(out, "    if (!{}.env || !{}.ref) {{", slot, slot)?;
                    writeln!(out, "        return {};", self.callback_default_ret(ret_type))?;
                    writeln!(out, "    }}")?;
                    writeln!(out, "    napi_value fn;")?;
                    writeln!(out, "    napi_get_reference_value({}.env, {}.ref, &fn);", slot, slot)?;
                    for (j, ty) in param_types.iter().enumerate() {
                        writeln!(out, "    napi_value argv{};", j)?;
                        match ty {
                            Type::Name(name, _) if name == "f64" => {
                                writeln!(out, "    napi_create_double({}.env, (double)arg{}, &argv{});", slot, j, j)?;
                            }
                            Type::Name(name, _) if name == "bool" => {
                                writeln!(out, "    napi_get_boolean({}.env, (bool)arg{}, &argv{});", slot, j, j)?;
                            }
                            _ => {
                                writeln!(out, "    napi_create_int64({}.env, arg{}, &argv{});", slot, j, j)?;
                            }
                        }
                    }
                    let argv_list: Vec<String> = (0..param_types.len()).map(|j| format!("&argv{}", j)).collect();
                    writeln!(out, "    napi_value result;")?;
                    writeln!(
                        out,
                        "    if (napi_call_function({}.env, NULL, fn, {}, {}, &result) != napi_ok) {{",
                        slot,
                        param_types.len(),
                        argv_list.join(", ")
                    )?;
                    writeln!(out, "        return {};", self.callback_default_ret(ret_type))?;
                    writeln!(out, "    }}")?;
                    if !matches!(ret_type.as_ref(), Type::Name(name, _) if name == "unit") {
                        writeln!(
                            out,
                            "    {} ret;",
                            ret_c
                        )?;
                        match ret_type.as_ref() {
                            Type::Name(name, _) if name == "f64" => {
                                writeln!(out, "    napi_get_value_double({}.env, result, &ret);", slot)?;
                            }
                            Type::Name(name, _) if name == "bool" => {
                                writeln!(out, "    napi_get_value_bool({}.env, result, &ret);", slot)?;
                            }
                            _ => {
                                writeln!(out, "    napi_get_value_int64({}.env, result, &ret);", slot)?;
                            }
                        }
                        writeln!(out, "    return ret;")?;
                    }
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }
            }
        }
        Ok(())
    }

    fn write_callback_arg_extract(
        &self,
        out: &mut String,
        func_name: &str,
        param_name: &str,
        arg_index: usize,
    ) -> Result<(), std::fmt::Error> {
        let slot = self.callback_slot_name(func_name, param_name);
        writeln!(out, "    napi_valuetype {}_type;", param_name)?;
        writeln!(
            out,
            "    napi_typeof(env, args[{}], &{}_type);",
            arg_index, param_name
        )?;
        writeln!(
            out,
            "    if ({}_type == napi_function) {{",
            param_name
        )?;
        writeln!(
            out,
            "        napi_create_reference(env, args[{}], 1, &{}.ref);",
            arg_index, slot
        )?;
        writeln!(out, "        {}.env = env;", slot)?;
        writeln!(out, "    }}")?;
        Ok(())
    }

    fn callback_slot_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_slot", func_name, param_name)
    }

    fn callback_trampoline_name(&self, func_name: &str, param_name: &str) -> String {
        format!("mimi_cb_{}_{}_trampoline", func_name, param_name)
    }

    fn callback_c_type(&self, ty: &Type) -> String {
        // Use the original Mimi scalar widths so generated C trampolines match
        // the function-pointer ABI expected by the compiled extern function.
        match ty {
            Type::Name(name, _) if name == "i32" => "int32_t".to_string(),
            Type::Name(name, _) if name == "i64" => "int64_t".to_string(),
            Type::Name(name, _) if name == "f64" => "double".to_string(),
            Type::Name(name, _) if name == "bool" => "bool".to_string(),
            Type::Name(name, _) if name == "unit" => "void".to_string(),
            _ => "int64_t".to_string(),
        }
    }

    fn callback_default_ret(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) if name == "f64" => "0.0".to_string(),
            Type::Name(name, _) if name == "unit" => "".to_string(),
            _ => "0".to_string(),
        }
    }

    fn callback_ts_type(&self, param_types: &[Type], ret_type: &Type) -> String {
        let args: Vec<String> = param_types
            .iter()
            .enumerate()
            .map(|(i, ty)| {
                let ty_str = match ty {
                    Type::Name(name, _) if name == "f64" => "number",
                    _ => "number",
                };
                format!("arg{}: {}", i, ty_str)
            })
            .collect();
        let ret = match ret_type {
            Type::Name(name, _) if name == "f64" => "number",
            Type::Name(name, _) if name == "unit" => "void",
            _ => "number",
        };
        format!("({}) => {}", args.join(", "), ret)
    }

    fn write_napi_function(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let wrapper_name = format!("napi_{}", func.name);

        writeln!(out, "static napi_value {}(napi_env env, napi_callback_info info) {{", wrapper_name)?;
        writeln!(out, "    size_t argc = {};", func.params.len())?;
        writeln!(out, "    napi_value args[{}];", func.params.len().max(1))?;
        writeln!(out, "    napi_get_cb_info(env, info, &argc, args, NULL, NULL);")?;
        writeln!(out)?;

        // Extract arguments
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::Int | FfiArgContract::Cap(_) | FfiArgContract::CShared(_)
                | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => {
                    writeln!(out, "    int64_t {}_val;", p.name)?;
                    writeln!(out, "    napi_get_value_int64(env, args[{}], &{}_val);", i, p.name)?;
                }
                FfiArgContract::Float => {
                    writeln!(out, "    double {}_val;", p.name)?;
                    writeln!(out, "    napi_get_value_double(env, args[{}], &{}_val);", i, p.name)?;
                }
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(out, "    size_t {}_len;", p.name)?;
                    writeln!(out, "    napi_get_value_string_utf8(env, args[{}], NULL, 0, &{}_len);", i, p.name)?;
                    writeln!(out, "    char* {}_buf = (char*)malloc({}_len + 1);", p.name, p.name)?;
                    writeln!(out, "    napi_get_value_string_utf8(env, args[{}], {}_buf, {}_len + 1, &{}_len);", i, p.name, p.name, p.name)?;
                }
                FfiArgContract::StructByValue(name) => {
                    self.write_struct_arg_extract(out, &p.name, name, i)?;
                }
                FfiArgContract::Callback { .. } => {
                    self.write_callback_arg_extract(out, &func.name, &p.name, i)?;
                }
                _ => {
                    writeln!(out, "    // Unsupported arg type for {}", p.name)?;
                }
            }
        }

        // Build C call
        let c_args: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| match &contract.args[i] {
                FfiArgContract::Int | FfiArgContract::Cap(_) | FfiArgContract::CShared(_)
                | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => format!("{}_val", p.name),
                FfiArgContract::Float => format!("{}_val", p.name),
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => format!("{}_buf", p.name),
                FfiArgContract::StructByValue(_name) => format!("{}_struct", p.name),
                FfiArgContract::Callback { .. } => self.callback_trampoline_name(&func.name, &p.name),
                _ => format!("(intptr_t)NULL /* {} */", p.name),
            })
            .collect();

        writeln!(out)?;

        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => {
                writeln!(out, "    {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_get_undefined(env, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::Int => {
                writeln!(out, "    long long ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_create_int64(env, ret, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::Float => {
                writeln!(out, "    double ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_create_double(env, ret, &result);")?;
            }
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => {
                writeln!(out, "    char* ret = {}({});", func.name, c_args.join(", "))?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    if (ret) {{")?;
                writeln!(out, "        napi_create_string_utf8(env, ret, NAPI_AUTO_LENGTH, &result);")?;
                writeln!(out, "        mimi_string_free(ret);")?;
                writeln!(out, "    }} else {{")?;
                writeln!(out, "        napi_get_undefined(env, &result);")?;
                writeln!(out, "    }}")?;
            }
            crate::ffi::contract::FfiRetContract::StructByValue(name) => {
                writeln!(out, "    struct {} ret = {}({});", name, func.name, c_args.join(", "))?;
                self.write_struct_return_build(out, "ret", name)?;
            }
            _ => {
                writeln!(out, "    // Unsupported return type")?;
                writeln!(out, "    napi_value result;")?;
                writeln!(out, "    napi_get_undefined(env, &result);")?;
            }
        }

        // Free string arguments and release callback references
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                    writeln!(out, "    free({}_buf);", p.name)?;
                }
                FfiArgContract::Callback { .. } => {
                    let slot = self.callback_slot_name(&func.name, &p.name);
                    writeln!(out, "    if ({}.ref) {{ napi_delete_reference(env, {}.ref); {}.ref = NULL; {}.env = NULL; }}", slot, slot, slot, slot)?;
                }
                _ => {}
            }
        }

        writeln!(out, "    return result;")?;
        writeln!(out, "}}")?;
        writeln!(out)
    }

    fn write_struct_arg_extract(
        &self,
        out: &mut String,
        param_name: &str,
        type_name: &str,
        arg_index: usize,
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "    struct {} {}_struct;", type_name, param_name)?;
        if let Some(td) = self.type_defs.get(type_name) {
            if let TypeDefKind::Record(fields) = &td.kind {
                for field in fields {
                    writeln!(out, "    napi_value {}_{}_val;", param_name, field.name)?;
                    writeln!(
                        out,
                        "    napi_get_named_property(env, args[{}], \"{}\", &{}_{}_val);",
                        arg_index, field.name, param_name, field.name
                    )?;
                    let extract = self.napi_extract_for_field(&field.ty, &format!("{}_{}_val", param_name, field.name), &format!("{}_struct.{}", param_name, field.name));
                    writeln!(out, "    {}", extract)?;
                }
            }
        }
        Ok(())
    }

    fn write_struct_return_build(
        &self,
        out: &mut String,
        c_var: &str,
        type_name: &str,
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "    napi_value result;")?;
        writeln!(out, "    napi_create_object(env, &result);")?;
        if let Some(td) = self.type_defs.get(type_name) {
            if let TypeDefKind::Record(fields) = &td.kind {
                for field in fields {
                    let c_field = format!("{}.{}", c_var, field.name);
                    let create = self.napi_create_for_field(&field.ty, &c_field, &field.name);
                    writeln!(out, "    napi_value {}_prop;", field.name)?;
                    writeln!(out, "    {}", create)?;
                    writeln!(
                        out,
                        "    napi_set_named_property(env, result, \"{}\", {}_prop);",
                        field.name, field.name
                    )?;
                }
            }
        }
        Ok(())
    }

    fn napi_extract_for_field(&self, ty: &Type, js_var: &str, c_var: &str) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => format!("napi_get_value_int32(env, {}, &{});", js_var, c_var),
                "i64" => format!("napi_get_value_int64(env, {}, &{});", js_var, c_var),
                "f64" => format!("napi_get_value_double(env, {}, &{});", js_var, c_var),
                "bool" => format!("napi_get_value_bool(env, {}, &{});", js_var, c_var),
                _ => format!("// unsupported field type {}", name),
            },
            _ => "// unsupported field type".to_string(),
        }
    }

    fn napi_create_for_field(&self, ty: &Type, c_var: &str, prop_var: &str) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => format!("napi_create_int32(env, {}, &{}_prop);", c_var, prop_var),
                "i64" => format!("napi_create_int64(env, {}, &{}_prop);", c_var, prop_var),
                "f64" => format!("napi_create_double(env, {}, &{}_prop);", c_var, prop_var),
                "bool" => format!("napi_get_boolean(env, {}, &{}_prop);", c_var, prop_var),
                _ => format!("// unsupported field type {}", name),
            },
            _ => "// unsupported field type".to_string(),
        }
    }

    fn write_module_init(
        &self,
        out: &mut String,
        extern_funcs: &[ExternFunc],
    ) -> Result<(), std::fmt::Error> {
        writeln!(out, "static napi_value Init(napi_env env, napi_value exports) {{")?;
        for func in extern_funcs {
            writeln!(out, "    {{")?;
            writeln!(out, "        napi_value fn;")?;
            writeln!(
                out,
                "        napi_create_function(env, \"{}\", NAPI_AUTO_LENGTH, napi_{}, NULL, &fn);",
                func.name, func.name
            )?;
            writeln!(out, "        napi_set_named_property(env, exports, \"{}\", fn);", func.name)?;
            writeln!(out, "    }}")?;
        }
        writeln!(out, "    return exports;")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
        writeln!(out, "NAPI_MODULE({}, Init)", self.module_name)?;
        Ok(())
    }

    fn mimi_type_to_ts(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "any".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "number".to_string(),
            FfiArgContract::Float => "number".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "string".to_string(),
            FfiArgContract::Cap(_) => "number".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "number".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "number".to_string(),
            FfiArgContract::Json => "string".to_string(),
            FfiArgContract::StructByValue(name) => name.clone(),
            FfiArgContract::Callback { param_types, ret_type } => {
                self.callback_ts_type(param_types, ret_type)
            }
            FfiArgContract::Unsupported(_) => "any".to_string(),
        }
    }

    fn ret_type_to_ts(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "number".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "number".to_string(),
            crate::ffi::contract::FfiRetContract::String | crate::ffi::contract::FfiRetContract::StringOwned => "string".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_) | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "number".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_) | crate::ffi::contract::FfiRetContract::CBorrow(_) | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "number".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "object".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => name.clone(),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "any".to_string(),
        }
    }

    fn mimi_type_to_c_field(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int32_t".to_string(),
                "i64" => "int64_t".to_string(),
                "f64" => "double".to_string(),
                "bool" => "bool".to_string(),
                other => {
                    if self.is_repr_c_record(other) {
                        format!("struct {}", other)
                    } else {
                        "void*".to_string()
                    }
                }
            },
            _ => "void*".to_string(),
        }
    }

    fn mimi_type_to_ts_field(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" | "i64" | "f64" => "number".to_string(),
                "bool" => "boolean".to_string(),
                _ => "any".to_string(),
            },
            _ => "any".to_string(),
        }
    }

    fn is_repr_c_record(&self, name: &str) -> bool {
        self.type_defs
            .get(name)
            .map(|td| {
                matches!(td.kind, TypeDefKind::Record(_))
                    && td.attributes.contains(&TypeAttribute::ReprC)
            })
            .unwrap_or(false)
    }
}
