//! Python binding generator (pybind11) from Mimi extern declarations.
//!
//! Generates a `.cpp` file that wraps Mimi's C API using pybind11,
//! allowing Mimi functions to be called from Python with natural types.
//!
//! Usage:
//!   mimi emit-py-bindings path/to/pkg.mimi -o bindings.cpp
//!   cmake -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)") \
//!         -DMIMI_HEADER=/path/to/mimi_ffi.h \
//!         -DMIMI_LIB=/path/to/libmimi_runtime.so \
//!         -B build && cmake --build build

use std::collections::{HashMap, HashSet};
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Python binding generator — produces a pybind11 `.cpp` file.
pub struct PyBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl PyBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete pybind11 C++ source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        self.write_preamble(&mut out)?;
        self.write_include_guard(&mut out)?;
        self.write_includes(&mut out)?;
        self.write_c_type_forward_decls(&mut out)?;
        self.write_module_def(&mut out)?;

        for func in extern_funcs {
            self.write_function(&mut out, func)?;
        }

        self.write_module_init(&mut out)?;
        Ok(out)
    }

    /// Generate a `.pyi` type stub file for the module.
    pub fn generate_pyi(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();
        writeln!(out, "# Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "# Type stubs for module: {}", self.module_name)?;
        writeln!(out, "from typing import Any, List, Optional, Dict, Tuple")?;
        writeln!(out)?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            let py_params: Vec<String> = func.params.iter().enumerate()
                .map(|(i, p)| format!("{}: {}", p.name, self.mimi_type_to_python(&contract, i)))
                .collect();
            let py_ret = self.ret_type_to_python(&contract);
            writeln!(out, "def {}({}) -> {}: ...", func.name, py_params.join(", "), py_ret)?;
        }

        writeln!(out)?;
        Ok(out)
    }

    /// Build FFI contract with record type name awareness for proper JSON mapping.
    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self.type_defs.iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps(func, &HashSet::new(), &record_type_names)
    }

    fn mimi_type_to_python(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "Any".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "int".to_string(),
            FfiArgContract::Float => "float".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "str".to_string(),
            FfiArgContract::Cap(_) => "int".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "int".to_string(),
            FfiArgContract::CShared(_) | FfiArgContract::CBorrow(_) | FfiArgContract::CBorrowMut(_) => "int".to_string(),
            FfiArgContract::Json => "str".to_string(),
            FfiArgContract::Callback { .. } => "callable".to_string(),
            FfiArgContract::Unsupported(_) => "Any".to_string(),
        }
    }

    fn ret_type_to_python(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "None".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "float".to_string(),
            crate::ffi::contract::FfiRetContract::String => "str".to_string(),
            crate::ffi::contract::FfiRetContract::StringOwned => "str".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_) | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "int".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_) | crate::ffi::contract::FfiRetContract::CBorrow(_) | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "int".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "Dict[str, Any]".to_string(),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "Any".to_string(),
        }
    }

    fn write_preamble(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "// Auto-generated by Mimi F9 Python binding generator.")?;
        writeln!(out, "// Requires: pybind11, Mimi C header + runtime library.")?;
        writeln!(out, "// Build: see accompanying CMakeLists.txt")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_include_guard(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let guard = format!("MIMI_PY_BIND_{}_H", self.module_name.to_uppercase().replace(|c: char| !c.is_ascii_alphanumeric(), "_"));
        writeln!(out, "#ifndef {}", guard)?;
        writeln!(out, "#define {}", guard)?;
        writeln!(out)?;
        Ok(())
    }

    fn write_includes(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "#include <pybind11/pybind11.h>")?;
        writeln!(out, "#include <pybind11/stl.h>")?;
        writeln!(out, "#include <cstdint>")?;
        writeln!(out, "#include <cstddef>")?;
        writeln!(out, "#include <cerrno>")?;
        writeln!(out, "#include <stdexcept>")?;
        writeln!(out, "extern \"C\" {{")?;
        writeln!(out, "#include \"mimi_ffi.h\"")?;
        writeln!(out, "}}")?;
        writeln!(out, "namespace py = pybind11;")?;
        writeln!(out)?;
        Ok(())
    }

    /// Forward-declare Mimi C API types (not defined in the C header).
    fn write_c_type_forward_decls(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "// Mimi C API types — defined in mimi_ffi.h as typedefs")?;
        writeln!(out, "// Ensure C++ compatibility:")?;
        writeln!(out, "using MimiHandle = int64_t;")?;
        writeln!(out, "using MimiCap = int64_t;")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_module_def(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "PYBIND11_MODULE({}, m) {{", self.module_name)?;
        writeln!(out, "    m.doc() = \"Mimi language FFI bindings (auto-generated)\";")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_function(&self, out: &mut String, func: &ExternFunc) -> Result<(), std::fmt::Error> {
        let contract = self.build_contract(func);
        let ret_cpp = self.contract_ret_to_cpp(&contract);
        let func_name = &func.name;

        // Build parameter list for the lambda
        let mut param_decls = Vec::new();
        for (i, param) in func.params.iter().enumerate() {
            let cpp_type = self.contract_arg_to_cpp(&contract, i);
            param_decls.push(format!("{} {}", cpp_type, param.name));
        }

        // Auto-enable errno checking if return type is Result-like.
        // Uses exact function name matching (not `contains`) to avoid false
        // positives on wrapper functions like `my_open_wrapper`.
        let check_errno = matches!(func.name.as_str(),
            "errno" | "strerror" | "perror"
            | "open" | "openat" | "creat" | "fopen" | "fdopen"
            | "read" | "write" | "pread" | "pwrite" | "readv" | "writev"
            | "socket" | "connect" | "bind" | "listen" | "accept" | "accept4"
            | "send" | "recv" | "sendto" | "recvfrom" | "sendmsg" | "recvmsg"
            | "close" | "shutdown" | "dup" | "dup2" | "dup3"
            | "fcntl" | "ioctl" | "poll" | "select" | "epoll_create" | "epoll_ctl" | "epoll_wait"
            | "fork" | "execve" | "wait" | "waitpid" | "waitid"
            | "kill" | "raise" | "signal" | "sigaction" | "sigprocmask"
            | "pipe" | "pipe2" | "mkfifo" | "socketpair"
            | "getaddrinfo" | "freeaddrinfo" | "getnameinfo"
            | "gethostbyname" | "gethostbyaddr"
            | "dlopen" | "dlsym" | "dlerror" | "dlclose"
            | "mmap" | "munmap" | "mprotect" | "msync"
            | "opendir" | "readdir" | "closedir"
            | "stat" | "fstat" | "lstat" | "access" | "chmod" | "chown"
            | "link" | "unlink" | "rename" | "symlink" | "mkdir" | "rmdir"
            | "mount" | "umount" | "chdir" | "fchdir" | "getcwd"
            | "setjmp" | "longjmp" | "sigsetjmp" | "siglongjmp"
            | "time" | "ctime" | "localtime" | "gmtime"
            | "strtol" | "strtoll" | "strtoul" | "strtoull" | "atoi" | "atol"
            | "malloc" | "calloc" | "realloc" | "posix_memalign"
            | "pthread_create" | "pthread_join" | "pthread_mutex_lock" | "pthread_mutex_unlock"
            | "sem_init" | "sem_wait" | "sem_post" | "sem_destroy"
            | "mq_open" | "mq_send" | "mq_receive" | "mq_close" | "mq_unlink"
            | "clock_gettime" | "clock_settime" | "timer_create" | "timer_settime"
            | "getenv" | "setenv" | "unsetenv" | "putenv"
            | "system" | "popen" | "pclose" | "execl" | "execle" | "execlp" | "execv" | "execvp"
            | "realpath" | "canonicalize_file_name"
            | "tempnam" | "tmpfile" | "mkstemp" | "mkdtemp"
            | "getopt" | "getopt_long" | "getopt_long_only"
        );

        writeln!(out, "    // {} — {}", func_name, func.name)?;
        writeln!(out, "    m.def(\"{}\", []({}) -> {} {{", func_name, param_decls.join(", "), ret_cpp)?;

        // Error handler: convert contract violations to C++ exceptions
        writeln!(out, "        mimi_runtime_set_error_handler([](const char* m) {{")?;
        writeln!(out, "            throw std::runtime_error(std::string(\"FFI contract violation: \") + m);")?;
        writeln!(out, "        }});")?;
        if check_errno {
            writeln!(out, "        errno = 0;")?;
        }

        // Build native call arguments
        let native_args: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, param)| self.arg_to_native(&contract, i, param))
            .collect();
        let ret_expr = self.ret_to_native(&contract, func_name, &native_args);

        if matches!(contract.ret, crate::ffi::contract::FfiRetContract::Unit) {
            writeln!(out, "        try {{")?;
            writeln!(out, "            {}({});", func_name, native_args.join(", "))?;
            writeln!(out, "            mimi_runtime_set_error_handler(nullptr);")?;
            if check_errno {
                writeln!(out, "            if (errno != 0) {{")?;
                writeln!(out, "                PyErr_SetFromErrno(PyExc_OSError);")?;
                writeln!(out, "                throw py::error_already_set();")?;
                writeln!(out, "            }}")?;
            }
            writeln!(out, "            return py::none();")?;
            writeln!(out, "        }} catch (const std::exception& e) {{")?;
            writeln!(out, "            mimi_runtime_set_error_handler(nullptr);")?;
            writeln!(out, "            throw py::value_error(e.what());")?;
            writeln!(out, "        }}")?;
        } else {
            writeln!(out, "        try {{")?;
            writeln!(out, "            auto _ret = {};", ret_expr)?;
            writeln!(out, "            mimi_runtime_set_error_handler(nullptr);")?;
            if check_errno {
                writeln!(out, "            if (errno != 0) {{")?;
                writeln!(out, "                PyErr_SetFromErrno(PyExc_OSError);")?;
                writeln!(out, "                throw py::error_already_set();")?;
                writeln!(out, "            }}")?;
            }
            writeln!(out, "            return _ret;")?;
            writeln!(out, "        }} catch (const std::exception& e) {{")?;
            writeln!(out, "            mimi_runtime_set_error_handler(nullptr);")?;
            writeln!(out, "            throw py::value_error(e.what());")?;
            writeln!(out, "        }}")?;
        }

        writeln!(out, "    }}, \"{}\"", func.name)?;

        if let Some(requires) = &func.requires {
            writeln!(out, "        .doc(\"Requires: {:?}\")", requires)?;
        }
        if let Some(ensures) = &func.ensures {
            writeln!(out, "        .doc(\"Ensures: {:?}\")", ensures)?;
        }

        writeln!(out, "    );")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_module_init(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "}}")?;
        writeln!(out)?;
        writeln!(out, "#endif // {}", format!("MIMI_PY_BIND_{}_H", self.module_name.to_uppercase().replace(|c: char| !c.is_ascii_alphanumeric(), "_")))?;
        Ok(())
    }

    // ---- Type mapping helpers ----

    fn mimi_type_to_cpp(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "int32_t".to_string(),
                "i64" => "int64_t".to_string(),
                "f64" => "double".to_string(),
                "bool" => "bool".to_string(),
                "string" => "std::string".to_string(),
                "unit" | "nothing" => "void".to_string(),
                _ => {
                    if self.type_defs.contains_key(name) {
                        name.clone()
                    } else {
                        "void*".to_string()
                    }
                }
            },
            Type::RawPtr(inner) | Type::RawPtrMut(inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("{}*", inner)
            }
            Type::CShared(_) | Type::CBorrow(_) | Type::CBorrowMut(_) => "MimiHandle".to_string(),
            Type::Cap(_) => "MimiCap".to_string(),
            Type::RawString => "char*".to_string(),
            Type::Shared(inner) | Type::LocalShared(inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("MimiHandle /* shared {} */", inner)
            }
            Type::Ref(_, inner) | Type::RefMut(_, inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("{}*", inner)
            }
            _ => "void*".to_string(),
        }
    }

    fn contract_arg_to_cpp(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "void*".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => {
                "const std::string&".to_string()
            }
            FfiArgContract::Cap(_) => "MimiCap".to_string(),
            FfiArgContract::RawPtr(inner) | FfiArgContract::RawPtrMut(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            FfiArgContract::CShared(inner) | FfiArgContract::CBorrow(inner) | FfiArgContract::CBorrowMut(inner) => {
                format!("MimiHandle /* {} */", self.mimi_type_to_cpp(inner))
            }
            FfiArgContract::Json => "const std::string&".to_string(),
            FfiArgContract::Callback { .. } => "py::function".to_string(),
            FfiArgContract::Unsupported(_) => "py::object".to_string(),
        }
    }

    fn contract_ret_to_cpp(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned
            | crate::ffi::contract::FfiRetContract::Json => "std::string".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::RawPtrMut(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::CShared(inner)
            | crate::ffi::contract::FfiRetContract::CBorrow(inner)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(inner) => {
                format!("MimiHandle /* {} */", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "py::object".to_string(),
        }
    }

    fn arg_to_native(&self, contract: &FfiContract, index: usize, param: &crate::ast::ExternParam) -> String {
        if index >= contract.args.len() {
            return "0".to_string();
        }
        let name = &param.name;
        match &contract.args[index] {
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                format!("{}.c_str()", name)
            }
            FfiArgContract::Callback { .. } => {
                format!("{}.cast<py::function>()", name)
            }
            _ => name.clone(),
        }
    }

    fn ret_to_native(&self, contract: &FfiContract, func_name: &str, native_args: &[String]) -> String {
        let args = native_args.join(", ");
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => format!("{}({}), py::none()", func_name, args),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => {
                // Safe nullptr handling: lambda captures result once, checks before constructing string
                format!("[&]() -> std::string {{ const char* _r = {}({}); return _r ? std::string(_r) : std::string(); }}()", func_name, args)
            }
            crate::ffi::contract::FfiRetContract::Json => {
                format!("[&]() -> std::string {{ const char* _r = {}({}); return _r ? std::string(_r) : std::string(); }}()", func_name, args)
            }
            _ => format!("{}({})", func_name, args),
        }
    }
}

fn func_param_name(index: usize) -> String {
    format!("arg{}", index)
}

/// Generate a CMakeLists.txt snippet for building the Python extension.
/// `mimi_lib_path` is the path to the user's compiled Mimi shared library (.so),
/// or empty string if unavailable.
pub fn generate_cmake_snippet(module_name: &str, header_path: &str, lib_path: &str, mimi_lib_path: &str) -> String {
    let mimi_lib_link = if mimi_lib_path.is_empty() {
        String::new()
    } else {
        // Strip lib prefix and .so suffix to get the link target name
        let libname = std::path::Path::new(mimi_lib_path)
            .file_stem()
            .and_then(|s| s.to_str())
            .map(|s| s.strip_prefix("lib").unwrap_or(s))
            .unwrap_or("mimi_module");
        format!(
            "find_library(MIMI_USER_LIB NAMES {libname} PATHS \"{dir}\")
target_link_libraries({module_name} PRIVATE ${{MIMI_USER_LIB}})
",
            libname = libname,
            module_name = module_name,
            dir = std::path::Path::new(mimi_lib_path).parent()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| ".".to_string()),
        )
    };

    format!(
r#"cmake_minimum_required(VERSION 3.14)
project({module_name}_bindings LANGUAGES CXX)

find_package(pybind11 REQUIRED)
find_library(MIMI_RUNTIME_LIB NAMES mimi_runtime PATHS "{lib_path}")

pybind11_add_module({module_name} bindings.cpp)
target_include_directories({module_name} PRIVATE "{header_path}")
target_link_libraries({module_name} PRIVATE ${{MIMI_RUNTIME_LIB}})
{mimi_lib_link}set_target_properties({module_name} PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED ON
)
"#,
        module_name = module_name,
        header_path = header_path,
        lib_path = lib_path,
        mimi_lib_link = mimi_lib_link,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ExternFunc, ExternParam, Type};

    fn sample_funcs() -> Vec<ExternFunc> {
        vec![
            ExternFunc {
                name: "mimi_add".to_string(),
                params: vec![
                    ExternParam { name: "a".to_string(), ty: Type::Name("i64".into(), Vec::new()), cap_mode: None },
                    ExternParam { name: "b".to_string(), ty: Type::Name("i64".into(), Vec::new()), cap_mode: None },
                ],
                ret: Some(Type::Name("i64".into(), Vec::new())),
                requires: None,
                ensures: None,
                variadic: false,
            },
            ExternFunc {
                name: "mimi_greet".to_string(),
                params: vec![
                    ExternParam { name: "name".to_string(), ty: Type::Name("string".into(), Vec::new()), cap_mode: None },
                ],
                ret: None,
                requires: None,
                ensures: None,
                variadic: false,
            },
        ]
    }

    #[test]
    fn test_py_bind_generator_basic() {
        let funcs = sample_funcs();
        let type_defs = HashMap::new();
        let gen = PyBindGenerator::new(type_defs, "mimi_test");
        let code = gen.generate(&funcs).unwrap();

        assert!(code.contains("PYBIND11_MODULE"));
        assert!(code.contains("mimi_add"));
        assert!(code.contains("mimi_greet"));
        assert!(code.contains("int64_t"));
        assert!(code.contains("std::string"));
        assert!(code.contains("m.def"));
    }

    #[test]
    fn test_py_bind_generator_contains_cpp_types() {
        let funcs = sample_funcs();
        let type_defs = HashMap::new();
        let gen = PyBindGenerator::new(type_defs, "test_mod");
        let code = gen.generate(&funcs).unwrap();

        assert!(code.contains("#include <pybind11/pybind11.h>"));
        assert!(code.contains("extern \"C\""));
        assert!(code.contains("#include \"mimi_ffi.h\""));
        assert!(code.contains("using MimiHandle = int64_t;"));
        assert!(code.contains("using MimiCap = int64_t;"));
    }

    #[test]
    fn test_cmake_snippet() {
        let cmake = generate_cmake_snippet("my_mod", "/usr/local/include/mimi", "/usr/local/lib", "");
        assert!(cmake.contains("pybind11_add_module(my_mod"));
        assert!(cmake.contains("find_package(pybind11 REQUIRED)"));
        assert!(cmake.contains("CXX_STANDARD 17"));
    }

    #[test]
    fn test_cmake_snippet_with_mimi_lib() {
        let cmake = generate_cmake_snippet("my_mod", "/usr/local/include/mimi", "/usr/local/lib", "/home/user/mymod.so");
        assert!(cmake.contains("find_library(MIMI_USER_LIB"));
        assert!(cmake.contains("my_mod PRIVATE ${MIMI_USER_LIB}"));
    }
}
