//! Python binding generator (pybind11) from Mimi extern declarations.
//!
//! Generates a `.cpp` file that wraps Mimi's C API using pybind11,
//! allowing Mimi functions to be called from Python with natural types.
//!
//! Usage:
//!   mimi emit-py-bindings path/to/pkg.mimi -o bindings.cpp
//!   cmake -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)") \
//!         -DMIMI_HEADER=/path/to/mimi_ffi.h \
//!         -DMIMI_LIB=/path/to/libmimi_runtime.so \
//!         -B build && cmake --build build

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Python binding generator — produces a pybind11 `.cpp` file.
pub struct PyBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl PyBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete pybind11 C++ source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        self.write_preamble(&mut out)?;
        self.write_include_guard(&mut out)?;
        self.write_includes(&mut out)?;
        self.write_type_classes(&mut out)?;
        self.write_module_def(&mut out)?;

        for func in extern_funcs {
            self.write_function(&mut out, func)?;
        }

        self.write_module_init(&mut out)?;
        Ok(out)
    }

    fn write_preamble(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "// Auto-generated by Mimi F9 Python binding generator.")?;
        writeln!(out, "// Requires: pybind11, Mimi C header + runtime library.")?;
        writeln!(out, "// Build: see accompanying CMakeLists.txt")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_include_guard(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let guard = format!("MIMI_PY_BIND_{}_H", self.module_name.to_uppercase().replace(|c: char| !c.is_ascii_alphanumeric(), "_"));
        writeln!(out, "#ifndef {}", guard)?;
        writeln!(out, "#define {}", guard)?;
        writeln!(out)?;
        Ok(())
    }

    fn write_includes(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "#include <pybind11/pybind11.h>")?;
        writeln!(out, "#include <pybind11/stl.h>")?;
        writeln!(out, "#include <cstdint>")?;
        writeln!(out, "#include <cstddef>")?;
        writeln!(out, "#include \"mimi_ffi.h\"")?;
        writeln!(out, "namespace py = pybind11;")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_type_classes(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        // MimiHandle — opaque int64_t wrapper
        writeln!(out, "class MimiHandle {{")?;
        writeln!(out, "public:")?;
        writeln!(out, "    int64_t id;")?;
        writeln!(out, "    MimiHandle(int64_t i = 0) : id(i) {{}}")?;
        writeln!(out, "    bool operator==(const MimiHandle& o) const {{ return id == o.id; }}")?;
        writeln!(out, "    bool operator!=(const MimiHandle& o) const {{ return id != o.id; }}")?;
        writeln!(out, "}};")?;
        writeln!(out)?;

        // MimiCap — opaque capability token
        writeln!(out, "class MimiCap {{")?;
        writeln!(out, "public:")?;
        writeln!(out, "    int64_t id;")?;
        writeln!(out, "    MimiCap(int64_t i = 0) : id(i) {{}}")?;
        writeln!(out, "}};")?;
        writeln!(out)?;

        Ok(())
    }

    fn write_module_def(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "PYBIND11_MODULE({}, m) {{", self.module_name)?;
        writeln!(out, "    m.doc() = \"Mimi language FFI bindings (auto-generated)\";")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_function(&self, out: &mut String, func: &ExternFunc) -> Result<(), std::fmt::Error> {
        let contract = FfiContract::from_extern(func);
        let ret_cpp = self.contract_ret_to_cpp(&contract);
        let func_name = &func.name;

        // Build parameter list for the lambda
        let mut param_decls = Vec::new();
        for (i, param) in func.params.iter().enumerate() {
            let cpp_type = self.contract_arg_to_cpp(&contract, i);
            param_decls.push(format!("{} {}", cpp_type, param.name));
        }

        writeln!(out, "    // {} — {}", func_name, func.name)?;
        writeln!(out, "    m.def(\"{}\", []({}) -> {} {{", func_name, param_decls.join(", "), ret_cpp)?;

        // Build native call arguments
        let native_args: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, param)| self.arg_to_native(&contract, i, param))
            .collect();
        let ret_expr = self.ret_to_native(&contract, func_name);

        if matches!(contract.ret, crate::ffi::contract::FfiRetContract::Unit) {
            writeln!(out, "        {}({});", func_name, native_args.join(", "))?;
            writeln!(out, "        return py::none();")?;
        } else {
            writeln!(out, "        return {};", ret_expr)?;
        }

        writeln!(out, "    }}, \"{}\"", func.name)?;

        if let Some(requires) = &func.requires {
            writeln!(out, "        .doc(\"Requires: {:?}\")", requires)?;
        }
        if let Some(ensures) = &func.ensures {
            writeln!(out, "        .doc(\"Ensures: {:?}\")", ensures)?;
        }

        writeln!(out, "    );")?;
        writeln!(out)?;
        Ok(())
    }

    fn write_module_init(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        writeln!(out, "}}")?;
        writeln!(out)?;
        writeln!(out, "#endif // {}", format!("MIMI_PY_BIND_{}_H", self.module_name.to_uppercase().replace(|c: char| !c.is_ascii_alphanumeric(), "_")))?;
        Ok(())
    }

    // ---- Type mapping helpers ----

    fn mimi_type_to_cpp(&self, ty: &Type) -> String {
        match ty {
            Type::Name(name, _) => match name.as_str() {
                "i32" | "i64" => "int64_t".to_string(),
                "f64" => "double".to_string(),
                "bool" => "bool".to_string(),
                "string" => "std::string".to_string(),
                "unit" | "nothing" => "void".to_string(),
                _ => {
                    if self.type_defs.contains_key(name) {
                        name.clone()
                    } else {
                        "void*".to_string()
                    }
                }
            },
            Type::RawPtr(inner) | Type::RawPtrMut(inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("{}*", inner)
            }
            Type::CShared(_) | Type::CBorrow(_) | Type::CBorrowMut(_) => "MimiHandle".to_string(),
            Type::Cap(_) => "MimiCap".to_string(),
            Type::RawString => "char*".to_string(),
            Type::Shared(inner) | Type::LocalShared(inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("MimiHandle /* shared {} */", inner)
            }
            Type::Ref(_, inner) | Type::RefMut(_, inner) => {
                let inner = self.mimi_type_to_cpp(inner);
                format!("{}*", inner)
            }
            _ => "void*".to_string(),
        }
    }

    fn contract_arg_to_cpp(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "void*".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "int64_t".to_string(),
            FfiArgContract::Float => "double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => {
                "const std::string&".to_string()
            }
            FfiArgContract::Cap(_) => "MimiCap".to_string(),
            FfiArgContract::RawPtr(inner) | FfiArgContract::RawPtrMut(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            FfiArgContract::CShared(inner) | FfiArgContract::CBorrow(inner) | FfiArgContract::CBorrowMut(inner) => {
                format!("MimiHandle /* {} */", self.mimi_type_to_cpp(inner))
            }
            FfiArgContract::Json => "const std::string&".to_string(),
            FfiArgContract::Callback { .. } => "py::function".to_string(),
            FfiArgContract::Unsupported(_) => "py::object".to_string(),
        }
    }

    fn contract_ret_to_cpp(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "void".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "int64_t".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "double".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned
            | crate::ffi::contract::FfiRetContract::Json => "std::string".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::RawPtrMut(inner) => {
                format!("{}*", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::CShared(inner)
            | crate::ffi::contract::FfiRetContract::CBorrow(inner)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(inner) => {
                format!("MimiHandle /* {} */", self.mimi_type_to_cpp(inner))
            }
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "py::object".to_string(),
        }
    }

    fn arg_to_native(&self, contract: &FfiContract, index: usize, param: &crate::ast::ExternParam) -> String {
        if index >= contract.args.len() {
            return "0".to_string();
        }
        let name = &param.name;
        match &contract.args[index] {
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer | FfiArgContract::Json => {
                format!("{}.c_str()", name)
            }
            FfiArgContract::Callback { .. } => {
                format!("{}.cast<py::function>()", name)
            }
            _ => name.clone(),
        }
    }

    fn ret_to_native(&self, contract: &FfiContract, func_name: &str) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => format!("{}(), py::none()", func_name),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => {
                format!("std::string({}())", func_name)
            }
            crate::ffi::contract::FfiRetContract::Json => {
                format!("std::string({}())", func_name)
            }
            _ => format!("{}()", func_name),
        }
    }
}

fn func_param_name(index: usize) -> String {
    format!("arg{}", index)
}

/// Generate a CMakeLists.txt snippet for building the Python extension.
pub fn generate_cmake_snippet(module_name: &str, header_path: &str, lib_path: &str) -> String {
    format!(
r#"cmake_minimum_required(VERSION 3.14)
project({module_name}_bindings LANGUAGES CXX)

find_package(pybind11 REQUIRED)
find_library(MIMI_RUNTIME_LIB NAMES mimi_runtime PATHS "{lib_path}")

pybind11_add_module({module_name} bindings.cpp)
target_include_directories({module_name} PRIVATE "{header_path}")
target_link_libraries({module_name} PRIVATE ${{MIMI_RUNTIME_LIB}})
set_target_properties({module_name} PROPERTIES
    CXX_STANDARD 17
    CXX_STANDARD_REQUIRED ON
)
"#,
        module_name = module_name,
        header_path = header_path,
        lib_path = lib_path,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{ExternFunc, ExternParam, Type};

    fn sample_funcs() -> Vec<ExternFunc> {
        vec![
            ExternFunc {
                name: "mimi_add".to_string(),
                params: vec![
                    ExternParam { name: "a".to_string(), ty: Type::Name("i64".into(), Vec::new()), cap_mode: None },
                    ExternParam { name: "b".to_string(), ty: Type::Name("i64".into(), Vec::new()), cap_mode: None },
                ],
                ret: Some(Type::Name("i64".into(), Vec::new())),
                requires: None,
                ensures: None,
            },
            ExternFunc {
                name: "mimi_greet".to_string(),
                params: vec![
                    ExternParam { name: "name".to_string(), ty: Type::Name("string".into(), Vec::new()), cap_mode: None },
                ],
                ret: None,
                requires: None,
                ensures: None,
            },
        ]
    }

    #[test]
    fn test_py_bind_generator_basic() {
        let funcs = sample_funcs();
        let type_defs = HashMap::new();
        let gen = PyBindGenerator::new(type_defs, "mimi_test");
        let code = gen.generate(&funcs).unwrap();

        assert!(code.contains("PYBIND11_MODULE"));
        assert!(code.contains("mimi_add"));
        assert!(code.contains("mimi_greet"));
        assert!(code.contains("int64_t"));
        assert!(code.contains("std::string"));
        assert!(code.contains("m.def"));
    }

    #[test]
    fn test_py_bind_generator_contains_cpp_types() {
        let funcs = sample_funcs();
        let type_defs = HashMap::new();
        let gen = PyBindGenerator::new(type_defs, "test_mod");
        let code = gen.generate(&funcs).unwrap();

        assert!(code.contains("#include <pybind11/pybind11.h>"));
        assert!(code.contains("#include \"mimi_ffi.h\""));
        assert!(code.contains("class MimiHandle"));
        assert!(code.contains("class MimiCap"));
    }

    #[test]
    fn test_cmake_snippet() {
        let cmake = generate_cmake_snippet("my_mod", "/usr/local/include/mimi", "/usr/local/lib");
        assert!(cmake.contains("pybind11_add_module(my_mod"));
        assert!(cmake.contains("find_package(pybind11 REQUIRED)"));
        assert!(cmake.contains("CXX_STANDARD 17"));
    }
}
