//! Rust FFI binding generator from Mimi extern declarations.
//!
//! Generates a `.rs` file with `extern "C"` blocks that can call Mimi functions
//! through the shared library.
//!
//! Usage:
//!   mimi emit-rust-bindings path/to/pkg.mimi -o bindings.rs

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, TypeDef};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Rust binding generator — produces a `.rs` file with extern "C" declarations.
pub struct RustBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl RustBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete Rust FFI bindings source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(out, "// Module: {}", self.module_name)?;
        writeln!(out, "// Do not edit manually.")?;
        writeln!(out)?;
        writeln!(out, "use std::ffi::{{c_char, c_double, c_int, c_longlong, c_void}};")?;
        writeln!(out, "use std::ptr;")?;
        writeln!(out)?;

        // Generate opaque handle types for records
        let record_names: Vec<&String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name)
            .collect();
        if !record_names.is_empty() {
            writeln!(out, "// Opaque handle types for Mimi records")?;
            for name in &record_names {
                writeln!(out, "#[repr(C)]")?;
                writeln!(out, "pub struct Mimi{}(c_void);", name)?;
            }
            writeln!(out)?;
        }

        writeln!(out, "extern \"C\" {{")?;

        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_function(&mut out, func, &contract)?;
        }

        writeln!(out, "}}")?;
        writeln!(out)?;

        // Generate safe wrapper functions
        writeln!(out, "// Safe wrapper functions")?;
        writeln!(out, "#[allow(dead_code)]")?;
        writeln!(out, "mod wrappers {{")?;
        writeln!(out, "    use super::*;")?;
        writeln!(out)?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_safe_wrapper(&mut out, func, &contract)?;
        }
        writeln!(out, "}}")?;
        writeln!(out, "pub use wrappers::*;")?;

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, crate::ast::TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&crate::ast::TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    fn write_function(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| format!("{}: {}", p.name, self.mimi_type_to_rust(contract, i)))
            .collect();
        let ret = self.ret_type_to_rust(contract);
        writeln!(out, "    pub fn {}({}) -> {};", func.name, params.join(", "), ret)
    }

    fn write_safe_wrapper(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                let rust_ty = self.mimi_type_to_rust_safe(contract, i);
                format!("{}: {}", p.name, rust_ty)
            })
            .collect();
        let ret = self.ret_type_to_rust_safe(contract);

        // For string parameters, convert &str to *const c_char
        let mut conversions = String::new();
        let mut call_args = Vec::new();
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => {
                    writeln!(conversions, "        let {}_cstr = std::ffi::CString::new({}).unwrap();", p.name, p.name)?;
                    writeln!(conversions, "        let {}_ptr = {}_cstr.as_ptr();", p.name, p.name)?;
                    call_args.push(format!("{}_ptr", p.name));
                }
                _ => {
                    call_args.push(p.name.clone());
                }
            }
        }

        writeln!(out, "    pub fn {}({}) -> {} {{", func.name, params.join(", "), ret)?;
        write!(out, "{}", conversions)?;
        writeln!(out, "        unsafe {{ crate::{}({}) }}", func.name, call_args.join(", "))?;
        writeln!(out, "    }}")?;
        writeln!(out)
    }

    fn mimi_type_to_rust(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "*const c_void".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "c_longlong".to_string(),
            FfiArgContract::Float => "c_double".to_string(),
            FfiArgContract::StringBorrow | FfiArgContract::StringTransfer => "*const c_char".to_string(),
            FfiArgContract::Cap(_) => "c_longlong".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "*mut c_void".to_string(),
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "c_longlong".to_string(),
            FfiArgContract::Json => "*const c_char".to_string(),
            FfiArgContract::StructByValue(name) => format!("*mut Mimi{}", name),
            FfiArgContract::Callback { .. } => "*const c_void".to_string(),
            FfiArgContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    fn mimi_type_to_rust_safe(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "*const c_void".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int => "i64".to_string(),
            FfiArgContract::Float => "f64".to_string(),
            FfiArgContract::StringBorrow => "&str".to_string(),
            FfiArgContract::StringTransfer => "String".to_string(),
            FfiArgContract::Cap(_) => "i64".to_string(),
            FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_) => "*mut c_void".to_string(),
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "i64".to_string(),
            FfiArgContract::Json => "&str".to_string(),
            FfiArgContract::StructByValue(name) => format!("*mut Mimi{}", name),
            FfiArgContract::Callback { .. } => "*const c_void".to_string(),
            FfiArgContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    fn ret_type_to_rust(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "()".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "c_longlong".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "c_double".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "*mut c_char".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "*mut c_void".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "c_longlong".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "*mut c_char".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("*mut Mimi{}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    fn ret_type_to_rust_safe(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "()".to_string(),
            crate::ffi::contract::FfiRetContract::Int => "i64".to_string(),
            crate::ffi::contract::FfiRetContract::Float => "f64".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "String".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(_)
            | crate::ffi::contract::FfiRetContract::RawPtrMut(_) => "*mut c_void".to_string(),
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "i64".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "String".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("*mut Mimi{}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }
}
