//! Rust FFI binding generator from Mimi extern declarations.
//!
//! Generates a `.rs` file with `extern "C"` blocks that can call Mimi functions
//! through the shared library.
//!
//! Usage:
//!   mimi emit-rust-bindings path/to/pkg.mimi -o bindings.rs

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::{ExternFunc, Type, TypeAttribute, TypeDef, TypeDefKind};
use crate::ffi::contract::{FfiArgContract, FfiContract};

/// Rust binding generator — produces a `.rs` file with extern "C" declarations.
pub struct RustBindGenerator {
    type_defs: HashMap<String, TypeDef>,
    module_name: String,
}

impl RustBindGenerator {
    pub fn new(type_defs: HashMap<String, TypeDef>, module_name: &str) -> Self {
        Self {
            type_defs,
            module_name: module_name.to_string(),
        }
    }

    /// Generate the complete Rust FFI bindings source.
    pub fn generate(&self, extern_funcs: &[ExternFunc]) -> Result<String, std::fmt::Error> {
        let mut out = String::new();

        writeln!(out, "// Auto-generated by Mimi FFI binding generator")?;
        writeln!(
            out,
            "// Module: {}",
            sanitize_rust_comment(&self.module_name)
        )?;
        writeln!(out, "// Do not edit manually.")?;
        writeln!(out)?;
        writeln!(
            out,
            "use std::ffi::{{c_char, c_double, c_int, c_longlong, c_void}};"
        )?;
        writeln!(out)?;

        // Generate type definitions
        self.write_type_definitions(&mut out)?;

        // Raw extern declarations are scoped so safe wrappers can use the same names.
        writeln!(out, "mod ffi_raw {{")?;
        writeln!(out, "    use super::*;")?;
        writeln!(out, "    extern \"C\" {{")?;
        writeln!(
            out,
            "        // Mimi runtime helpers referenced by generated wrappers"
        )?;
        writeln!(out, "        pub fn mimi_string_free(c_str: *mut c_char);")?;
        // FFI-01 (audit 2026-08-20): `StringTransfer` wrappers allocate a
        // libc-malloc'd buffer via `super::ffi_raw::malloc`, but `malloc` was
        // never declared in this extern block, so the generated Rust binding
        // failed to compile. Declare `malloc`/`free` here (they resolve to the
        // system libc and match the C-side `libc::free` deallocation contract).
        writeln!(out, "        pub fn malloc(size: usize) -> *mut c_void;")?;
        writeln!(out, "        pub fn free(ptr: *mut c_void);")?;
        writeln!(out)?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_function(&mut out, func, &contract)?;
        }
        writeln!(out, "    }}")?;
        writeln!(out, "}}")?;
        writeln!(out)?;

        // Generate safe wrapper functions
        writeln!(out, "// Safe wrapper functions")?;
        writeln!(out, "#[allow(dead_code)]")?;
        writeln!(out, "mod wrappers {{")?;
        writeln!(out, "    use super::*;")?;
        writeln!(out)?;
        for func in extern_funcs {
            let contract = self.build_contract(func);
            self.write_safe_wrapper(&mut out, func, &contract)?;
        }
        writeln!(out, "}}")?;
        writeln!(out, "pub use wrappers::*;")?;

        Ok(out)
    }

    fn build_contract(&self, func: &ExternFunc) -> FfiContract {
        let record_type_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| matches!(td.kind, TypeDefKind::Record(_)))
            .map(|(name, _)| name.clone())
            .collect();
        let repr_c_record_names: std::collections::HashSet<String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .map(|(name, _)| name.clone())
            .collect();
        FfiContract::from_extern_with_caps_repr(
            func,
            &std::collections::HashSet::new(),
            &record_type_names,
            &repr_c_record_names,
        )
    }

    /// Generate Rust type definitions for #[repr(C)] records (as real structs)
    /// and non-repr(C) records (as opaque handles).
    fn write_type_definitions(&self, out: &mut String) -> Result<(), std::fmt::Error> {
        let mut repr_c: Vec<(&String, &TypeDef)> = self
            .type_defs
            .iter()
            .filter(|(_, td)| td.attributes.contains(&TypeAttribute::ReprC))
            .collect();
        repr_c.sort_by_key(|(name, _)| *name);

        if !repr_c.is_empty() {
            writeln!(out, "// #[repr(C)] structs (layout-compatible with C)")?;
            for (name, td) in repr_c {
                if let TypeDefKind::Record(fields) = &td.kind {
                    writeln!(out, "#[repr(C)]")?;
                    writeln!(out, "#[derive(Debug, Clone, Copy)]")?;
                    writeln!(out, "pub struct Mimi{} {{", name)?;
                    for field in fields {
                        let rust_ty = self.mimi_type_to_rust_field(&field.ty);
                        writeln!(out, "    pub {}: {},", field.name, rust_ty)?;
                    }
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }
            }
        }

        // Opaque handles for non-#[repr(C)] records
        let opaque: Vec<&String> = self
            .type_defs
            .iter()
            .filter(|(_, td)| {
                matches!(td.kind, TypeDefKind::Record(_))
                    && !td.attributes.contains(&TypeAttribute::ReprC)
            })
            .map(|(name, _)| name)
            .collect();
        if !opaque.is_empty() {
            writeln!(
                out,
                "// Opaque handle types for non-#[repr(C)] Mimi records"
            )?;
            for name in opaque {
                writeln!(out, "#[repr(C)]")?;
                writeln!(out, "pub struct Mimi{}(c_void);", name)?;
            }
            writeln!(out)?;
        }

        Ok(())
    }

    fn write_function(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| format!("{}: {}", p.name, self.mimi_type_to_rust(contract, i)))
            .collect();
        let ret = self.ret_type_to_rust(contract);
        writeln!(
            out,
            "    pub fn {}({}) -> {};",
            func.name,
            params.join(", "),
            ret
        )
    }

    fn write_safe_wrapper(
        &self,
        out: &mut String,
        func: &ExternFunc,
        contract: &FfiContract,
    ) -> Result<(), std::fmt::Error> {
        let params: Vec<String> = func
            .params
            .iter()
            .enumerate()
            .map(|(i, p)| {
                let rust_ty = self.mimi_type_to_rust_safe(contract, i);
                format!("{}: {}", p.name, rust_ty)
            })
            .collect();
        let ret = self.ret_type_to_rust_safe(contract);

        // For string parameters, convert &str to *const c_char (borrow) or
        // hand over a heap pointer to C (transfer).
        let mut conversions = String::new();
        let mut call_args = Vec::new();
        for (i, p) in func.params.iter().enumerate() {
            match &contract.args[i] {
                FfiArgContract::StringBorrow => {
                    // Avoid panicking on embedded NUL bytes (P2-3): filter them
                    // out for the C-string borrow, mirroring StringTransfer.
                    writeln!(
                        conversions,
                        "        let {}_cstr = std::ffi::CString::new({}.bytes().filter(|&b| b != 0).collect::<Vec<_>>()).unwrap();",
                        p.name, p.name
                    )?;
                    writeln!(
                        conversions,
                        "        let {}_ptr = {}_cstr.as_ptr();",
                        p.name, p.name
                    )?;
                    call_args.push(format!("{}_ptr", p.name));
                }
                FfiArgContract::StringTransfer => {
                    // Ownership transfers TO C (FfiArgContract::StringTransfer):
                    // hand over a libc malloc-allocated buffer and do NOT free
                    // it after the call — C is now the owner and must free it
                    // with mimi_string_free_raw (which is libc::free). The old
                    // CString::into_raw path used the Rust global allocator,
                    // mismatch-prone with C-side free contracts.
                    // Interior NUL bytes are filtered first, mirroring the
                    // interpreter reference behavior (interp/ffi_runtime.rs
                    // StringTransfer arm).
                    writeln!(
                        conversions,
                        "        let {n}_bytes: Vec<u8> = {n}.bytes().filter(|&b| b != 0).collect();",
                        n = p.name
                    )?;
                    writeln!(
                        conversions,
                        "        let {n}_len = {n}_bytes.len();",
                        n = p.name
                    )?;
                    writeln!(
                        conversions,
                        "        let {n}_raw = unsafe {{ super::ffi_raw::malloc({n}_len + 1) }} as *mut c_char;",
                        n = p.name
                    )?;
                    writeln!(
                        conversions,
                        "        if {n}_raw.is_null() {{ panic!(\"out of memory for StringTransfer argument\") }}",
                        n = p.name
                    )?;
                    writeln!(conversions, "        unsafe {{",)?;
                    writeln!(
                        conversions,
                        "            std::ptr::copy_nonoverlapping({n}_bytes.as_ptr(), {n}_raw as *mut u8, {n}_len);",
                        n = p.name
                    )?;
                    writeln!(
                        conversions,
                        "            *{n}_raw.add({n}_len) = 0;",
                        n = p.name
                    )?;
                    writeln!(conversions, "        }}")?;
                    writeln!(
                        conversions,
                        "        // Ownership transferred to C (StringTransfer contract); must NOT be freed here."
                    )?;
                    writeln!(conversions, "        let {n}_ptr = {n}_raw;", n = p.name)?;
                    call_args.push(format!("{}_ptr", p.name));
                }
                _ => {
                    call_args.push(p.name.clone());
                }
            }
        }

        let is_unsafe = contract
            .args
            .iter()
            .any(|a| matches!(a, FfiArgContract::RawPtr(_) | FfiArgContract::RawPtrMut(_)))
            || matches!(
                contract.ret,
                crate::ffi::contract::FfiRetContract::RawPtr(_)
                    | crate::ffi::contract::FfiRetContract::RawPtrMut(_)
            );
        let fn_decl = if is_unsafe { "pub unsafe fn" } else { "pub fn" };
        writeln!(
            out,
            "    {} {}({}) -> {} {{",
            fn_decl,
            func.name,
            params.join(", "),
            ret
        )?;
        write!(out, "{}", conversions)?;
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::String => {
                // BORROWED from C (FfiRetContract::String): copy into an owned
                // String but do NOT free the C pointer — C retains ownership.
                // Freeing it here corrupted the C heap (the interpreter
                // reference behavior warns instead of freeing:
                // interp/ffi_runtime.rs ffi_ret_to_value).
                writeln!(
                    out,
                    "        let raw = unsafe {{ super::ffi_raw::{}({}) }};",
                    func.name,
                    call_args.join(", ")
                )?;
                writeln!(out, "        if raw.is_null() {{ return String::new(); }}")?;
                writeln!(
                    out,
                    "        // Borrowed from C: copy, do NOT free (FfiRetContract::String)."
                )?;
                writeln!(out, "        unsafe {{ std::ffi::CStr::from_ptr(raw).to_string_lossy().into_owned() }}")?;
            }
            crate::ffi::contract::FfiRetContract::StringOwned
            | crate::ffi::contract::FfiRetContract::Json => {
                // OWNED: copy, then free the C pointer with the documented
                // runtime deallocator (mimi_string_free == libc::free).
                writeln!(
                    out,
                    "        let raw = unsafe {{ super::ffi_raw::{}({}) }};",
                    func.name,
                    call_args.join(", ")
                )?;
                writeln!(out, "        if raw.is_null() {{ return String::new(); }}")?;
                writeln!(out, "        let s = unsafe {{ std::ffi::CStr::from_ptr(raw).to_string_lossy().into_owned() }};")?;
                writeln!(out, "        // Owned by Mimi (StringOwned/Json contract): free with the runtime deallocator.")?;
                writeln!(
                    out,
                    "        unsafe {{ super::ffi_raw::mimi_string_free(raw) }};"
                )?;
                writeln!(out, "        s")?;
            }
            _ => {
                writeln!(
                    out,
                    "        unsafe {{ super::ffi_raw::{}({}) }}",
                    func.name,
                    call_args.join(", ")
                )?;
            }
        }
        writeln!(out, "    }}")?;
        writeln!(out)
    }

    fn mimi_type_to_rust(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "*const c_void".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "c_int".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "c_longlong".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            FfiArgContract::Float => "c_double".to_string(),
            FfiArgContract::StringBorrow => "*const c_char".to_string(),
            // Ownership transfers to C, which must free it — declare the owned
            // pointer as mutable to match the C header (`char*`).
            FfiArgContract::StringTransfer => "*mut c_char".to_string(),
            FfiArgContract::Cap(_) => "c_longlong".to_string(),
            FfiArgContract::RawPtr(inner) => {
                format!("*const {}", self.mimi_type_to_rust_field(inner))
            }
            FfiArgContract::RawPtrMut(inner) => {
                format!("*mut {}", self.mimi_type_to_rust_field(inner))
            }
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "c_longlong".to_string(),
            FfiArgContract::Json => "*const c_char".to_string(),
            FfiArgContract::StructByValue(name) => format!("Mimi{}", name),
            FfiArgContract::Callback {
                param_types,
                ret_type,
            } => self.callback_signature_to_rust(param_types, ret_type),
            FfiArgContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    fn mimi_type_to_rust_safe(&self, contract: &FfiContract, index: usize) -> String {
        if index >= contract.args.len() {
            return "*const c_void".to_string();
        }
        match &contract.args[index] {
            FfiArgContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "i32".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "i64".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            FfiArgContract::Float => "f64".to_string(),
            FfiArgContract::StringBorrow => "&str".to_string(),
            FfiArgContract::StringTransfer => "String".to_string(),
            FfiArgContract::Cap(_) => "i64".to_string(),
            FfiArgContract::RawPtr(inner) => {
                format!("*const {}", self.mimi_type_to_rust_field(inner))
            }
            FfiArgContract::RawPtrMut(inner) => {
                format!("*mut {}", self.mimi_type_to_rust_field(inner))
            }
            FfiArgContract::CShared(_)
            | FfiArgContract::CBorrow(_)
            | FfiArgContract::CBorrowMut(_) => "i64".to_string(),
            FfiArgContract::Json => "&str".to_string(),
            FfiArgContract::StructByValue(name) => format!("Mimi{}", name),
            FfiArgContract::Callback {
                param_types,
                ret_type,
            } => self.callback_signature_to_rust(param_types, ret_type),
            FfiArgContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    /// Build a C function-pointer type string from Mimi callback parameter/return types.
    fn callback_signature_to_rust(&self, param_types: &[Type], ret_type: &Type) -> String {
        // Match the original Mimi scalar widths in the extern "C" function-pointer ABI.
        let arg_types: Vec<String> = param_types
            .iter()
            .map(|ty| match ty.unlocated() {
                Type::Name(name, _) if name == "i32" => "i32".to_string(),
                Type::Name(name, _) if name == "i64" => "i64".to_string(),
                Type::Name(name, _) if name == "f64" => "f64".to_string(),
                Type::Name(name, _) if name == "bool" => "bool".to_string(),
                _ => "c_longlong".to_string(),
            })
            .collect();
        let ret = match ret_type.unlocated() {
            Type::Name(name, _) if name == "i32" => "i32".to_string(),
            Type::Name(name, _) if name == "i64" => "i64".to_string(),
            Type::Name(name, _) if name == "f64" => "f64".to_string(),
            Type::Name(name, _) if name == "bool" => "bool".to_string(),
            Type::Name(name, _) if name == "unit" => "()".to_string(),
            _ => "c_longlong".to_string(),
        };
        format!(
            "unsafe extern \"C\" fn({}) -> {}",
            arg_types.join(", "),
            ret
        )
    }

    fn ret_type_to_rust(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "()".to_string(),
            crate::ffi::contract::FfiRetContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "c_int".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "c_longlong".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            crate::ffi::contract::FfiRetContract::Float => "c_double".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "*mut c_char".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(inner) => {
                format!("*const {}", self.mimi_type_to_rust_field(inner))
            }
            crate::ffi::contract::FfiRetContract::RawPtrMut(inner) => {
                format!("*mut {}", self.mimi_type_to_rust_field(inner))
            }
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "c_longlong".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "*mut c_char".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("Mimi{}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    fn ret_type_to_rust_safe(&self, contract: &FfiContract) -> String {
        match &contract.ret {
            crate::ffi::contract::FfiRetContract::Unit => "()".to_string(),
            crate::ffi::contract::FfiRetContract::Int(scalar) => match scalar {
                crate::ffi::contract::FfiScalarType::I32 => "i32".to_string(),
                crate::ffi::contract::FfiScalarType::I64 => "i64".to_string(),
                crate::ffi::contract::FfiScalarType::Bool => "bool".to_string(),
            },
            crate::ffi::contract::FfiRetContract::Float => "f64".to_string(),
            crate::ffi::contract::FfiRetContract::String
            | crate::ffi::contract::FfiRetContract::StringOwned => "String".to_string(),
            crate::ffi::contract::FfiRetContract::RawPtr(inner) => {
                format!("*const {}", self.mimi_type_to_rust_field(inner))
            }
            crate::ffi::contract::FfiRetContract::RawPtrMut(inner) => {
                format!("*mut {}", self.mimi_type_to_rust_field(inner))
            }
            crate::ffi::contract::FfiRetContract::CShared(_)
            | crate::ffi::contract::FfiRetContract::CBorrow(_)
            | crate::ffi::contract::FfiRetContract::CBorrowMut(_) => "i64".to_string(),
            crate::ffi::contract::FfiRetContract::Json => "String".to_string(),
            crate::ffi::contract::FfiRetContract::StructByValue(name) => format!("Mimi{}", name),
            crate::ffi::contract::FfiRetContract::Unsupported(_) => "*const c_void".to_string(),
        }
    }

    /// Map a Mimi type used inside a #[repr(C)] record field to a Rust type.
    fn mimi_type_to_rust_field(&self, ty: &Type) -> String {
        match ty.unlocated() {
            Type::Name(name, _) => match name.as_str() {
                "i32" => "i32".to_string(),
                "i64" => "i64".to_string(),
                "f64" => "f64".to_string(),
                "bool" => "bool".to_string(),
                other => {
                    if self.is_repr_c_record(other) {
                        format!("Mimi{}", other)
                    } else {
                        "c_void".to_string()
                    }
                }
            },
            _ => "c_void".to_string(),
        }
    }

    fn is_repr_c_record(&self, name: &str) -> bool {
        self.type_defs
            .get(name)
            .map(|td| {
                matches!(td.kind, TypeDefKind::Record(_))
                    && td.attributes.contains(&TypeAttribute::ReprC)
            })
            .unwrap_or(false)
    }
}

/// Make a value safe to embed in a generated Rust comment.
fn sanitize_rust_comment(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c == '\n' || c == '\r' || c == '\t' {
                ' '
            } else {
                c
            }
        })
        .collect()
}
