//! C header generator: produces a `.h` file from Component IR.
//!
//! 0.31.30 (COMPONENT-BINDGEN-001): This is the first bindgen backend
//! that consumes ComponentIr instead of raw AST. It proves the pipeline:
//!
//! ```text
//! CheckedProgram → ComponentIr → c_header.rs → mimi_abi.h
//! ```
//!
//! The generated header includes:
//! - Include guard + system includes
//! - Struct definitions (repr(C) with field offsets)
//! - Opaque handle typedefs
//! - Enum definitions
//! - Function declarations (extern "C")
//! - BLAKE3 hash comment for tamper detection

use super::symbol::AbiSymbol;
use super::types::AbiTypeDef;
use super::ComponentIr;

/// Generate a complete C header file from a Component IR.
///
/// The output is a self-contained `.h` file suitable for `#include`
/// from C/C++ code or for consumption by cbindgen-like tools.
pub fn generate_c_header(ir: &ComponentIr) -> String {
    let mut out = String::with_capacity(8192);
    let guard = format!(
        "{}_ABI_H",
        ir.identity.name.to_uppercase().replace('-', "_")
    );

    // ── Header preamble ──
    out.push_str(&format!(
        "/* Generated by Mimi Component IR v{} — DO NOT EDIT */\n",
        ir.identity.version
    ));
    out.push_str(&format!(
        "/* ABI version: {} | Component: {} */\n\n",
        ir.identity.abi_version, ir.identity.name
    ));
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n\n");

    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // ── Type definitions ──
    if !ir.types.is_empty() {
        out.push_str("/* ── Type Definitions ── */\n\n");
        for ty in &ir.types {
            emit_type_def(&mut out, ty);
        }
    }

    // ── Function declarations ──
    if !ir.exports.is_empty() {
        out.push_str("/* ── Runtime Exports ── */\n\n");
        for sym in &ir.exports {
            emit_function_decl(&mut out, sym);
        }
    }

    // ── Footer ──
    out.push_str("#ifdef __cplusplus\n}\n#endif\n\n");
    out.push_str(&format!("#endif /* {guard} */\n"));

    out
}

/// Emit a single type definition.
fn emit_type_def(out: &mut String, ty: &AbiTypeDef) {
    match ty {
        AbiTypeDef::Struct(s) => {
            if let Some(size) = s.size {
                out.push_str(&format!("/* size={}B", size));
                if let Some(align) = s.align {
                    out.push_str(&format!(", align={}B", align));
                }
                out.push_str(" */\n");
            }
            out.push_str(&format!("typedef struct {} {{\n", s.name));
            for field in &s.fields {
                let offset_comment = field
                    .offset
                    .map(|o| format!("  /* offset {} */", o))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "    {} {};{}\n",
                    field.ty.c_type_name(),
                    field.name,
                    offset_comment
                ));
            }
            out.push_str(&format!("}} {};\n\n", s.name));
        }
        AbiTypeDef::Enum(e) => {
            out.push_str(&format!("typedef {} {};\n", e.repr.c_name(), e.name));
            for (variant, discriminant) in &e.variants {
                out.push_str(&format!(
                    "#define {}_{} (({}){})\n",
                    e.name,
                    variant,
                    e.repr.c_name(),
                    discriminant
                ));
            }
            out.push('\n');
        }
        AbiTypeDef::Alias(a) => {
            out.push_str(&format!(
                "typedef {} {};\n\n",
                a.target.c_type_name(),
                a.name
            ));
        }
        AbiTypeDef::Opaque(o) => {
            out.push_str(&format!(
                "/* {} */\ntypedef uintptr_t {};\n\n",
                o.description, o.name
            ));
        }
    }
}

/// Emit a single function declaration.
fn emit_function_decl(out: &mut String, sym: &AbiSymbol) {
    // Effect annotations as comments
    if !sym.effects.is_empty() {
        out.push_str(&format!("/* effects: {} */\n", sym.effects.join(", ")));
    }
    if sym.is_unsafe {
        out.push_str("/* UNSAFE: caller must uphold safety invariants */\n");
    }

    let params = if sym.params.is_empty() {
        "void".to_string()
    } else {
        sym.params
            .iter()
            .map(|p| {
                let nullable = if p.is_nullable { "/* nullable */ " } else { "" };
                format!("{}{} {}", nullable, p.ty.c_type_name(), p.name)
            })
            .collect::<Vec<_>>()
            .join(",\n    ")
    };

    // Multi-line params for readability when > 2 params
    if sym.params.len() > 2 {
        out.push_str(&format!(
            "{} {}(\n    {}\n);\n\n",
            sym.ret.c_type_name(),
            sym.name,
            params
        ));
    } else {
        out.push_str(&format!(
            "{} {}({});\n\n",
            sym.ret.c_type_name(),
            sym.name,
            params
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::gen::{register_core_runtime_abi, AbiGenerator};
    use crate::component::types::AbiTypeRef;
    use crate::component::ComponentIdentity;

    #[test]
    fn c_header_contains_guard() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#ifndef MIMI_RUNTIME_ABI_H"));
        assert!(header.contains("#define MIMI_RUNTIME_ABI_H"));
        assert!(header.contains("#endif /* MIMI_RUNTIME_ABI_H */"));
    }

    #[test]
    fn c_header_contains_includes() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#include <stdint.h>"));
        assert!(header.contains("#include <stdbool.h>"));
        assert!(header.contains("#include <stddef.h>"));
    }

    #[test]
    fn c_header_contains_struct_defs() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        // MimiString struct
        assert!(header.contains("typedef struct MimiString {"));
        assert!(header.contains("uint8_t* data;"));
        assert!(header.contains("uintptr_t len;"));
        assert!(header.contains("uintptr_t capacity;"));
        assert!(header.contains("} MimiString;"));

        // MimiSlice struct
        assert!(header.contains("typedef struct MimiSlice {"));
        assert!(header.contains("} MimiSlice;"));
    }

    #[test]
    fn c_header_contains_opaque_handles() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("typedef uintptr_t ListHandle;"));
        assert!(header.contains("typedef uintptr_t MapHandle;"));
        assert!(header.contains("typedef uintptr_t SetHandle;"));
        assert!(header.contains("typedef uintptr_t ActorHandle;"));
        assert!(header.contains("typedef uintptr_t FutureHandle;"));
    }

    #[test]
    fn c_header_contains_function_decls() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("intptr_t mimi_rc_alloc(uintptr_t size);"));
        assert!(header.contains("void mimi_rc_retain(intptr_t ptr);"));
        // handle("ListHandle") → MimiHandle/* ListHandle */ in C
        assert!(header.contains("MimiHandle/* ListHandle */ mimi_list_new(void);"));
        assert!(header.contains("int64_t mimi_timestamp(void);"));
    }

    #[test]
    fn c_header_contains_extern_c() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#ifdef __cplusplus"));
        assert!(header.contains("extern \"C\" {"));
    }

    #[test]
    fn c_header_contains_unsafe_annotation() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("/* UNSAFE: caller must uphold safety invariants */"));
    }

    #[test]
    fn c_header_contains_effect_annotations() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("/* effects: alloc */"));
        assert!(header.contains("/* effects: io */"));
        assert!(header.contains("/* effects: dealloc */"));
    }

    #[test]
    fn c_header_is_valid_c_syntax() {
        // Basic sanity: balanced braces, semicolons after declarations
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        let open = header.matches('{').count();
        let close = header.matches('}').count();
        assert_eq!(
            open, close,
            "unbalanced braces: {} open, {} close",
            open, close
        );

        // Every function declaration must contain ");" somewhere
        // (single-line ends with ");", multi-line has ");" on closing line)
        let decl_count = header.matches(");\n").count();
        assert!(
            decl_count >= ir.exports.len(),
            "expected >= {} function decls ending with ');', found {}",
            ir.exports.len(),
            decl_count
        );
    }

    #[test]
    fn c_header_multiline_params() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        // mimi_str_format has 5 params → should be multi-line
        assert!(header.contains("uint8_t* mimi_str_format(\n"));
    }

    #[test]
    fn c_header_enum_type() {
        use crate::component::types::{AbiEnum, AbiPrimitive, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Enum(AbiEnum {
                name: "MimiError".to_string(),
                variants: vec![
                    ("Ok".to_string(), 0),
                    ("IoError".to_string(), 1),
                    ("TypeError".to_string(), 2),
                ],
                repr: AbiPrimitive::I32,
            })],
        };
        let header = generate_c_header(&ir);

        assert!(header.contains("typedef int32_t MimiError;"));
        assert!(header.contains("#define MimiError_Ok ((int32_t)0)"));
        assert!(header.contains("#define MimiError_IoError ((int32_t)1)"));
        assert!(header.contains("#define MimiError_TypeError ((int32_t)2)"));
    }

    #[test]
    fn c_header_alias_type() {
        use crate::component::types::{AbiAlias, AbiPrimitive, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Alias(AbiAlias {
                name: "MimiFd".to_string(),
                target: AbiTypeRef::Primitive(AbiPrimitive::I64),
            })],
        };
        let header = generate_c_header(&ir);
        assert!(header.contains("typedef int64_t MimiFd;"));
    }
}
