//! C header generator: produces a `.h` file from Component IR.
//!
//! 0.31.30 (COMPONENT-BINDGEN-001): This is the first bindgen backend
//! that consumes ComponentIr instead of raw AST. It proves the pipeline:
//!
//! ```text
//! CheckedProgram → ComponentIr → c_header.rs → mimi_abi.h
//! ```
//!
//! The generated header includes:
//! - Include guard + system includes
//! - Struct definitions (repr(C) with field offsets)
//! - Opaque handle typedefs
//! - Enum definitions
//! - Function declarations (extern "C")
//! - BLAKE3 hash comment for tamper detection

use super::symbol::AbiSymbol;
use super::types::AbiTypeDef;
use super::ComponentIr;

/// Validate that a string is a safe C identifier.
///
/// Returns `true` if the name matches `[a-zA-Z_][a-zA-Z0-9_]*`.
/// Names failing this check could inject arbitrary C code into the
/// generated header (security: code injection via crafted .mimiabi).
pub fn is_valid_c_identifier(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let first = name.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }
    name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Sanitize a name for safe use as a C identifier.
///
/// Replaces invalid characters with `_`. Prepends `_` if the name
/// starts with a digit. Returns the sanitized name and whether it
/// was modified.
fn sanitize_c_identifier(name: &str) -> (String, bool) {
    if is_valid_c_identifier(name) {
        return (name.to_string(), false);
    }
    let mut out = String::with_capacity(name.len() + 1);
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else if i == 0 && c.is_ascii_digit() {
            out.push('_');
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    (out, true)
}

/// Sanitize a string for safe use inside a C comment.
///
/// Removes `*/` sequences that would break out of the comment block.
fn sanitize_c_comment(s: &str) -> String {
    s.replace("*/", "* /")
}

/// Generate a complete C header file from a Component IR.
///
/// The output is a self-contained `.h` file suitable for `#include`
/// from C/C++ code or for consumption by cbindgen-like tools.
pub fn generate_c_header(ir: &ComponentIr) -> String {
    let mut out = String::with_capacity(8192);
    let guard = format!(
        "{}_ABI_H",
        ir.identity.name.to_uppercase().replace('-', "_")
    );

    // ── Header preamble ──
    out.push_str(&format!(
        "/* Generated by Mimi Component IR v{} — DO NOT EDIT */\n",
        ir.identity.version
    ));
    out.push_str(&format!(
        "/* ABI version: {} | Component: {} */\n\n",
        ir.identity.abi_version, ir.identity.name
    ));
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n\n");

    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // ── Type definitions ──
    if !ir.types.is_empty() {
        out.push_str("/* ── Type Definitions ── */\n\n");
        for ty in &ir.types {
            emit_type_def(&mut out, ty);
        }
    }

    // ── Function declarations ──
    if !ir.exports.is_empty() {
        out.push_str("/* ── Runtime Exports ── */\n\n");
        for sym in &ir.exports {
            emit_function_decl(&mut out, sym);
        }
    }

    // ── Footer ──
    out.push_str("#ifdef __cplusplus\n}\n#endif\n\n");
    out.push_str(&format!("#endif /* {guard} */\n"));

    out
}

/// Emit a single type definition.
fn emit_type_def(out: &mut String, ty: &AbiTypeDef) {
    match ty {
        AbiTypeDef::Struct(s) => {
            let (name, _) = sanitize_c_identifier(&s.name);
            if let Some(size) = s.size {
                out.push_str(&format!("/* size={}B", size));
                if let Some(align) = s.align {
                    out.push_str(&format!(", align={}B", align));
                }
                out.push_str(" */\n");
            }
            out.push_str(&format!("typedef struct {} {{\n", name));
            for field in &s.fields {
                let (field_name, _) = sanitize_c_identifier(&field.name);
                let offset_comment = field
                    .offset
                    .map(|o| format!("  /* offset {} */", o))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "    {} {};{}\n",
                    field.ty.c_type_name(),
                    field_name,
                    offset_comment
                ));
            }
            out.push_str(&format!("}} {};\n\n", name));
        }
        AbiTypeDef::Enum(e) => {
            let (name, _) = sanitize_c_identifier(&e.name);
            out.push_str(&format!("typedef {} {};\n", e.repr.c_name(), name));
            for (variant, discriminant) in &e.variants {
                let (variant_name, _) = sanitize_c_identifier(variant);
                out.push_str(&format!(
                    "#define {}_{} (({}){})\n",
                    name,
                    variant_name,
                    e.repr.c_name(),
                    discriminant
                ));
            }
            out.push('\n');
        }
        AbiTypeDef::Alias(a) => {
            let (name, _) = sanitize_c_identifier(&a.name);
            out.push_str(&format!("typedef {} {};\n\n", a.target.c_type_name(), name));
        }
        AbiTypeDef::Opaque(o) => {
            let (name, _) = sanitize_c_identifier(&o.name);
            let desc = sanitize_c_comment(&o.description);
            out.push_str(&format!("/* {} */\ntypedef uintptr_t {};\n\n", desc, name));
        }
    }
}

/// Emit a single function declaration.
fn emit_function_decl(out: &mut String, sym: &AbiSymbol) {
    let (name, _) = sanitize_c_identifier(&sym.name);

    // Effect annotations as comments (sanitized against comment injection)
    if !sym.effects.is_empty() {
        let effects = sym
            .effects
            .iter()
            .map(|e| sanitize_c_comment(e))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("/* effects: {} */\n", effects));
    }
    if sym.is_unsafe {
        out.push_str("/* UNSAFE: caller must uphold safety invariants */\n");
    }

    let params = if sym.params.is_empty() {
        "void".to_string()
    } else {
        sym.params
            .iter()
            .map(|p| {
                let (param_name, _) = sanitize_c_identifier(&p.name);
                let nullable = if p.is_nullable { "/* nullable */ " } else { "" };
                format!("{}{} {}", nullable, p.ty.c_type_name(), param_name)
            })
            .collect::<Vec<_>>()
            .join(",\n    ")
    };

    // Multi-line params for readability when > 2 params
    if sym.params.len() > 2 {
        out.push_str(&format!(
            "{} {}(\n    {}\n);\n\n",
            sym.ret.c_type_name(),
            name,
            params
        ));
    } else {
        out.push_str(&format!(
            "{} {}({});\n\n",
            sym.ret.c_type_name(),
            name,
            params
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::gen::{register_core_runtime_abi, AbiGenerator};
    use crate::component::types::AbiTypeRef;
    use crate::component::ComponentIdentity;

    #[test]
    fn c_header_contains_guard() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#ifndef MIMI_RUNTIME_ABI_H"));
        assert!(header.contains("#define MIMI_RUNTIME_ABI_H"));
        assert!(header.contains("#endif /* MIMI_RUNTIME_ABI_H */"));
    }

    #[test]
    fn c_header_contains_includes() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#include <stdint.h>"));
        assert!(header.contains("#include <stdbool.h>"));
        assert!(header.contains("#include <stddef.h>"));
    }

    #[test]
    fn c_header_contains_struct_defs() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        // MimiString struct
        assert!(header.contains("typedef struct MimiString {"));
        assert!(header.contains("uint8_t* data;"));
        assert!(header.contains("uintptr_t len;"));
        assert!(header.contains("uintptr_t capacity;"));
        assert!(header.contains("} MimiString;"));

        // MimiSlice struct
        assert!(header.contains("typedef struct MimiSlice {"));
        assert!(header.contains("} MimiSlice;"));
    }

    #[test]
    fn c_header_contains_opaque_handles() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("typedef uintptr_t ListHandle;"));
        assert!(header.contains("typedef uintptr_t MapHandle;"));
        assert!(header.contains("typedef uintptr_t SetHandle;"));
        assert!(header.contains("typedef uintptr_t ActorHandle;"));
        assert!(header.contains("typedef uintptr_t FutureHandle;"));
    }

    #[test]
    fn c_header_contains_function_decls() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("intptr_t mimi_rc_alloc(uintptr_t size);"));
        assert!(header.contains("void mimi_rc_retain(intptr_t ptr);"));
        // handle("ListHandle") → MimiHandle/* ListHandle */ in C
        assert!(header.contains("MimiHandle/* ListHandle */ mimi_list_new(void);"));
        assert!(header.contains("int64_t mimi_timestamp(void);"));
    }

    #[test]
    fn c_header_contains_extern_c() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("#ifdef __cplusplus"));
        assert!(header.contains("extern \"C\" {"));
    }

    #[test]
    fn c_header_contains_unsafe_annotation() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("/* UNSAFE: caller must uphold safety invariants */"));
    }

    #[test]
    fn c_header_contains_effect_annotations() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        assert!(header.contains("/* effects: alloc */"));
        assert!(header.contains("/* effects: io */"));
        assert!(header.contains("/* effects: dealloc */"));
    }

    #[test]
    fn c_header_is_valid_c_syntax() {
        // Basic sanity: balanced braces, semicolons after declarations
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        let open = header.matches('{').count();
        let close = header.matches('}').count();
        assert_eq!(
            open, close,
            "unbalanced braces: {} open, {} close",
            open, close
        );

        // Every function declaration must contain ");" somewhere
        // (single-line ends with ");", multi-line has ");" on closing line)
        let decl_count = header.matches(");\n").count();
        assert!(
            decl_count >= ir.exports.len(),
            "expected >= {} function decls ending with ');', found {}",
            ir.exports.len(),
            decl_count
        );
    }

    #[test]
    fn c_header_multiline_params() {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        let ir = gen.build();
        let header = generate_c_header(&ir);

        // mimi_str_format has 5 params → should be multi-line
        assert!(header.contains("uint8_t* mimi_str_format(\n"));
    }

    #[test]
    fn c_header_enum_type() {
        use crate::component::types::{AbiEnum, AbiPrimitive, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Enum(AbiEnum {
                name: "MimiError".to_string(),
                variants: vec![
                    ("Ok".to_string(), 0),
                    ("IoError".to_string(), 1),
                    ("TypeError".to_string(), 2),
                ],
                repr: AbiPrimitive::I32,
            })],
        };
        let header = generate_c_header(&ir);

        assert!(header.contains("typedef int32_t MimiError;"));
        assert!(header.contains("#define MimiError_Ok ((int32_t)0)"));
        assert!(header.contains("#define MimiError_IoError ((int32_t)1)"));
        assert!(header.contains("#define MimiError_TypeError ((int32_t)2)"));
    }

    #[test]
    fn c_header_alias_type() {
        use crate::component::types::{AbiAlias, AbiPrimitive, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Alias(AbiAlias {
                name: "MimiFd".to_string(),
                target: AbiTypeRef::Primitive(AbiPrimitive::I64),
            })],
        };
        let header = generate_c_header(&ir);
        assert!(header.contains("typedef int64_t MimiFd;"));
    }

    // ── Attack tests (0.31.37) ──

    #[test]
    fn c_identifier_validation() {
        assert!(is_valid_c_identifier("mimi_list_push"));
        assert!(is_valid_c_identifier("_private"));
        assert!(is_valid_c_identifier("MimiString"));
        assert!(!is_valid_c_identifier(""));
        assert!(!is_valid_c_identifier("123abc"));
        assert!(!is_valid_c_identifier("mimi_evil(); int x"));
        assert!(!is_valid_c_identifier("foo-bar"));
        assert!(!is_valid_c_identifier("a b"));
    }

    #[test]
    fn c_header_sanitizes_injection_in_symbol_name() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "mimi_evil(); int x".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::Function,
                params: vec![],
                ret: AbiTypeRef::Void,
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            imports: vec![],
            types: vec![],
        };
        let header = generate_c_header(&ir);
        // The injected code must not appear verbatim
        assert!(!header.contains("mimi_evil(); int x"));
        // The sanitized name should appear (each invalid char → _)
        assert!(header.contains("mimi_evil____int_x"));
    }

    #[test]
    fn c_header_sanitizes_comment_injection() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "mimi_test".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::Function,
                params: vec![],
                ret: AbiTypeRef::Void,
                effects: vec!["alloc */ int evil; /*".to_string()],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            imports: vec![],
            types: vec![],
        };
        let header = generate_c_header(&ir);
        // The */ must be neutralized
        assert!(!header.contains("*/ int evil;"));
        assert!(header.contains("* / int evil;"));
    }

    #[test]
    fn c_header_sanitizes_type_name_injection() {
        use crate::component::types::{AbiOpaque, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Opaque(AbiOpaque {
                name: "Evil; typedef int".to_string(),
                description: "test */ break".to_string(),
            })],
        };
        let header = generate_c_header(&ir);
        assert!(!header.contains("Evil; typedef int"));
        assert!(header.contains("Evil__typedef_int"));
    }
}
