//! Rust bindgen backend: generates Rust FFI bindings from Component IR.
//!
//! 0.31.35 (COMPONENT-BINDGEN-002): Second bindgen backend consuming
//! ComponentIr. Generates an unsafe `-sys` style crate:
//!
//! ```text
//! ComponentIr → rust_bind.rs → mimi_sys.rs
//! ```
//!
//! The generated code includes:
//! - `#[repr(C)]` struct definitions
//! - Type aliases for opaque handles
//! - `extern "C"` function declarations (implicitly unsafe to call in Rust 2021)
//! - Doc comments from effects/unsafe annotations

use super::symbol::AbiSymbol;
use super::types::{AbiTypeDef, AbiTypeRef};
use super::ComponentIr;

/// Rust keywords that must be escaped with `r#` when used as identifiers.
const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "async", "await", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield",
];

/// Validate that a string is a safe Rust identifier.
///
/// Returns `true` if the name matches `[a-zA-Z_][a-zA-Z0-9_]*` and is
/// not a Rust keyword (or is already escaped with `r#`).
fn is_valid_rust_identifier(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    // Already escaped with r# — valid as long as the inner part is alphanumeric
    if let Some(inner) = name.strip_prefix("r#") {
        if inner.is_empty() {
            return false;
        }
        let first = inner.chars().next().unwrap_or('_');
        return (first.is_ascii_alphabetic() || first == '_')
            && inner.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    }
    let first = name.chars().next().unwrap_or('_');
    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }
    if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return false;
    }
    !RUST_KEYWORDS.contains(&name)
}

/// Escape a name for safe use as a Rust identifier.
///
/// - Replaces invalid characters with `_`
/// - Prepends `_` if the name starts with a digit
/// - Escapes Rust keywords with `r#`
///
/// Fast path: if the name is already valid, returns it unchanged.
fn escape_rust_identifier(name: &str) -> String {
    if is_valid_rust_identifier(name) {
        return name.to_string();
    }
    let mut out = String::with_capacity(name.len() + 2);
    for (i, c) in name.chars().enumerate() {
        if i == 0 && c.is_ascii_digit() {
            // Digit at start: prepend underscore
            out.push('_');
            out.push(c);
        } else if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    if RUST_KEYWORDS.contains(&out.as_str()) {
        format!("r#{}", out)
    } else {
        out
    }
}

/// Generate Rust FFI bindings from a Component IR.
///
/// The output is a self-contained `.rs` file suitable for inclusion
/// in a `-sys` crate. All functions are inside `extern "C"` blocks
/// and are implicitly unsafe to call (Rust 2021 semantics).
pub fn generate_rust_bindings(ir: &ComponentIr) -> String {
    let mut out = String::with_capacity(8192);

    // ── Preamble ──
    out.push_str(&format!(
        "//! Generated by Mimi Component IR v{} — DO NOT EDIT\n",
        ir.identity.version
    ));
    out.push_str(&format!(
        "//! ABI version: {} | Component: {}\n",
        ir.identity.abi_version, ir.identity.name
    ));
    out.push_str("#![allow(non_camel_case_types, non_snake_case, dead_code)]\n\n");

    // ── Type definitions ──
    if !ir.types.is_empty() {
        out.push_str("// ── Type Definitions ──\n\n");
        for ty in &ir.types {
            emit_rust_type_def(&mut out, ty);
        }
    }

    // ── Function declarations ──
    if !ir.exports.is_empty() {
        out.push_str("// ── Runtime Exports ──\n\n");
        out.push_str("extern \"C\" {\n");
        for sym in &ir.exports {
            emit_rust_fn_decl(&mut out, sym);
        }
        out.push_str("}\n");
    }

    out
}

/// Emit a Rust type definition.
fn emit_rust_type_def(out: &mut String, ty: &AbiTypeDef) {
    match ty {
        AbiTypeDef::Struct(s) => {
            let name = escape_rust_identifier(&s.name);
            if let Some(size) = s.size {
                out.push_str(&format!("/// size={}B", size));
                if let Some(align) = s.align {
                    out.push_str(&format!(", align={}B", align));
                }
                out.push('\n');
            }
            out.push_str("#[repr(C)]\n");
            out.push_str(&format!("pub struct {} {{\n", name));
            for field in &s.fields {
                let field_name = escape_rust_identifier(&field.name);
                let offset_comment = field
                    .offset
                    .map(|o| format!(" // offset {}", o))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "    pub {}: {},{}\n",
                    field_name,
                    rust_type_name(&field.ty),
                    offset_comment
                ));
            }
            out.push_str("}\n\n");
        }
        AbiTypeDef::Enum(e) => {
            let name = escape_rust_identifier(&e.name);
            out.push_str(&format!("pub type {} = {};\n", name, e.repr.rust_name()));
            for (variant, discriminant) in &e.variants {
                let variant_name = escape_rust_identifier(variant);
                out.push_str(&format!(
                    "pub const {}_{}: {} = {};\n",
                    name,
                    variant_name,
                    e.repr.rust_name(),
                    discriminant
                ));
            }
            out.push('\n');
        }
        AbiTypeDef::Alias(a) => {
            let name = escape_rust_identifier(&a.name);
            out.push_str(&format!(
                "pub type {} = {};\n\n",
                name,
                rust_type_name(&a.target)
            ));
        }
        AbiTypeDef::Opaque(o) => {
            let name = escape_rust_identifier(&o.name);
            out.push_str(&format!("/// {}\n", o.description));
            out.push_str(&format!("pub type {} = usize;\n\n", name));
        }
    }
}

/// Emit a Rust function declaration inside an `extern "C"` block.
fn emit_rust_fn_decl(out: &mut String, sym: &AbiSymbol) {
    let name = escape_rust_identifier(&sym.name);

    // Doc comment from effects
    if !sym.effects.is_empty() || sym.is_unsafe {
        out.push_str("    ///");
        if sym.is_unsafe {
            out.push_str(" UNSAFE");
        }
        if !sym.effects.is_empty() {
            if sym.is_unsafe {
                out.push_str(" |");
            }
            out.push_str(&format!(" effects: {}", sym.effects.join(", ")));
        }
        out.push('\n');
    }

    let params = sym
        .params
        .iter()
        .map(|p| {
            let param_name = escape_rust_identifier(&p.name);
            format!("{}: {}", param_name, rust_type_name(&p.ty))
        })
        .collect::<Vec<_>>()
        .join(", ");

    let ret = if sym.ret.is_void() {
        String::new()
    } else {
        format!(" -> {}", rust_type_name(&sym.ret))
    };

    out.push_str(&format!("    pub fn {}({}){};\n", name, params, ret));
}

/// Convert an AbiTypeRef to a Rust type name.
fn rust_type_name(ty: &AbiTypeRef) -> String {
    match ty {
        AbiTypeRef::Primitive(p) => p.rust_name().to_string(),
        AbiTypeRef::Named(name) => name.clone(),
        AbiTypeRef::Pointer(inner) => format!("*mut {}", rust_type_name(inner)),
        AbiTypeRef::Slice(inner) => format!("*mut {}", rust_type_name(inner)),
        AbiTypeRef::Opaque(name) => name.clone(),
        AbiTypeRef::FatPointer { has_capacity, .. } => {
            if *has_capacity {
                "MimiString".to_string()
            } else {
                "MimiSlice".to_string()
            }
        }
        AbiTypeRef::Void => "()".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::gen::{register_core_runtime_abi, AbiGenerator};
    use crate::component::types::AbiTypeRef;
    use crate::component::ComponentIdentity;

    fn make_ir() -> ComponentIr {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        gen.build()
    }

    #[test]
    fn rust_bindings_contains_preamble() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("//! Generated by Mimi Component IR"));
        assert!(bindings.contains("#![allow(non_camel_case_types"));
    }

    #[test]
    fn rust_bindings_contains_structs() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // Audit 2026-08-05: the phantom MimiString/MimiSlice structs were
        // removed from the core registry (no runtime counterparts), so the
        // core bindings carry no #[repr(C)] structs — only opaque handles.
        assert!(!bindings.contains("pub struct MimiString"));
        assert!(!bindings.contains("pub struct MimiSlice"));

        // Struct emission must still work for components that define real
        // repr(C) structs:
        use crate::component::types::{AbiField, AbiPrimitive, AbiStruct, AbiTypeDef};
        use crate::component::ComponentIdentity;
        let ir_with_struct = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Struct(AbiStruct {
                name: "Point".to_string(),
                fields: vec![
                    AbiField {
                        name: "x".to_string(),
                        ty: AbiTypeRef::Primitive(AbiPrimitive::I32),
                        offset: Some(0),
                    },
                    AbiField {
                        name: "y".to_string(),
                        ty: AbiTypeRef::Primitive(AbiPrimitive::I32),
                        offset: Some(4),
                    },
                ],
                is_repr_c: true,
                size: Some(8),
                align: Some(4),
            })],
        };
        let bindings = generate_rust_bindings(&ir_with_struct);
        assert!(bindings.contains("#[repr(C)]"));
        assert!(bindings.contains("pub struct Point {"));
        assert!(bindings.contains("pub x: i32,"));
        assert!(bindings.contains("pub y: i32,"));
    }

    #[test]
    fn rust_bindings_contains_opaque_handles() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("pub type ListHandle = usize;"));
        assert!(bindings.contains("pub type MapHandle = usize;"));
        assert!(bindings.contains("pub type ActorHandle = usize;"));
    }

    #[test]
    fn rust_bindings_contains_extern_block() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("extern \"C\" {"));
        // Audit fix 2026-08-05: mimi_rc_alloc really is (size: i64) -> *mut c_void
        assert!(bindings.contains("pub fn mimi_rc_alloc(size: i64) -> *mut u8;"));
        assert!(bindings.contains("pub fn mimi_rc_retain(ptr: *mut u8);"));
        // mimi_timestamp was phantom; the real time source is mimi_now.
        assert!(bindings.contains("pub fn mimi_now() -> i64;"));
        // Corrected real signature (capability.rs:34).
        assert!(bindings.contains("pub fn mimi_cap_register(name: *mut u8) -> i64;"));
    }

    #[test]
    fn rust_bindings_contains_doc_comments() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // mimi_rc_alloc has effect "alloc"
        assert!(bindings.contains("/// effects: alloc"));
        // mimi_runtime_abort is unsafe
        assert!(bindings.contains("/// UNSAFE"));
    }

    #[test]
    fn rust_bindings_function_count() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // Count "pub fn mimi_" occurrences
        let fn_count = bindings.matches("pub fn mimi_").count();
        assert!(
            fn_count >= 140,
            "expected >=140 function declarations, got {}",
            fn_count
        );
    }

    #[test]
    fn rust_bindings_valid_syntax() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // Balanced braces
        let open = bindings.matches('{').count();
        let close = bindings.matches('}').count();
        assert_eq!(open, close, "unbalanced braces");

        // Every fn decl ends with ;
        for line in bindings.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("pub fn mimi_") {
                assert!(
                    trimmed.ends_with(';'),
                    "fn decl doesn't end with ';': {}",
                    trimmed
                );
            }
        }
    }

    #[test]
    fn rust_bindings_callback_symbol() {
        use crate::component::symbol::{AbiCallbackCategory, AbiSymbolKind};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "mimi_on_data".to_string(),
                kind: AbiSymbolKind::Callback,
                params: vec![crate::component::symbol::AbiParam {
                    name: "data".to_string(),
                    ty: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I64),
                    is_nullable: false,
                }],
                ret: AbiTypeRef::Void,
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: Some(AbiCallbackCategory::AsyncMultiShot),
            }],
            imports: vec![],
            types: vec![],
        };
        let bindings = generate_rust_bindings(&ir);
        assert!(bindings.contains("pub fn mimi_on_data(data: i64);"));
    }

    #[test]
    fn rust_bindings_import_symbols() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![AbiSymbol {
                name: "abs".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::ExternFunction,
                params: vec![crate::component::symbol::AbiParam {
                    name: "x".to_string(),
                    ty: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I32),
                    is_nullable: false,
                }],
                ret: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I32),
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            types: vec![],
        };
        // Imports are not in the extern "C" block (only exports are)
        let bindings = generate_rust_bindings(&ir);
        assert!(!bindings.contains("pub fn abs"));
    }

    // ── Attack tests (0.31.37) ──

    #[test]
    fn rust_identifier_escaping() {
        assert!(is_valid_rust_identifier("mimi_list_push"));
        assert!(is_valid_rust_identifier("_private"));
        assert!(!is_valid_rust_identifier(""));
        assert!(!is_valid_rust_identifier("123abc"));
        assert!(!is_valid_rust_identifier("type")); // Rust keyword
        assert!(!is_valid_rust_identifier("fn")); // Rust keyword
        assert!(is_valid_rust_identifier("r#type")); // already escaped
    }

    #[test]
    fn rust_bindings_escapes_keyword_field_names() {
        use crate::component::types::{AbiField, AbiPrimitive, AbiStruct, AbiTypeDef};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![],
            types: vec![AbiTypeDef::Struct(AbiStruct {
                name: "Config".to_string(),
                fields: vec![
                    AbiField {
                        name: "type".to_string(),
                        ty: AbiTypeRef::Primitive(AbiPrimitive::I32),
                        offset: Some(0),
                    },
                    AbiField {
                        name: "match".to_string(),
                        ty: AbiTypeRef::Primitive(AbiPrimitive::I64),
                        offset: Some(4),
                    },
                ],
                is_repr_c: true,
                size: Some(16),
                align: Some(8),
            })],
        };
        let bindings = generate_rust_bindings(&ir);
        // Keywords must be escaped with r#
        assert!(bindings.contains("pub r#type: i32"));
        assert!(bindings.contains("pub r#match: i64"));
    }

    #[test]
    fn rust_bindings_sanitizes_injection_in_fn_name() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "mimi_evil() -> i32 { 42 }".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::Function,
                params: vec![],
                ret: AbiTypeRef::Void,
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            imports: vec![],
            types: vec![],
        };
        let bindings = generate_rust_bindings(&ir);
        // The injected code must not appear verbatim
        assert!(!bindings.contains("mimi_evil() -> i32 { 42 }"));
        // Sanitized name should appear (each invalid char → _)
        // "mimi_evil() -> i32 { 42 }" → "mimi_evil______i32___42__"
        assert!(bindings.contains("mimi_evil______i32___42__"));
    }

    #[test]
    fn rust_bindings_sanitizes_digit_start_name() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "123invalid".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::Function,
                params: vec![],
                ret: AbiTypeRef::Void,
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            imports: vec![],
            types: vec![],
        };
        let bindings = generate_rust_bindings(&ir);
        assert!(bindings.contains("pub fn _123invalid()"));
    }
}
