//! Rust bindgen backend: generates Rust FFI bindings from Component IR.
//!
//! 0.31.35 (COMPONENT-BINDGEN-002): Second bindgen backend consuming
//! ComponentIr. Generates an unsafe `-sys` style crate:
//!
//! ```text
//! ComponentIr → rust_bind.rs → mimi_sys.rs
//! ```
//!
//! The generated code includes:
//! - `#[repr(C)]` struct definitions
//! - Type aliases for opaque handles
//! - `extern "C"` function declarations
//! - `unsafe` marker on all functions
//! - Doc comments from effects/unsafe annotations

use super::symbol::AbiSymbol;
use super::types::{AbiTypeDef, AbiTypeRef};
use super::ComponentIr;

/// Generate Rust FFI bindings from a Component IR.
///
/// The output is a self-contained `.rs` file suitable for inclusion
/// in a `-sys` crate. All functions are `unsafe extern "C"`.
pub fn generate_rust_bindings(ir: &ComponentIr) -> String {
    let mut out = String::with_capacity(8192);

    // ── Preamble ──
    out.push_str(&format!(
        "//! Generated by Mimi Component IR v{} — DO NOT EDIT\n",
        ir.identity.version
    ));
    out.push_str(&format!(
        "//! ABI version: {} | Component: {}\n",
        ir.identity.abi_version, ir.identity.name
    ));
    out.push_str("#![allow(non_camel_case_types, non_snake_case, dead_code)]\n\n");

    // ── Type definitions ──
    if !ir.types.is_empty() {
        out.push_str("// ── Type Definitions ──\n\n");
        for ty in &ir.types {
            emit_rust_type_def(&mut out, ty);
        }
    }

    // ── Function declarations ──
    if !ir.exports.is_empty() {
        out.push_str("// ── Runtime Exports ──\n\n");
        out.push_str("extern \"C\" {\n");
        for sym in &ir.exports {
            emit_rust_fn_decl(&mut out, sym);
        }
        out.push_str("}\n");
    }

    out
}

/// Emit a Rust type definition.
fn emit_rust_type_def(out: &mut String, ty: &AbiTypeDef) {
    match ty {
        AbiTypeDef::Struct(s) => {
            if let Some(size) = s.size {
                out.push_str(&format!("/// size={}B", size));
                if let Some(align) = s.align {
                    out.push_str(&format!(", align={}B", align));
                }
                out.push('\n');
            }
            out.push_str("#[repr(C)]\n");
            out.push_str(&format!("pub struct {} {{\n", s.name));
            for field in &s.fields {
                let offset_comment = field
                    .offset
                    .map(|o| format!(" // offset {}", o))
                    .unwrap_or_default();
                out.push_str(&format!(
                    "    pub {}: {},{}\n",
                    field.name,
                    rust_type_name(&field.ty),
                    offset_comment
                ));
            }
            out.push_str("}\n\n");
        }
        AbiTypeDef::Enum(e) => {
            out.push_str(&format!("pub type {} = {};\n", e.name, e.repr.rust_name()));
            for (variant, discriminant) in &e.variants {
                out.push_str(&format!(
                    "pub const {}_{}: {} = {};\n",
                    e.name,
                    variant,
                    e.repr.rust_name(),
                    discriminant
                ));
            }
            out.push('\n');
        }
        AbiTypeDef::Alias(a) => {
            out.push_str(&format!(
                "pub type {} = {};\n\n",
                a.name,
                rust_type_name(&a.target)
            ));
        }
        AbiTypeDef::Opaque(o) => {
            out.push_str(&format!("/// {}\n", o.description));
            out.push_str(&format!("pub type {} = usize;\n\n", o.name));
        }
    }
}

/// Emit a Rust function declaration inside an `extern "C"` block.
fn emit_rust_fn_decl(out: &mut String, sym: &AbiSymbol) {
    // Doc comment from effects
    if !sym.effects.is_empty() || sym.is_unsafe {
        out.push_str("    ///");
        if sym.is_unsafe {
            out.push_str(" UNSAFE");
        }
        if !sym.effects.is_empty() {
            if sym.is_unsafe {
                out.push_str(" |");
            }
            out.push_str(&format!(" effects: {}", sym.effects.join(", ")));
        }
        out.push('\n');
    }

    let params = sym
        .params
        .iter()
        .map(|p| format!("{}: {}", p.name, rust_type_name(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");

    let ret = if sym.ret.is_void() {
        String::new()
    } else {
        format!(" -> {}", rust_type_name(&sym.ret))
    };

    out.push_str(&format!("    pub fn {}({}){};\n", sym.name, params, ret));
}

/// Convert an AbiTypeRef to a Rust type name.
fn rust_type_name(ty: &AbiTypeRef) -> String {
    match ty {
        AbiTypeRef::Primitive(p) => p.rust_name().to_string(),
        AbiTypeRef::Named(name) => name.clone(),
        AbiTypeRef::Pointer(inner) => format!("*mut {}", rust_type_name(inner)),
        AbiTypeRef::Slice(inner) => format!("*mut {}", rust_type_name(inner)),
        AbiTypeRef::Opaque(name) => name.clone(),
        AbiTypeRef::FatPointer { has_capacity, .. } => {
            if *has_capacity {
                "MimiString".to_string()
            } else {
                "MimiSlice".to_string()
            }
        }
        AbiTypeRef::Void => "()".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::gen::{register_core_runtime_abi, AbiGenerator};
    use crate::component::types::AbiTypeRef;
    use crate::component::ComponentIdentity;

    fn make_ir() -> ComponentIr {
        let mut gen = AbiGenerator::new();
        register_core_runtime_abi(&mut gen);
        gen.build()
    }

    #[test]
    fn rust_bindings_contains_preamble() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("//! Generated by Mimi Component IR"));
        assert!(bindings.contains("#![allow(non_camel_case_types"));
    }

    #[test]
    fn rust_bindings_contains_structs() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("#[repr(C)]"));
        assert!(bindings.contains("pub struct MimiString {"));
        assert!(bindings.contains("pub data: *mut u8,"));
        assert!(bindings.contains("pub len: usize,"));
        assert!(bindings.contains("pub capacity: usize,"));
        assert!(bindings.contains("pub struct MimiSlice {"));
    }

    #[test]
    fn rust_bindings_contains_opaque_handles() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("pub type ListHandle = usize;"));
        assert!(bindings.contains("pub type MapHandle = usize;"));
        assert!(bindings.contains("pub type ActorHandle = usize;"));
    }

    #[test]
    fn rust_bindings_contains_extern_block() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        assert!(bindings.contains("extern \"C\" {"));
        assert!(bindings.contains("pub fn mimi_rc_alloc(size: usize) -> isize;"));
        assert!(bindings.contains("pub fn mimi_rc_retain(ptr: isize);"));
        assert!(bindings.contains("pub fn mimi_timestamp() -> i64;"));
    }

    #[test]
    fn rust_bindings_contains_doc_comments() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // mimi_rc_alloc has effect "alloc"
        assert!(bindings.contains("/// effects: alloc"));
        // mimi_runtime_abort is unsafe
        assert!(bindings.contains("/// UNSAFE"));
    }

    #[test]
    fn rust_bindings_function_count() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // Count "pub fn mimi_" occurrences
        let fn_count = bindings.matches("pub fn mimi_").count();
        assert!(
            fn_count >= 140,
            "expected >=140 function declarations, got {}",
            fn_count
        );
    }

    #[test]
    fn rust_bindings_valid_syntax() {
        let ir = make_ir();
        let bindings = generate_rust_bindings(&ir);

        // Balanced braces
        let open = bindings.matches('{').count();
        let close = bindings.matches('}').count();
        assert_eq!(open, close, "unbalanced braces");

        // Every fn decl ends with ;
        for line in bindings.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("pub fn mimi_") {
                assert!(
                    trimmed.ends_with(';'),
                    "fn decl doesn't end with ';': {}",
                    trimmed
                );
            }
        }
    }

    #[test]
    fn rust_bindings_callback_symbol() {
        use crate::component::symbol::{AbiCallbackCategory, AbiSymbolKind};
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![AbiSymbol {
                name: "mimi_on_data".to_string(),
                kind: AbiSymbolKind::Callback,
                params: vec![crate::component::symbol::AbiParam {
                    name: "data".to_string(),
                    ty: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I64),
                    is_nullable: false,
                }],
                ret: AbiTypeRef::Void,
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: Some(AbiCallbackCategory::AsyncMultiShot),
            }],
            imports: vec![],
            types: vec![],
        };
        let bindings = generate_rust_bindings(&ir);
        assert!(bindings.contains("pub fn mimi_on_data(data: i64);"));
    }

    #[test]
    fn rust_bindings_import_symbols() {
        let ir = ComponentIr {
            identity: ComponentIdentity::default(),
            exports: vec![],
            imports: vec![AbiSymbol {
                name: "abs".to_string(),
                kind: crate::component::symbol::AbiSymbolKind::ExternFunction,
                params: vec![crate::component::symbol::AbiParam {
                    name: "x".to_string(),
                    ty: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I32),
                    is_nullable: false,
                }],
                ret: AbiTypeRef::Primitive(crate::component::types::AbiPrimitive::I32),
                effects: vec![],
                is_unsafe: false,
                call_conv: crate::component::symbol::AbiCallConv::C,
                callback_category: None,
            }],
            types: vec![],
        };
        // Imports are not in the extern "C" block (only exports are)
        let bindings = generate_rust_bindings(&ir);
        assert!(!bindings.contains("pub fn abs"));
    }
}
