use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenKind {
    // Literals
    Int(String),
    Float(String),
    String(String),
    FString(String), // f"..." raw content for parser to split
    True,
    False,
    Unit,

    // Identifiers / keywords
    Ident(String),

    // Keywords
    Module,
    Type,
    Func,
    Fn,
    Actor,
    Newtype,
    Let,
    Mut,
    Ref,
    Shared,
    LocalShared,
    Weak,
    WeakLocal,
    CShared,
    CBorrow,
    CBorrowMut,
    RawString,
    Arena,
    Alloc,
    Cap,
    Trait,
    Impl,
    Dyn,
    Where,
    Extern,
    If,
    Else,
    For,
    In,
    While,
    Return,
    Break,
    Continue,
    Match,
    Use,
    Pub,
    Drop,
    Await,
    Async,
    Unsafe,
    Spawn,
    Steps,
    Parasteps,
    Quote,
    Comptime,
    Failure,
    Requires,
    Ensures,
    Math,
    Desc,
    Rule,
    Old,
    Mms,
    With,
    And,
    Or,
    Not,

    // Types
    I32,
    I64,
    F64,
    Bool,
    StringKw,
    Nothing,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Pow,
    Eq,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    BitAndEq,
    BitOrEq,
    BitXorEq,
    EqEq,
    Ne,
    Lt,
    Gt,
    Le,
    Ge,
    AndAnd,
    OrOr,
    #[allow(dead_code)]
    NotOp,
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
    Tilde,
    DollarParen,

    // Punctuation
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Colon,
    Semi,
    Comma,
    Dot,
    DotDot,
    ColonColon,
    Arrow,
    FatArrow,
    Question,
    Bang,
    Ellipsis,
    At,
    Hash,
    Tick,

    Newline,
    Indent,
    Dedent,
    Eof,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            TokenKind::Int(v) => return write!(f, "integer `{}`", v),
            TokenKind::Float(v) => return write!(f, "float `{}`", v),
            TokenKind::String(v) => return write!(f, "string `{}`", v),
            TokenKind::FString(v) => return write!(f, "f-string `{}`", v),
            TokenKind::Ident(v) => return write!(f, "identifier `{}`", v),
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Unit => "()",
            TokenKind::Module => "module",
            TokenKind::Type => "type",
            TokenKind::Func => "func",
            TokenKind::Fn => "fn",
            TokenKind::Actor => "actor",
            TokenKind::Newtype => "newtype",
            TokenKind::Let => "let",
            TokenKind::Mut => "mut",
            TokenKind::Ref => "ref",
            TokenKind::Shared => "shared",
            TokenKind::LocalShared => "local_shared",
            TokenKind::Weak => "weak",
            TokenKind::WeakLocal => "weak_local",
            TokenKind::CShared => "c_shared",
            TokenKind::CBorrow => "c_borrow",
            TokenKind::CBorrowMut => "c_borrow_mut",
            TokenKind::RawString => "raw_string",
            TokenKind::Arena => "arena",
            TokenKind::Alloc => "alloc",
            TokenKind::Cap => "cap",
            TokenKind::Trait => "trait",
            TokenKind::Impl => "impl",
            TokenKind::Dyn => "dyn",
            TokenKind::Where => "where",
            TokenKind::Extern => "extern",
            TokenKind::If => "if",
            TokenKind::Else => "else",
            TokenKind::For => "for",
            TokenKind::In => "in",
            TokenKind::While => "while",
            TokenKind::Return => "return",
            TokenKind::Break => "break",
            TokenKind::Continue => "continue",
            TokenKind::Match => "match",
            TokenKind::Use => "use",
            TokenKind::Pub => "pub",
            TokenKind::Drop => "drop",
            TokenKind::Await => "await",
            TokenKind::Async => "async",
            TokenKind::Unsafe => "unsafe",
            TokenKind::Spawn => "spawn",
            TokenKind::Steps => "steps",
            TokenKind::Parasteps => "parasteps",
            TokenKind::Quote => "quote",
            TokenKind::Comptime => "comptime",

            TokenKind::Failure => "failure",
            TokenKind::Requires => "requires",
            TokenKind::Ensures => "ensures",
            TokenKind::Math => "math",
            TokenKind::Desc => "desc",
            TokenKind::Rule => "rule",
            TokenKind::Old => "old",
            TokenKind::Mms => "mms",
            TokenKind::With => "with",
            TokenKind::And => "and",
            TokenKind::Or => "or",
            TokenKind::Not => "not",
            TokenKind::I32 => "i32",
            TokenKind::I64 => "i64",
            TokenKind::F64 => "f64",
            TokenKind::Bool => "bool",
            TokenKind::StringKw => "string",
            TokenKind::Nothing => "nothing",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Star => "*",
            TokenKind::Slash => "/",
            TokenKind::Percent => "%",
            TokenKind::Pow => "**",
            TokenKind::Eq => "=",
            TokenKind::PlusEq => "+=",
            TokenKind::MinusEq => "-=",
            TokenKind::StarEq => "*=",
            TokenKind::SlashEq => "/=",
            TokenKind::EqEq => "==",
            TokenKind::Ne => "!=",
            TokenKind::Lt => "<",
            TokenKind::Gt => ">",
            TokenKind::Le => "<=",
            TokenKind::Ge => ">=",
            TokenKind::AndAnd => "&&",
            TokenKind::OrOr => "||",
            TokenKind::NotOp => "!",
            TokenKind::BitAnd => "&",
            TokenKind::BitOr => "|",
            TokenKind::BitXor => "^",
            TokenKind::Shl => "<<",
            TokenKind::Shr => ">>",
            TokenKind::Tilde => "~",
            TokenKind::DollarParen => "$(",
            TokenKind::LParen => "(",
            TokenKind::RParen => ")",
            TokenKind::LBrace => "{",
            TokenKind::RBrace => "}",
            TokenKind::LBracket => "[",
            TokenKind::RBracket => "]",
            TokenKind::Colon => ":",
            TokenKind::Semi => ";",
            TokenKind::Comma => ",",
            TokenKind::Dot => ".",
            TokenKind::DotDot => "..",
            TokenKind::ColonColon => "::",
            TokenKind::Arrow => "->",
            TokenKind::FatArrow => "=>",
            TokenKind::Question => "?",
            TokenKind::Bang => "!",
            TokenKind::Ellipsis => "...",
            TokenKind::At => "@",
            TokenKind::Hash => "#",
            TokenKind::Newline => "newline",
            TokenKind::Indent => "INDENT",
            TokenKind::Dedent => "DEDENT",
            TokenKind::Tick => "'",
            TokenKind::Eof => "EOF",
            TokenKind::BitAndEq => "&=",
            TokenKind::BitOrEq => "|=",
            TokenKind::BitXorEq => "^=",
        };
        write!(f, "{}", s)
    }
}

impl TokenKind {
    pub fn source_text(&self) -> &str {
        match self {
            TokenKind::Int(v) => v,
            TokenKind::Float(v) => v,
            TokenKind::String(v) => v,
            TokenKind::FString(v) => v,
            TokenKind::Ident(v) => v,
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Unit => "unit",
            TokenKind::Module => "module",
            TokenKind::Type => "type",
            TokenKind::Func => "func",
            TokenKind::Fn => "fn",
            TokenKind::Actor => "actor",
            TokenKind::Newtype => "newtype",
            TokenKind::Let => "let",
            TokenKind::Mut => "mut",
            TokenKind::Ref => "ref",
            TokenKind::Shared => "shared",
            TokenKind::LocalShared => "local_shared",
            TokenKind::Weak => "weak",
            TokenKind::WeakLocal => "weak_local",
            TokenKind::CShared => "c_shared",
            TokenKind::CBorrow => "c_borrow",
            TokenKind::CBorrowMut => "c_borrow_mut",
            TokenKind::RawString => "raw_string",
            TokenKind::Arena => "arena",
            TokenKind::Alloc => "alloc",
            TokenKind::Cap => "cap",
            TokenKind::Trait => "trait",
            TokenKind::Impl => "impl",
            TokenKind::Dyn => "dyn",
            TokenKind::Where => "where",
            TokenKind::Extern => "extern",
            TokenKind::If => "if",
            TokenKind::Else => "else",
            TokenKind::For => "for",
            TokenKind::In => "in",
            TokenKind::While => "while",
            TokenKind::Return => "return",
            TokenKind::Break => "break",
            TokenKind::Continue => "continue",
            TokenKind::Match => "match",
            TokenKind::Use => "use",
            TokenKind::Pub => "pub",
            TokenKind::Drop => "drop",
            TokenKind::Await => "await",
            TokenKind::Async => "async",
            TokenKind::Unsafe => "unsafe",
            TokenKind::Spawn => "spawn",
            TokenKind::Steps => "steps",
            TokenKind::Parasteps => "parasteps",
            TokenKind::Quote => "quote",
            TokenKind::Comptime => "comptime",

            TokenKind::Failure => "failure",
            TokenKind::Requires => "requires",
            TokenKind::Ensures => "ensures",
            TokenKind::Math => "math",
            TokenKind::Desc => "desc",
            TokenKind::Rule => "rule",
            TokenKind::Old => "old",
            TokenKind::Mms => "mms",
            TokenKind::With => "with",
            TokenKind::And => "and",
            TokenKind::Or => "or",
            TokenKind::Not => "not",
            TokenKind::I32 => "i32",
            TokenKind::I64 => "i64",
            TokenKind::F64 => "f64",
            TokenKind::Bool => "bool",
            TokenKind::StringKw => "string",
            TokenKind::Nothing => "nothing",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Star => "*",
            TokenKind::Slash => "/",
            TokenKind::Percent => "%",
            TokenKind::Pow => "**",
            TokenKind::Eq => "=",
            TokenKind::PlusEq => "+=",
            TokenKind::MinusEq => "-=",
            TokenKind::StarEq => "*=",
            TokenKind::SlashEq => "/=",
            TokenKind::EqEq => "==",
            TokenKind::Ne => "!=",
            TokenKind::Lt => "<",
            TokenKind::Gt => ">",
            TokenKind::Le => "<=",
            TokenKind::Ge => ">=",
            TokenKind::AndAnd => "&&",
            TokenKind::OrOr => "||",
            TokenKind::NotOp => "!",
            TokenKind::BitAnd => "&",
            TokenKind::BitOr => "|",
            TokenKind::BitXor => "^",
            TokenKind::Shl => "<<",
            TokenKind::Shr => ">>",
            TokenKind::Tilde => "~",
            TokenKind::DollarParen => "$(",
            TokenKind::LParen => "(",
            TokenKind::RParen => ")",
            TokenKind::LBrace => "{",
            TokenKind::RBrace => "}",
            TokenKind::LBracket => "[",
            TokenKind::RBracket => "]",
            TokenKind::Colon => ":",
            TokenKind::Semi => ";",
            TokenKind::Comma => ",",
            TokenKind::Dot => ".",
            TokenKind::DotDot => "..",
            TokenKind::ColonColon => "::",
            TokenKind::Arrow => "->",
            TokenKind::FatArrow => "=>",
            TokenKind::Question => "?",
            TokenKind::Bang => "!",
            TokenKind::Ellipsis => "...",
            TokenKind::At => "@",
            TokenKind::Hash => "#",
            TokenKind::Tick => "'",
            TokenKind::Newline => "\n",
            TokenKind::Indent => "",
            TokenKind::Dedent => "",
            TokenKind::BitAndEq => "&=",
            TokenKind::BitOrEq => "|=",
            TokenKind::BitXorEq => "^=",
            TokenKind::Eof => "",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub line: usize,
    pub col: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LexerMode {
    Production,
    Sketch,
}
